### ISSUE TITLE
God Mode and Infinite Mana

### ISSUE THREAD

**Issue by skooch** [Pryaxis/TShock#110]
A feature that allows the player to have infinite mana and infinite health and to be impervious to all substances. (Because the "ouch" noises would just get annoying)

Example Commands:
/god <player> - Toggles godmode for current player or if a player is specified, toggle it for them
/infmana <player> - Toggles infinite mana for current player or if a player is specified, toggle it for them
(/god includes health + impervious to substances)

Hopefully this can be implemented at sometime down the track, or whenever you guys want!

**Comment by gh-doot** [comment]
agree

**Comment by blixer-debug** [comment]
Not supported TShock
