### ISSUE TITLE
Missing config options.

### ISSUE THREAD

**Issue by tlworks** [Pryaxis/TShock#1399]
Though, not really `missing` here but mainly the fact some config options simply (still) do not work such as spawnrate, crim/cor-spread and probably some others. Most likely OTAPI related.

**Comment by tlworks** [comment]
Related to #1357

**Comment by ProfessorXZ** [comment]
Corruption spread has been fixed [81e21f31](https://github.com/Pryaxis/TShock/commit/81e21f31dc9f68d4db77f15dbb207d2b3373cb63). I'll keep this open until someone actually tests #1357

**Comment by ProfessorXZ** [comment]
Everything reported here is now working properly. Closing the issue.
