### ISSUE TITLE
Crash upon Server Exit.

### ISSUE THREAD

**Issue by tlworks** [Pryaxis/TShock#1428]
Now I am not sure whether this is caused by a plugin yet, might be the cause though.

https://i.gyazo.com/f246d51cad59e37879bda0e191b1d942.png

**Comment by ProfessorXZ** [comment]
Does this still happen/did anyone else confirm this?

**Comment by tanpro260196** [comment]
Still hapenning (sometimes) on my server.

**Comment by bartico6** [comment]
Used to recently happen on my server, but after updating from release 4.3.24 to one of the fresh general-devel builds it ceased. I think the issue can be closed.
