### ISSUE TITLE
GPL compliance

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1430]
We aren't apparently doing GPL compliance properly. We need to display a message when the server starts and provide a command to show the "no warranty" disclaimer apparently.

This is a great issue for a new contributor to do.

**Comment by Ijwu** [comment]
As far as I know, it is not required to display anything _within_ the software. As long as you include a copy of the license and warranty disclaimer with an installation in an easy to access place and format it should be ok.

**Comment by hakusaro** [comment]
@Ijwu would be nice imho

**Comment by GNUGradyn** [comment]
Nothing is required inside the software itself. 
https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

**Comment by Enerdy** [comment]
So whats the current call on this? Still on the do-or-not territory?

**Comment by Ijwu** [comment]
There isn't a decision in the works here, we're just too lazy to do this ourselves. A potential new contributor could submit something. Hell, it's till October for one more day. #Hacktoberfest
