### ISSUE TITLE
[Feature Request] Kick on not being Softcore.

### ISSUE THREAD

**Issue by tlworks** [Pryaxis/TShock#1437]
To prevent players from joining an getting kicked on a Medium/Hardcore character to begin with, why not add a feature to kick medium/hard-core in the first place so they don't have to go through that process.

**Comment by ProfessorXZ** [comment]
As far as I know tshock only has options to enable `MediumcoreOnly` and `˙HardcoreOnly`, thus I don't understand what this issue means.

**Comment by tanpro260196** [comment]
I think he/she want a `Softcore Only` option.

**Comment by QuiCM** [comment]
Should be a plugin really
