### ISSUE TITLE
plugins are loaded in root of filesystem

### ISSUE THREAD

**Issue by TimVNL** [Pryaxis/TShock#1441]
Hi,

I am using the latest build and it seems to create a ServerPlugins folder in de root instead of the tshock folder how can I fix this?

Mad a symlink for now

**Comment by hakusaro** [comment]
OS?

**Comment by TimVNL** [comment]
Docker Alpine Linux and debian

**Comment by hakusaro** [comment]
@TimVNL sorry for the delayed reply on this. Can you test with the latest build and give us the build number you tested on?

**Comment by TimVNL** [comment]
@hakusaro The build I have is t-1.3.5/1596 will test the latest tonight :)

**Comment by WhiteXZ** [comment]
This should be resolved in [build#1604](https://travis.tshock.co/general-devel/1604/). Testing would be appreciated

**Comment by TimVNL** [comment]
@WhiteXZ Still not fixed

**Comment by WhiteXZ** [comment]
@TimVNL what's your docker script?

**Comment by TimVNL** [comment]
@WhiteXZ see: https://github.com/TimVNL-Dockers/tshock

**Comment by QuiCM** [comment]
Likely related to https://github.com/Pryaxis/TerrariaAPI-Server/issues/142

**Comment by QuiCM** [comment]
Will be resolved by https://github.com/Pryaxis/TerrariaAPI-Server/pull/162
