### ISSUE TITLE
Stat tracker should track usage of -ignoreversion and all plugins

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1444]
We just need to add some data:

* -ignoreversion on/off
* List of loaded plugins

Why? It would help us make decisions better. If every server is using -ignoreversion and SEconomy, Marriage, and Essentials, we should at least be able to test to see if we're going to break that configuration horribly, before we change things that would break literally every server.

**Comment by ProfessorXZ** [comment]
This has been resolved in [1cdd33a](https://github.com/Pryaxis/TShock/commit/1cdd33a78a9aa9c4a0e5ad71590878652937d289)
