### ISSUE TITLE
Re-enable console redirected input

### ISSUE THREAD

**Issue by cokll** [Pryaxis/TShock#1450]
_See the feature description by Onsen below._ --@hakusaro

**Comment by Ijwu** [comment]
Your issue title asks how to remove console input but your description suggests you're already unable to enter commands. Please specifically state what the issue you're facing is and describe reproduction steps.

**Comment by cokll** [comment]
I use the pipeline to start TShock,I sent any instructions to TShock that did not respond.
In 1.3.4.4 I removed IsInputRedirected to use the instruction,But 1.3.5.3 I did not find a similar one.


`			if (Console.IsInputRedirected == true)
			{
				Console.WriteLine("TerrariaServer is running in the background and input is disabled.");
				return;
			}
`

**Comment by cokll** [comment]
@Ijwu so?

**Comment by Ijwu** [comment]
I apologize for the delay @cokll. To be honest, I've shared this issue with the dev team and we collectively acknowledge that we have no idea what you're asking.

**Comment by cokll** [comment]
In 1.3.4.4 there are Console.IsInputRedirected,But 1.3.5.3 I did not find a similar one. @Ijwu

**Comment by mistzzt** [comment]
Why you are still asking for `Console.IsInputRedirected`?
From what you said

> In 1.3.4.4 I removed IsInputRedirected to use the instruction

You just want the TShock send you an instruction like `TerrariaServer is running in the background and input is disabled.`?

**Comment by cokll** [comment]
@mistzzt I want to delete IsInputRedirected,I don't want the input to be disabled in the background.

**Comment by cokll** [comment]
@mistzzt I made a software to manage TShock.If the input is disabled, the status can not be obtained

**Comment by madman2021** [comment]
@cokll I'm trying to understand what you are asking, are you trying to use `System.Diagnostics.Process` to wrap the TShock binary and now it's not working for you ?

**Comment by OnsenManju** [comment]
Maybe he is asking "how to redirect own text to TShock's console by using pipeline, as if that was typed on console", I guess.

As you developers know, before TShock Mintaka (4.3.21), `TerrariaServerAPI/Terraria/Main.cs` had the following part:
```
public static void startDedInput()
{
	if (Console.IsInputRedirected == true)
	{
		Console.WriteLine("TerrariaServer is running in the background and input is disabled.");
		return;
	}

	Thread t = new Thread(Main.startDedInputCallBack);
	t.Name = "Console Input Thread";
	t.IsBackground = true;
	t.Start();
}

public static void startDedInputCallBack(object threadContext)
{
	while (!Netplay.disconnect)
	{
		Console.Write(": ");
		string str = Console.ReadLine();
		......
```
Removing the part he said will probably make it possible to use a way like this:
```
$ mkfifo /tmp/pipe
$ mono TerrariaServer.exe -world my.wld < /tmp/pipe &
$ echo "bc hello" > /tmp/pipe
$ echo "kick badguy" > /tmp/pipe
$ echo "restart" > /tmp/pipe
```

But now, vanilla part of Terraria is hidden into OTAPI, so people can't hack that easily.
I recommend using [REST API](https://tshock.readme.io/v4.3.22/reference#rest-api-endpoints) instead, or making custom plugin which captures `Console.ReadLine()` in some way, or whatever (not sure).

**Comment by DeathCradle** [comment]
Or perhaps the OTAPI 'startDedInput' hook can be used to run the required code as like premintaka

**Comment by cokll** [comment]
@OnsenManju Yes,So it can not be modified now.

**Comment by bskrtich** [comment]
I just ran this code via this [build](https://ci.appveyor.com/project/hakusaro/terrariaapi-server/build/85/artifacts) and it seems to fix the issue.

**Comment by hakusaro** [comment]
I'm not at all convince this is fixed: we got a report in #2003 that says that they want input redirection enabled and then again in Discord. I'm not sure entirely what @bskrtich was referring to other than I think he was wanting it to not crash as per #1487. I think the end solution is going to be having a command line flag to enable or disable input redirection.

**Comment by hskrtich** [comment]
@hakusaro Correct, the issue I was talking about was the crash fixed by #1487

**Comment by hakusaro** [comment]
Holy guacamole, you're alive! Thank you for the context! 💚

**Comment by hskrtich** [comment]
hah! I am! Have to keep my docker container for tshock/vanilla server working. Happy I could help!

**Comment by marco-jsf** [comment]
Hey There, in my case I'm running TShock as a python subprocess. I can write to the stdin stream but because of "TerrariaServer is running in the background and input is disabled" nothing happens.

If it's not possible to make a flag to disable the background mode. How can I trick mono into thinking, that the process is running in the foreground?

Thanks for your help!

**Comment by hakusaro** [comment]
This is a really reasonable request. Definitely reasonable and definitely something we'd want to get fixed, @dr4xor.
