### ISSUE TITLE
"/restart" Not implemented in Mono

### ISSUE THREAD

**Issue by VengeanceVenger** [Pryaxis/TShock#1454]
I run my server in a freenas jail with screen and mono. It works great until i try `/restart`. This makes my life a lot harder because I have to press `^C` and restart the screen and relaunch the server. Please this would be a lot of help for those of us with Linux and Mono. 

To Reproduce: *
1) Have a freenas jail with `screen` and `mono` installed. (install by typing `pkg install screen mono`.)
2) Now that those are installed, navigate to your directory with tshock and launch screen by typing `screen -S Terraria_Server`.
3) Now type `mono TerrariaServer.exe` to launch the server.
    *Note: Use attached world and config.json

Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Sat Apr 15 01:35:37 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

[Files.zip](https://github.com/NyxStudios/TShock/files/1027687/Files.zip)

Hope You find an answer,
                                       Venger

**Comment by QuiCM** [comment]
Does restart actually not exist on Mono, or is it just that the server sometimes hangs when trying to restart?

**Comment by hakusaro** [comment]
@QuiCM I want to remove this command from TShock as it's unreliable and crappy.

**Comment by Enerdy** [comment]
To be fair, dedicated server configurations never use /restart. With a batch file setup, you just use /off as a restart since your server is set to automatically start up again when the process dies so that crashes don't kill you until someone notices. Therefore I see no reason to keep this command, specially in the way it's implemented right now (ie kill the process and start it again).
