### ISSUE TITLE
[SSC/hardcore only] Hp and mana  are not reset to default sometimes on Tshock 4.2.24

### ISSUE THREAD

**Issue by slzn** [Pryaxis/TShock#1458]
I am playing a character in trustedadmin group and dead few times before, It always reset to default hp, mana and inventory. 
But this happens to me last night. After character dead, I created a new one with same name and reconnect to server, I found that inventory is empty, but hp and mana are remain 400/200(default should be 100/20), any idea ?

It also happens to a character with chinese name '封塵' in default group. I thought that may be the chinese name causes this issue, but my character is named 'SLZN', and it happens to me too. 

NOTE: When this happened, It always happens to this named character.

trustedadmin permissions:
tshock.cfg.maintenance, tshock.cfg.*, tshock.world.*, tshock.npc.butcher, 
tshock.item.spawn, tshock.item.give, tshock.heal, tshock.admin.noban, 
tshock.item.usebanned, tshock.admin.group, tshock.ignore.removetile, 
tshock.ignore.liquid, tshock.superadmin.user, tshock.admin.ban, 
tshock.cfg.whitelist, tshock.world.time.*, tshock.npc.spawnboss, 
tshock.npc.spawnmob, tshock.admin.warp, tshock.world.time.set, tshock.tp.self, 
tshock.slap, tshock.kill, tshock.admin.viewlogs, tshock.admin.nokick, 
tshock.tp.others, tshock.admin.kick, tshock.world.editspawn, 
tshock.reservedslot, tshock.warp, tshock.account.changepassword, 
tshock.account.logout, tshock.tp.home, tshock.npc.summonboss, 
tshock.tp.wormhole, tshock.world.modify, tshock.account.register, 
tshock.account.login, tshock.partychat, tshock.thirdperson, tshock.canchat

**Comment by QuiCM** [comment]
Maybe something @mistzzt can check for us

**Comment by mistzzt** [comment]
Tested on travis build 1891 of branch general-devel.
![image](https://user-images.githubusercontent.com/12794966/33816949-6f4baffa-ddf1-11e7-98df-72b5b4eb76fc.png)
Though it is unrelated, I'd like to point out that the kick system is buggy: player name was not displayed in console; the kick message was not shown in game. (I tested with a English character name 'test')

However, the command with `kick test` behaved properly.

## Test Process
1. create a player with name `封塵`, hardcore.
2. join ssc-enabled, hardcore only tshock server.
3. use Life Crystals.
4. kill player
5. recreate a new player with same name and hardcore.
6. join server.

The SSC system worked properly and reset them in the latest build (1891).
