### ISSUE TITLE
[Feature Request] Ban Message Format.

### ISSUE THREAD

**Issue by tlworks** [Pryaxis/TShock#1464]
I mean, I get the point that when not issuing a temporary ban it would most likely mean that the ban would be "forever". But wouldn't it be better to have a configurable format rather than having it notifying the player it's forever since it _could_ be misleading to some.

Config concept:
`"BanFormat": ""`

**Comment by Enerdy** [comment]
Not sure why exactly this was left unnoticed — it’s actually a good idea.

I would be willing to put some work on this, seems like an easy implementation. Is there any cons to this addition? (having to modify config format so needs default behaviour for if empty for backwards compatibility, etc)

**Comment by Enerdy** [comment]
To expand on my why this could be a good idea: depending on the target community, if ban appeals are a thing, then the ability to set a default ban reason could save some work to its administrators by automatically giving off the link to a page where such can be done. @tlworks ban reasons are already a thing I believe, even for permanent bans, but you need to append them to the command or otherwise it will default to forever (?). I’m not too keen on this, still need to investigate on our current implementation.

**Comment by QuiCM** [comment]
IMO this would be better served as a hook - perhaps with a default TShock impl. that uses a config field.
I.E., if a user joins and is kicked because banned, invoke hook.

**Comment by Enerdy** [comment]
@QuiCM that would allow for further customization. Hooks are great! Are you suggesting a hook specifically for banned players who try to join? (BannedUserJoin)

**Comment by QuiCM** [comment]
That is indeed what I am suggesting

**Comment by bartico6** [comment]
Late bump:
```@tlworks ban reasons are already a thing I believe, even for permanent bans, but you need to append them to the command or otherwise it will default to forever (?). I’m not too keen on this, still need to investigate on our current implementation.```
He meant ban kick message formatting. You know, this:
![Screenshot](http://i.quake.tf/1509856333-9959471142.png)

**Comment by hakusaro** [comment]
Personally I don't really see needing a hook for this at present. However, the message was changed to "Banned for x seconds for [reason]" in #1515. Okay, this is a little tiny bit non-human readable (good luck with your seconds conversions)?

It just seems kinda crummy to make a huge config option out of one message used by one command, imho.

**Comment by hakusaro** [comment]
(Or a hook)

**Comment by QuiCM** [comment]
I think you meant #1512 @hakusaro ;o

**Comment by hakusaro** [comment]
Yep can confirm @QuiCM

**Comment by hakusaro** [comment]
Okay @QuiCM so looking at this more: he just wants this configurable and as it stands, I don't think we need to do that. Do you agree?

**Comment by QuiCM** [comment]
Given upcoming extensive changes to the ban system, I'll close this and merge the suggestion into #1511
