### ISSUE TITLE
v4.3.24.0 REST API /users/create endpoint is storing plain-text passwords

### ISSUE THREAD

**Issue by haxandsnax** [Pryaxis/TShock#1467]
When creating accounts with the REST API /users/create endpoint, the specified password is stored as plain-text and is not hashed / encrypted. This is causing login errors for new users because it's trying to verify the hash against a plain-text password. I have to update the password with a server command to be able to log in at all.

![image](https://user-images.githubusercontent.com/29994959/27982754-6edf952e-6379-11e7-8db9-ed59f225e860.png)

Here **h1v1j3z1** is the password.

**Comment by Ijwu** [comment]
Confirmed issue.

Someone forgot to hash this shit: https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/Rest/RestManager.cs#L523

@QuiCM Your turn. Make a PR and fix this. I tracked it down for you and everything. :)

**Comment by haxandsnax** [comment]
I can fix this real quick if you want?
