### ISSUE TITLE
High priority issue: Fix Buff Timers.

### ISSUE THREAD

**Issue by tlworks** [Pryaxis/TShock#1469]
Issued filed after contacting @MarioE on Discord.

Issue: Whenever a buff goes past a certain value, it'll crash the client. Now I am not sure about whether cheated client can force buffs on players but I suddenly had a 94 day buff on my Character and my client froze due to this. Nobody had used any kind of command that can force buffs on players therefore I guess it's someone's doing by using a cheated client or packet changer.

Image: 
![clientbuff](https://user-images.githubusercontent.com/19647337/27988361-6f475f22-6420-11e7-81fd-4ca1b0ab91e7.png)

**Comment by hakusaro** [comment]
@MarioE?

**Comment by ProfessorXZ** [comment]
@hakusaro IIRC buff time has been changed to an `int` to extend buff durations but TShock's data handler is still reading shorts from the stream.
