### ISSUE TITLE
Tool to make plugins in javascript: TShockJS

### ISSUE THREAD

**Issue by PixelPlugins** [Pryaxis/TShock#1472]
If you find it annoying  to make plugins in c# or you can't find out how (the first problem I had), then try out a developer tool plugin I made called TShockJS. (https://github.com/PixelPlugins/TShockJS).
Follow the instructions in the readme and then go to the wiki to see how to make a plugin.
This is similar to minecraft scriptcraft but for terraria.

**Comment by Ijwu** [comment]
Feel free to submit this to the resource manager on tshock.co

Closing this, seeing as this _isn't an issue._
