### ISSUE TITLE
Fix code feedback for #1445 and update changelog

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1478]
![36bf860a-32dc-4b37-a933-ca12d1c67e66](https://user-images.githubusercontent.com/532647/28254422-e85e4282-6a69-11e7-8741-84d9e5413f69.png)

**Comment by deadsurgeon42** [comment]
uh where's #1445 even? Can't find it on pulls or issues on either tshock or terrariaapi-server.

**Comment by hakusaro** [comment]
The pull request was deleted.
