### ISSUE TITLE
Build project in release mode.

### ISSUE THREAD

**Issue by Leeleo3x** [Pryaxis/TShock#1480]
I'm trying to build the whole project including TShockAPI, TerrariaServerAPI and TShock.4.OTAPI with release configuration. I got an error about missing OTAPI because in TerrariaServerAPI.csproj and TShockAPI.csproj,  msbuild is only suggested to find OTAPI in Debug folder https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/TShockAPI.csproj#L77. 

Adding more HintPaths can fix the error and I'm bringing one PR which will fix it.

**Comment by hakusaro** [comment]
Did you nuget restore?

**Comment by Leeleo3x** [comment]
Yeah but restore wont fix because I'm not building TShock.4.OTAPI  with debug configuration.
