### ISSUE TITLE
Could someone please tell me how to add the TerrariaAPI which is needed for certain plugins

### ISSUE THREAD

**Issue by TomTheHero** [Pryaxis/TShock#1482]
I want to add the TerrariaAPI to my server which is needed for certain plugins but there ain't a single readme or tutorial explaining how to add it.

**Comment by hakusaro** [comment]
https://tshock.readme.io/docs/getting-started

**Comment by TomTheHero** [comment]
That does not explain anything about the TerrariaAPI that you can add to it

**Comment by hakusaro** [comment]
Did you do it?

**Comment by hakusaro** [comment]
The api is distributed with TShock.

**Comment by hakusaro** [comment]
It’s literally the server exe we ship

**Comment by hakusaro** [comment]
Uh, do you understand now?
