### ISSUE TITLE
Mono out of sync: System.dll

### ISSUE THREAD

**Issue by That-Tea-Hoe** [Pryaxis/TShock#1502]
TShock 4.3.24

Ran the server with `mono TerrariaServer.exe`,

The server ran beautifully on startup, took everything I could throw at it in the shell, however, as soon as I or another person were to join the server would crash, I am using tmux on Ubuntu Yakkety 16.10 (latest) and to upload the file I used PuTTY's pscp file transfer to upload the zip and extracted with unzip

![image](https://user-images.githubusercontent.com/20776314/31723058-bb311ed8-b415-11e7-9ab2-def8ea032ec5.png)

**Comment by hakusaro** [comment]
Please update your mono install.

![screen shot 2017-10-18 at 08 19 07](https://user-images.githubusercontent.com/532647/31723793-0cdfbc0a-b3dd-11e7-9056-4ad37269c2c4.png)
![screen shot 2017-10-18 at 08 18 54](https://user-images.githubusercontent.com/532647/31723794-0cf563fc-b3dd-11e7-97b3-aae38ccd7df6.png)

**Comment by hakusaro** [comment]
_We've closed this issue as it isn't related to TShock. If you need help updating Mono, please let us know._

**Comment by That-Tea-Hoe** [comment]
Mono is freshly installed, there are no updates.

**Comment by hakusaro** [comment]
```mono --version```?

**Comment by That-Tea-Hoe** [comment]
![image](https://user-images.githubusercontent.com/20776314/31724256-26ad0ebc-b419-11e7-9625-998be0b1bfe9.png)

**Comment by hakusaro** [comment]
Okay, so, unfortunately, you still have a broken mono install. Updating would've been my easy fix.

What is inside ```/root/Terraria/1353/Linux/``` and why does it have a System.dll that's out of sync with the system mono version?

**Comment by hakusaro** [comment]
Also, you should **really not run mono or TShock as root** as indicated by your ```/root/``` home folder storing Terraria.

Normally, I would point to the official mono instructions for installation, but I'm at a loss because they appear to not have instructions for 16.10. I'm guessing this is why your install is so weird. You compiled it yourself, right?

**Comment by That-Tea-Hoe** [comment]
[reference to the instructions](http://www.mono-project.com/download/#download-lin)

root, doesn't seem to have any effect as far as I've noticed with TShock, I'll look into mono

**Comment by hakusaro** [comment]
Root is just not a secure way to run any Linux application. If any vulnerability exists in Terraria or in TShock or in Mono, your entire system is owned.

Your best bet is to compile mono from git source and purge all existing mono installations. To be honest, if you aren't married to that box, I would reinstall the LTS version of Ubuntu too -- their non LTS releases can be a bit funky as far as third party developer support goes.

**Comment by tylerjwatson** [comment]
> What is inside /root/Terraria/1353/Linux/ and why does it have a System.dll that's out of sync with the system mono version?

You should answer this question with a `tree /root/Terraria/1353`. I don't know how you ended up with a copy of mscorlib underneath a Linux folder in your installation but I can guarantee that's a culprit.

Install mono from the xamarin ppas, and then leave it alone. There should be no reason to touch the runtime after that.
