### ISSUE TITLE
Discouraging superadmin use

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1505]
Us: "You should never use super admin. It's for initial config only."
Also us: "You can customize the colors for super admin in chat!"

If we changed this to "no, you can't customize superadmin chat colors" it would probably force a lot of people to not use superadmin. Not kidding -- since most people value displaying their rank, if we forced it to the default color and stopped people from changing it, it might help stop people from using it.

Other ideas I've had:

- Change the onboarding process to just give users an admin account with a really good set of permissions, but not every permission. Specifically, we'd leave out the ignore permissions, the anti-hack stuff, all that jazz.
- Implement a su system, so you can temporarily become a superadmin, but it times out after a few minutes and cannot be activated permanently.
- Prevent super admins from chatting.

Thoughts?

**Comment by QuiCM** [comment]
Temporary activation sounds good - similar to the admin controls of xF, where you need to re-authenticate to enter, with a short authenticated session

**Comment by hakusaro** [comment]
GitHub's "you are entering sudo mode" is also a good analogy. Requires re-entry of password and expires when not used.

**Comment by bartico6** [comment]
Both of those systems are based off linux sudo btw

**Comment by hakusaro** [comment]
I definitely think making an admin group that's at least well granted will help fix problems like in #1503.

**Comment by Brycey92** [comment]
One of the appeals of superadmin is that it gets the * permission, so any added plugins will automatically be accessible by the superadmin. Perhaps (a/the) new stock group could be created starting with * and have several default negated permissions from there?

I'm also in favor of unspecial superadmin chat, su command, and su timeouts.

**Comment by bartico6** [comment]
If you give any rank *, all plugins will be compatible since * nodes work on every plugin.
Superadmin should not exist, you should be able to /su (since /sudo will both a) conflict with Essentials+ and b) sudo in modern versions allows running as any user) and create their main group and later, the rank they want.

**Comment by hakusaro** [comment]
In a private channel, concerns were raised by another developer over this act of discouragement. It was brought to our attention that some users may find it perfectly acceptable to play as S.A.

This discussion was brought up after the fact, however, we are still accepting input (and would like input) on how we handled this issue. @Brycey92 do you feel that the new owner group with su/sudo is a good permission set? Or no?

**Comment by Brycey92** [comment]
The new commit appears to implement /su in a comprehensive and effective way (I haven't tested it yet, but I looked at the commit). As for the owner group, I see it inherits from the trustedadmin group, which has a few more groups in the chain it inherits from. To voice my opinion on whether the default permission set for owner is good, I would need to see/create a list of all vanilla TShock permissions with visual indicators like check marks or colored highlights for whether the owner group has the permission. I don't suppose there's an Excel or Google Sheets type document for permissions already, is there?

**Comment by hakusaro** [comment]
Nope, it's probably hard to make any assumptions about that group because it was fairly lackluster to begin with. Permissions have long since been added without any care in the world towards the default groups. Perhaps this is an issue that should be marked as "ongoing" -> the re-definition of all group permission sets by default.

**Comment by Brycey92** [comment]
I think that's a good idea, though it may be a better idea to put in another issue thread, since it would be more than just for discouraging superadmin use.

Side note: I play as a custom "owner" group currently, which I granted the * permission, and subtracted a couple of permissions that I don't want or that break gameplay, so that could be an option for those who prefer playing on the current superadmin account and dislike the discouragement.

**Comment by hakusaro** [comment]
@Brycey92 you were one step ahead of me. See #1519. Working on a matrix right now.
