### ISSUE TITLE
Bypass SSC shouldn't prevent someone from forcing an SSC save

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1506]
As discussed in #1503, right now the method that saves SSC data will return true (indicating that the data save was successful) if a save request happens and the player is a super admin. It also denies this request.

This method should be changed to:

- Not return true when the super admin tries to be saved.
- Permit the /savessc command to actually run the save operation as opposed to just ignoring it.

Potential solution:
- Overload the save method to allow forcing a save even if the user is bypassing ssc and permit the save command to work without auto save.

**Comment by bartico6** [comment]
Followup on above solution:  
  
Add a default parameter "force" which takes the def value false, and then in all of those "disqualifying" checks do "&& !force"
