### ISSUE TITLE
ITEM FRAME ERROR

### ISSUE THREAD

**Issue by OrOlLover** [Pryaxis/TShock#1507]
## Any stack traces that may have happened when the issue occurred

I am playing with t.shock.
I am going to use the "Item Frame" to display items.
As soon as I hold the items and right click, the weapon is on display.
But as soon as I click on the displayed items, the items disappears!
"Item Frame" is different when placed on the floor and when hang on the wall.
When hang on the wall, it works normally.

There is no problem using the default server driver, not t.shock.

![1](https://user-images.githubusercontent.com/33578913/32691991-ca9e529a-c753-11e7-92bd-84d814f3f977.png)
![2](https://user-images.githubusercontent.com/33578913/32691992-cac77242-c753-11e7-9fe3-fe042d819e52.png)
![3](https://user-images.githubusercontent.com/33578913/32691993-caf05856-c753-11e7-8071-86f310fd6101.png)
![4](https://user-images.githubusercontent.com/33578913/32691994-cb1c8304-c753-11e7-84d6-b9cbd4d5789d.png)
![5](https://user-images.githubusercontent.com/33578913/32691995-cb44d73c-c753-11e7-8a37-cdd70bef23b4.png)

**Comment by mistzzt** [comment]
Could you please help test the vanilla server?
Does the item frame behave properly on the vanilla server?

**Comment by bartico6** [comment]
From what he said in the issue it would seem that it works properly in vanilla:
>There is no problem using the default server driver, not t.shock.

**Comment by mistzzt** [comment]
It's likely related to [this line](https://github.com/Pryaxis/TShock/blob/51ff8483cd4b4b49970d18e4f56e6195bd88f7d7/TShockAPI/GetDataHandlers.cs#L4379).

```csharp
			if (itemFrame.item?.netID == args.TPlayer.inventory[args.TPlayer.selectedItem]?.netID)
			{
				NetMessage.SendData((int)PacketTypes.UpdateTileEntity, -1, -1, NetworkText.Empty, itemFrame.ID, 0, 1);
				return true;
			}
```
I don't know what the mechanism does; commenting out this block will prevent item from disappearing.

**Comment by OrOlLover** [comment]
amazing! I respect you.

But, I can not find the script file for T.shock.
Is there a script in the T.shock folder I downloaded?

**Comment by mistzzt** [comment]
It's a issue related to TShock.
You don't have to anything actually.. Just wait for a new version of TShock.

**Comment by OrOlLover** [comment]
Will the next version of T.shock be released after the next version of Terraria?
AND Thank you
I hope my bug discovery will help fix Item Frame Error.
I respect the feedback and effort of the developers who answer simple personal questions.

**Comment by hakusaro** [comment]
@OrOlLover no promises but we might get a new release soon (and this might be fixed in it)

**Comment by hakusaro** [comment]
@mistzzt from Ivan in discord:

> the issue in fact is the code you posted. That piece of code goes back to 1.3.3/4(?) when item frames allowed you to duplicate placed items. The mechanism has probably changed and caused the current code to break because I believe everything worked fine prior to pushing that code
So feel free to remove it now but make sure everything is kept in tact and check if youre able to duplicate items after you remove it
