### ISSUE TITLE
Can SSC save a list of "Mark as favorite" items?

### ISSUE THREAD

**Issue by daiaji** [Pryaxis/TShock#1514]
## TShock version
tshock_4.3.24

## Screenshots of the problem, if applicable
![74d074b3b7af64f58af7da62e9da51a2](https://user-images.githubusercontent.com/25875791/33514503-fbaff68a-d78f-11e7-8aa9-0262ae6bb5c8.PNG)

The list of items for "Mark as favorite" seems to be unsaved

**Comment by hakusaro** [comment]
I personally have no idea if this is networked or not. I would assume it isn't?

**Comment by bartico6** [comment]
You're correct @hakusaro.
It is not networked to the server, so the server cannot remember if you have something favorited or not. That's a Terraria bug/issue, and to answer the question - no, it cannot.

**Comment by hakusaro** [comment]
Well, that's unfortunate.

**Comment by daiaji** [comment]
😭

**Comment by hakusaro** [comment]
@daiaji I'll let you know if I hear back (I asked for it to be networked).

**Comment by daiaji** [comment]
@hakusaro If it is not networking content
Can I send a list of "Mark as favorite" items to the server by creating a "tModLoader" module?😏

**Comment by ivanbiljan** [comment]
Since we're asking for stuff can we (you) ask them to send the actual buffTime for buffs too (see issue #1452)?

**Comment by hakusaro** [comment]
DOne.

**Comment by hakusaro** [comment]
@daiaji I wanted to update you: this request has been heard and triaged, but may not happen. Depends on developer energy and such.
