### ISSUE TITLE
Revise default permission set

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1519]
This is the issue to track discussion from #1505 post merge of /su and /sudo. I hope this discussion takes less than 24 hours (and I hope to have a proposed new permission set in the next 12 hours). I'm really getting sick of everything in this project taking 7.8 decades to get merged.

Step 1: Generate a matrix of permissions so we can figure out what goes where.

**Comment by Brycey92** [comment]
Is this matrix of permissions currently in a publicly viewable location?

**Comment by hakusaro** [comment]
@Brycey92 I'll throw it in this issue as soon as I'm done generating it.

**Comment by hakusaro** [comment]
And lo, a matrix! @Brycey92, here ya go.

|Permission|guest|default|newadmin|admin|trustedadmin|owner|vip|superadmin|
|-------|-------|-------|-------|-------|-------|-------|-------|-------|
|tshock.accountinfo.details||||||||✔|
|tshock.ignore.sendtilesquare||||||||✔|
|tshock.ignore.dropbanneditem||||||||✔|
|tshock.annoy||||||||✔|
|tshock.admin.antibuild||||||||✔|
|tshock.admin.ban||||✔|✔|✔||✔|
|tshock.world.time.bloodmoon||||✔|✔|✔||✔|
|tshock.admin.broadcast||||||||✔|
|tshock.buff.self||||||||✔|
|tshock.buff.others||||||||✔|
|tshock.npc.butcher|||||✔|✔||✔|
|tshock.ignore.ssc||||||||✔|
|tshock.world.modify|✔|✔|✔|✔|✔|✔|✔|✔|
|tshock.account.changepassword||✔|✔|✔|✔|✔|✔|✔|
|tshock.canchat|✔|✔|✔|✔|✔|✔|✔|✔|
|tshock.account.login|✔|✔|✔|✔|✔|✔|✔|✔|
|tshock.account.logout||✔|✔|✔|✔|✔|✔|✔|
|tshock.world.paint|||||✔|✔||✔|
|tshock.partychat|✔|✔|✔|✔|✔|✔|✔|✔|
|tshock.account.register|✔|✔|✔|✔|✔|✔|✔|✔|
|tshock.thirdperson|✔|✔|✔|✔|✔|✔|✔|✔|
|tshock.projectiles.usebanned||||||||✔|
|tshock.tiles.usebanned||||||||✔|
|tshock.cfg.password|||||✔|✔||✔|
|tshock.cfg.reload|||||✔|✔||✔|
|tshock.accountinfo.check||||||||✔|
|tshock.clear||||||||✔|
|tshock.npc.clearanglerquests||||||||✔|
|tshock.world.converthardmode|||||✔|✔||✔|
|tshock.world.time.dropmeteor||||✔|✔|✔||✔|
|tshock.world.setdungeon|||||✔|✔||✔|
|tshock.world.time.eclipse||||✔|✔|✔||✔|
|tshock.world.editregion|||||✔|✔||✔|
|tshock.world.editspawn|||✔|✔|✔|✔||✔|
|tshock.world.time.fullmoon||||✔|✔|✔||✔|
|tshock.tp.getpos||||||||✔|
|tshock.item.give|||||✔|✔||✔|
|tshock.godmode||||||||✔|
|tshock.godmode.other||||||||✔|
|tshock.world.grow|||||✔|✔||✔|
|tshock.world.sethalloween|||||✔|✔||✔|
|tshock.world.hardmode|||||✔|✔||✔|
|tshock.heal|||||✔|✔||✔|
|tshock.tp.home||||||||✔|
|tshock.npc.hurttown||||||||✔|
|tshock.ignore.damage||||||||✔|
|tshock.ignore.hp||||||||✔|
|tshock.ignore.removetile||||||||✔|
|tshock.ignore.liquid||||||||✔|
|tshock.ignore.mp||||||||✔|
|tshock.ignore.noclip||||||||✔|
|tshock.ignore.paint||||||||✔|
|tshock.ignore.placetile||||||||✔|
|tshock.ignore.projectile||||||||✔|
|tshock.ignore.itemstack||||||||✔|
|tshock.admin.noban|||||✔|✔||✔|
|tshock.admin.nokick||||✔|✔|✔||✔|
|tshock.npc.invade||||||||✔|
|tshock.item.spawn|||||✔|✔||✔|
|tshock.admin.kick|||✔|✔|✔|✔||✔|
|tshock.kill||||✔|✔|✔||✔|
|tshock.admin.viewlogs||||✔|✔|✔||✔|
|tshock.cfg.maintenance|||||✔|✔||✔|
|tshock.admin.group||||||||✔|
|tshock.admin.itemban||||||||✔|
|tshock.admin.projectileban||||||||✔|
|tshock.admin.region||||||||✔|
|tshock.admin.tileban||||||||✔|
|tshock.admin.warp||||✔|✔|✔||✔|
|tshock.npc.maxspawns||||||||✔|
|tshock.world.movenpc|||||✔|✔||✔|
|tshock.admin.mute||||||||✔|
|tshock.world.rain|||||✔|✔||✔|
|tshock.npc.rename||||||||✔|
|tshock.reservedslot|||✔|✔|✔|✔|✔|✔|
|tshock.tp.rod||||||||✔|
|tshock.world.sandstorm|||||✔|✔||✔|
|tshock.admin.savessi||||||||✔|
|tshock.admin.seeplayerids||||||||✔|
|tshock.info||||||||✔|
|tshock.admin.tempgroup||||||||✔|
|tshock.slap||||✔|✔|✔||✔|
|tshock.tp.spawn||||||||✔|
|tshock.npc.spawnboss||||✔|✔|✔||✔|
|tshock.npc.spawnmob||||✔|✔|✔||✔|
|tshock.npc.spawnrate||||||||✔|
|tshock.npc.startdd2||||||||✔|
|tshock.npc.startinvasion||||||||✔|
|tshock.su||||||✔||✔|
|tshock.npc.summonboss||||||||✔|
|tshock.world.time.set||||✔|✔|✔||✔|
|tshock.world.toggleexpert|||||✔|✔||✔|
|tshock.world.toggleparty|||||✔|✔||✔|
|tshock.tp.self||||✔|✔|✔||✔|
|tshock.tp.allothers||||||||✔|
|tshock.tp.block||||||||✔|
|tshock.tp.npc||||||||✔|
|tshock.tp.others||||✔|✔|✔||✔|
|tshock.tp.override||||||||✔|
|tshock.tp.pos||||||||✔|
|tshock.tp.silent||||||||✔|
|tshock.cfg.updateplugins|||||✔|✔||✔|
|tshock.ssc.upload||||||||✔|
|tshock.ssc.upload.others||||||||✔|
|tshock.item.usebanned|||||✔|✔||✔|
|tshock.superadmin.user||||||||✔|
|tshock.admin.userinfo||||||||✔|
|tshock.world.time.usesundial||||✔|✔|✔||✔|
|tshock.warp||✔|✔|✔|✔|✔|✔|✔|
|tshock.whisper||||||||✔|
|tshock.cfg.whitelist||||✔|✔|✔||✔|
|tshock.world.wind|||||✔|✔||✔|
|tshock.world.info|||||✔|✔||✔|
|tshock.world.save|||||✔|✔||✔|
|tshock.world.settleliquids|||||✔|✔||✔|
|tshock.world.setspawn|||||✔|✔||✔|
|tshock.tp.wormhole||||||||✔|
|tshock.world.setxmas|||||✔|✔||✔|

**Comment by Brycey92** [comment]
It's impressive, but is there a way to view the full width at once? Github is forcing it into the narrow comment box size.

**Comment by Brycey92** [comment]
Actually, better yet, you might be able dump this into a Google Sheets document and allow commenting so people can suggest checkmarks directly. Up to you.

**Comment by hakusaro** [comment]
@Brycey92 you can view this in https://docs.google.com/spreadsheets/d/1R5_pTMeY2Z73-DPSdliuEDM38c6VHpA6qQLXY8D9jPM/edit?usp=sharing

**Comment by hakusaro** [comment]
It's important to note that this isn't _explicit_ permissions. So a lot of these can be viewed as constructed through in inheritance relationships and other things. The actual construction call for the default groups is:

```csharp
AddDefaultGroup("guest", "",
  string.Join(",", Permissions.canbuild, Permissions.canregister, Permissions.canlogin, Permissions.canpartychat,
    Permissions.cantalkinthird, Permissions.canchat));

AddDefaultGroup("default", "guest",
  string.Join(",", Permissions.warp, Permissions.canchangepassword, Permissions.canlogout));

AddDefaultGroup("newadmin", "default",
  string.Join(",", Permissions.kick, Permissions.editspawn, Permissions.reservedslot));

AddDefaultGroup("admin", "newadmin",
  string.Join(",", Permissions.ban, Permissions.whitelist, "tshock.world.time.*", Permissions.spawnboss,
    Permissions.spawnmob, Permissions.managewarp, Permissions.time, Permissions.tp, Permissions.slap,
    Permissions.kill, Permissions.logs,
    Permissions.immunetokick, Permissions.tpothers));

AddDefaultGroup("trustedadmin", "admin",
  string.Join(",", Permissions.maintenance, "tshock.cfg.*", "tshock.world.*", Permissions.butcher, Permissions.item, Permissions.give,
    Permissions.heal, Permissions.immunetoban, Permissions.usebanneditem));

AddDefaultGroup("owner", "trustedadmin", string.Join(",", Permissions.su));

AddDefaultGroup("vip", "default", string.Join(",", Permissions.reservedslot));
```

**Comment by hakusaro** [comment]
New matrix (proposed):

|Permission|guest|default|vip|newadmin|admin|trustedadmin|owner|superadmin|
|-------|-------|-------|-------|-------|-------|-------|-------|-------|
|tshock.accountinfo.details|||||✔|✔|✔|✔|
|tshock.ignore.sendtilesquare||||||✔|✔|✔|
|tshock.ignore.dropbanneditem|||||||✔|✔|
|tshock.annoy||||✔|✔|✔|✔|✔|
|tshock.admin.antibuild|||||||✔|✔|
|tshock.admin.ban|||||✔|✔|✔|✔|
|tshock.world.time.bloodmoon||||✔|✔|✔|✔|✔|
|tshock.admin.broadcast|||||✔|✔|✔|✔|
|tshock.buff.self||||||✔|✔|✔|
|tshock.buff.others||||||✔|✔|✔|
|tshock.npc.butcher||||||✔|✔|✔|
|tshock.ignore.ssc||||||||✔|
|tshock.world.modify|✔|✔|✔|✔|✔|✔|✔|✔|
|tshock.account.changepassword||✔|✔|✔|✔|✔|✔|✔|
|tshock.canchat|✔|✔|✔|✔|✔|✔|✔|✔|
|tshock.account.login|✔|✔|✔|✔|✔|✔|✔|✔|
|tshock.account.logout||✔|✔|✔|✔|✔|✔|✔|
|tshock.world.paint||✔|✔|✔|✔|✔|✔|✔|
|tshock.partychat|✔|✔|✔|✔|✔|✔|✔|✔|
|tshock.account.register|✔|✔|✔|✔|✔|✔|✔|✔|
|tshock.thirdperson|✔|✔|✔|✔|✔|✔|✔|✔|
|tshock.projectiles.usebanned|||||||✔|✔|
|tshock.tiles.usebanned|||||||✔|✔|
|tshock.cfg.password||||||✔|✔|✔|
|tshock.cfg.reload||||||✔|✔|✔|
|tshock.accountinfo.check||||✔|✔|✔|✔|✔|
|tshock.clear||||||✔|✔|✔|
|tshock.npc.clearanglerquests||||||✔|✔|✔|
|tshock.world.converthardmode||||||✔|✔|✔|
|tshock.world.time.dropmeteor||||✔|✔|✔|✔|✔|
|tshock.world.setdungeon||||||✔|✔|✔|
|tshock.world.time.eclipse||||✔|✔|✔|✔|✔|
|tshock.world.editregion||||||✔|✔|✔|
|tshock.world.editspawn||||✔|✔|✔|✔|✔|
|tshock.world.time.fullmoon||||✔|✔|✔|✔|✔|
|tshock.tp.getpos||||✔|✔|✔|✔|✔|
|tshock.item.give||||||✔|✔|✔|
|tshock.godmode||||||✔|✔|✔|
|tshock.godmode.other||||||✔|✔|✔|
|tshock.world.grow||||||✔|✔|✔|
|tshock.world.sethalloween||||||✔|✔|✔|
|tshock.world.hardmode||||||✔|✔|✔|
|tshock.heal||||||✔|✔|✔|
|tshock.tp.home|||||✔|✔|✔|✔|
|tshock.npc.hurttown||||||||✔|
|tshock.ignore.damage||||||✔|✔|✔|
|tshock.ignore.hp||||||✔|✔|✔|
|tshock.ignore.removetile||||||✔|✔|✔|
|tshock.ignore.liquid||||||✔|✔|✔|
|tshock.ignore.mp||||||✔|✔|✔|
|tshock.ignore.noclip||||||✔|✔|✔|
|tshock.ignore.paint||||||✔|✔|✔|
|tshock.ignore.placetile||||||✔|✔|✔|
|tshock.ignore.projectile||||||✔|✔|✔|
|tshock.ignore.itemstack||||||✔|✔|✔|
|tshock.admin.noban||||||✔|✔|✔|
|tshock.admin.nokick|||||✔|✔|✔|✔|
|tshock.npc.invade||||||✔|✔|✔|
|tshock.item.spawn||||||✔|✔|✔|
|tshock.admin.kick||||✔|✔|✔|✔|✔|
|tshock.kill|||||✔|✔|✔|✔|
|tshock.admin.viewlogs|||||✔|✔|✔|✔|
|tshock.cfg.maintenance||||||✔|✔|✔|
|tshock.admin.group|||||||✔|✔|
|tshock.admin.itemban|||||||✔|✔|
|tshock.admin.projectileban|||||||✔|✔|
|tshock.admin.region|||||||✔|✔|
|tshock.admin.tileban|||||||✔|✔|
|tshock.admin.warp|||||✔|✔|✔|✔|
|tshock.npc.maxspawns|||||||✔|✔|
|tshock.world.movenpc||||||✔|✔|✔|
|tshock.admin.mute||||✔|✔|✔|✔|✔|
|tshock.world.rain||||||✔|✔|✔|
|tshock.npc.rename|||✔|✔|✔|✔|✔|✔|
|tshock.reservedslot|||✔|✔|✔|✔|✔|✔|
|tshock.tp.rod||||✔|✔|✔|✔|✔|
|tshock.world.sandstorm||||||✔|✔|✔|
|tshock.admin.savessi||||✔|✔|✔|✔|✔|
|tshock.admin.seeplayerids||||✔|✔|✔|✔|✔|
|tshock.info|||||||✔|✔|
|tshock.admin.tempgroup|||||||✔|✔|
|tshock.slap|||||✔|✔|✔|✔|
|tshock.tp.spawn||||||||✔|
|tshock.npc.spawnboss|||||✔|✔|✔|✔|
|tshock.npc.spawnmob|||||✔|✔|✔|✔|
|tshock.npc.spawnrate|||||||✔|✔|
|tshock.npc.startdd2||||||✔|✔|✔|
|tshock.npc.startinvasion|||✔|✔|✔|✔|✔|✔|
|tshock.su|||||||✔|✔|
|tshock.npc.summonboss||✔|✔|✔|✔|✔|✔|✔|
|tshock.world.time.set||||✔|✔|✔|✔|✔|
|tshock.world.toggleexpert||||||✔|✔|✔|
|tshock.world.toggleparty||||||✔|✔|✔|
|tshock.tp.self|||||✔|✔|✔|✔|
|tshock.tp.allothers|||||✔|✔|✔|✔|
|tshock.tp.block|||||✔|✔|✔|✔|
|tshock.tp.npc|||||✔|✔|✔|✔|
|tshock.tp.others|||||✔|✔|✔|✔|
|tshock.tp.override|||||||✔|✔|
|tshock.tp.pos|||||✔|✔|✔|✔|
|tshock.tp.silent|||||✔|✔|✔|✔|
|tshock.cfg.updateplugins||||||✔|✔|✔|
|tshock.ssc.upload||||||✔|✔|✔|
|tshock.ssc.upload.others||||||✔|✔|✔|
|tshock.item.usebanned||||||✔|✔|✔|
|tshock.superadmin.user||||||||✔|
|tshock.admin.userinfo|||||✔|✔|✔|✔|
|tshock.world.time.usesundial||||✔|✔|✔|✔|✔|
|tshock.warp||✔|✔|✔|✔|✔|✔|✔|
|tshock.whisper||✔|✔|✔|✔|✔|✔|✔|
|tshock.cfg.whitelist|||||✔|✔|✔|✔|
|tshock.world.wind||||||✔|✔|✔|
|tshock.world.info||||||✔|✔|✔|
|tshock.world.save||||||✔|✔|✔|
|tshock.world.settleliquids||||||✔|✔|✔|
|tshock.world.setspawn||||||✔|✔|✔|
|tshock.tp.wormhole||✔|✔|✔|✔|✔|✔|✔|
|tshock.world.setxmas||||||✔|✔|✔|

**Comment by hakusaro** [comment]
The google doc has been updated with the new permission set proposal (all permission changes from the prior google doc sheet have been implemented).
