### ISSUE TITLE
mono TerrariaServer.exe -dump doesn't dump things

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1521]
On some latest version of general-devel, ```mono TerrariaServer.exe -dump``` just runs the server, doesn't dump anything, and doesn't exit. No errors in console, nor in any log files. Also, Utils.Dump() is never called because it should error out and die because not all of the dump functions were updated for the newest version of Terraria.

![screen shot 2017-12-03 at 16 00 12](https://user-images.githubusercontent.com/532647/33530906-32c3c8e6-d843-11e7-86f2-c4f5a8997fab.png)

**Comment by QuiCM** [comment]
I've done some investigation. It appears to be because somehow an empty parameter is getting added to the cmdline (i.e., the commandline being passed ends up being `[ "", "-flag", "-flag", "-etc" ]`. The parser is dumb and can't deal with the empty string. I'll try to fix it

**Comment by QuiCM** [comment]
Will be resolved by #1532
