### ISSUE TITLE
Update Readme with better docs

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1531]
I’ve come to the determination that our documentation sucks for developers. In particular:

* Building TShock from scratch is non-trivial, at least on macOS, maybe on Windows.
* Basic system architecture (what files do what and which things operate where) is non-existent.
* The relationship between TShock, Terraria Server API, and OTAPI is not clear.
* What TShock provides as an API to other plugins and what it expects other plugins to reimplement is non-clear.

In addition, I think it’s worth having a quick start guide for how to at least get up and running with TShock in a nutshell. This doesn’t have to be in depth, but it should at least cover starting the server, authenticating, and creating a couple accounts.

RIght now, this is on my todo list for implementation later today.

**Comment by QuiCM** [comment]
I feel like we should probably blow away much of the current readme documentation because it's all quite old

**Comment by hakusaro** [comment]
Ya, all on my list c:
