### ISSUE TITLE
Some REST endpoints should be used with POST instead of GET

### ISSUE THREAD

**Issue by Ryozuki** [Pryaxis/TShock#1543]
## TShock version
4.3.24.0

The endpoints that in my opinion should be using `POST` instead of `GET`:
- /bans/create
- /v2/server/broadcast
- /v2/server/off
- /v3/server/rawcmd
- /v3/server/reload
- /v3/server/restart
- /v2/users/create
- /v2/users/destroy
- /v2/users/update

**Comment by QuiCM** [comment]
Closing because we'll track this in #1546
