### ISSUE TITLE
Hardcore kick on join is buggy

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1548]
From Mist @ https://github.com/Pryaxis/TShock/issues/1458#issuecomment-350627613:

> Though it is unrelated, I'd like to point out that the kick mechanism on hardcore only is buggy: player name was not displayed in console; the kick message was not shown in game. (I tested with a English character name 'test')

**Comment by mistzzt** [comment]
Adding a delay works (but looks stupid).
More discussions needed.

For reference:
```csharp
args.Player.Difficulty = difficulty;
args.TPlayer.name = name;
args.Player.ReceivedInfo = true;

if (TShock.Config.HardcoreOnly && difficulty < 2)
{
	Task.Delay(50).ContinueWith(t =>
	{
		TShock.Utils.ForceKick(args.Player, "Server is set to hardcore characters only!", true);
	});
	return true;
}
```

**Comment by QuiCM** [comment]
Wondering if this is still an issue after #1620.
Labeling as follow-up

**Comment by DankRank** [comment]
This is about kick on join, whereas #1620 is about kick on death. They are not related.

**Comment by QuiCM** [comment]
The kick method was adjusted in https://github.com/Pryaxis/TShock/commit/1ea04ffd4f568e0ba708599ea9ea3007622a441e
Is anyone aware if this is still an issue?
