### ISSUE TITLE
Handled events should take a reason

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1570]
As discussed with @QuiCM in Discord, we should make it so that you can provide a reason with each event handle. E.g.,`args.Handle("Block the player from evading range checks for tile edit event.");`

This would enable a user to eventually turn on a tracing system to find where hooks go wrong and explain why a player has been disabled. Further, it would help us debug hooks easier.

Could potentially be an Orion thing too.

**Comment by QuiCM** [comment]
This will be part of #1575
