### ISSUE TITLE
Normal projectiles will be removed repeatedly in build 2102

### ISSUE THREAD

**Issue by mistzzt** [Pryaxis/TShock#1584]
*This issue would never happen in stable version (4.3.25).*

There's a check on `NewProjectile` in [Bouncer](https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/Bouncer.cs#L981):
```csharp
// from `GetDataHandlers`
// it seems that `SearchProjectile` could never find the proj id here
var index = TShock.Utils.SearchProjectile(ident, owner);

			if (index > Main.maxProjectiles || index < 0)
			{
				args.Player.RemoveProjectile(ident, owner);
				args.Handled = true;
				return;
			}
```
```csharp
		/// <summary>
		/// Searches for a projectile by identity and owner
		/// </summary>
		/// <param name="identity">identity</param>
		/// <param name="owner">owner</param>
		/// <returns>projectile ID or -1 if not found</returns>
		public int SearchProjectile(short identity, int owner)
		{
			for (int i = 0; i < Main.maxProjectiles; i++)
			{
				if (Main.projectile[i].identity == identity && Main.projectile[i].owner == owner)
					return i;
			}
			return -1;
		}
```
In the master branch, the return value of `Utils.SearchProjectile` if projectile not found is `1000`; it was changed to `-1`. 
Since `Main.maxProjectiles` is 1000, statements in *if-clause* is never executed in stable build. 
However, as it was changed to -1, every new projectile will be removed.

**Comment by hakusaro** [comment]
Which projectiles get removed?

**Comment by hakusaro** [comment]
So I'm thinking more about this. If there are normal game projectiles being caught by this we need to fix it with exemptions on those projectiles. My assumption is that the game is generating projectiles with no owner or something, which makes that check return `-1`.

However, in the stable version of TShock this bounds check never worked at all. If there haven't been reports of an uptick in cheating, I would suggest as a side measure removal of the entire if statement:

```csharp
if (index > Main.maxProjectiles || index < 0)
			{
				args.Player.RemoveProjectile(ident, owner);
				args.Handled = true;
				return;
			}
```

**Comment by hakusaro** [comment]
Wait! Bouncer doesn't have `var index = TShock.Utils.SearchProjectile(ident, owner);`??
