### ISSUE TITLE
TileKill permission check is Easily Bypassed

### ISSUE THREAD

**Issue by Joshwoo70** [Pryaxis/TShock#1590]
* TShock version: TShock v4.3.25 for Terraria 1.3.5.3
* TShock build number (if known): N/A

#### Reproduction steps (if applicable)?

1. Install [TerrariaPatcher](https://forums.terraria.org/index.php?threads/1-3-terrariapatcher-plugins-and-more-works-with-tmodloader-now.24615/)
2. Patch Terraria
3. Enter into tshock server with axe and pick in hand
4. Level the terrain in a few hours.

#### Video (Thanks to hakusaro for uploading.)
[Trees? What Trees?](https://streamable.com/6lgqd)

**Comment by hakusaro** [comment]
This absolutely needs to be fixed as soon as possible.

**Comment by Joshwoo70** [comment]
you may get blocked after a few swings but it's more of nuisance then an issue.

**Comment by hakusaro** [comment]
After discussion with @ivanbiljan, this is going to be left to a plugin to implement a fix for or mitigation against. My current suggestion is to set tile kill thresholds on a per axe/per weapon basis, and combine that with range checks to mitigate these types of tile kills. A tile kill threshold per set of tools or a tile kill threshold that's more tailored to how a user interacts with the game is a better way to go than relying on TShock to continually keep its thresholds up to date.
