### ISSUE TITLE
NoClip Protection is easily Bypassed

### ISSUE THREAD

**Issue by Joshwoo70** [Pryaxis/TShock#1592]
* TShock version: TShock v4.3.25 for Terraria 1.3.5.3
* TShock build number (if known): N/A

#### Reproduction steps (if applicable)?

1. Install [Terrariapatcher](https://forums.terraria.org/index.php?threads/1-3-terrariapatcher-plugins-and-more-works-with-tmodloader-now.24615/)
2. Download the [Noclip Script](https://github.com/septor/TerrariaPatcherPlugins)
2.1 Drag the .cs file from master into the plugins folder
2.5. Patch Terraria
3. Enter into tshock server and press "Q"
4. You shall not see me!

#### Video
[You shall not see me!](https://streamable.com/bcvdp)

**Comment by hakusaro** [comment]
Fixed in #1589
