### ISSUE TITLE
Can not connect to update server?

### ISSUE THREAD

**Issue by slzn** [Pryaxis/TShock#1596]
* TShock version: 4.3.25

#### Reproduction steps (if applicable)?

Can not connect to update server
http://update.tshock.co/latest/

#### Any stack traces or error messages (if known)?

UpdateManager warning: Update server did not respond with an OK. Server message: [error BadGateway] Bad Gateway
Retrying in 5 minutes.
UpdateManager warning: Update server did not respond with an OK. Server message: [error BadGateway] Bad Gateway
Retrying in 5 minutes.
UpdateManager warning: Update server did not respond with an OK. Server message: [error BadGateway] Bad Gateway
Retrying in 5 minutes.

**Comment by hakusaro** [comment]
Thanks for that report. I accidentally took it down and forgot to reboot it. Should be good now.
