### ISSUE TITLE
Spawn crystal storm with mythical modifier gives random modifier instead

### ISSUE THREAD

**Issue by LyraelRayne** [Pryaxis/TShock#1597]
!!!!!! PLEASE FILL IN THE TEMPLATE BELOW THANK YOU VERY MUCH !!!!!!

If you don't need help, delete this template and just post an issue (feature requests and discussions and the like).

* TShock version: TShock: 4.3.25.0 (Mintaka).
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. Login to server
2. /i crystal storm 1 mythical OR /i crystal storm 1 83
3. Get wrong modifier
4. Cry

#### Any stack traces or error messages (if known)?
No. The chat message says the right modifier but the item has the wrong one.

#### Any screenshots?
I don't think it's necessary for this issue.

**Comment by LyraelRayne** [comment]
Ignore this. I'm an idiot. Apparently it's not possible to get mythical in the latest versions. I was reading old posts recommending it.

**Comment by hakusaro** [comment]
@LyraelRayne thanks!
