### ISSUE TITLE
Incomplete loading of maps

### ISSUE THREAD

**Issue by wagayaluda** [Pryaxis/TShock#1604]
TShock version:4.3.25.0
screenshot：http://www.terrariaserver.cn/wp-content/uploads/2018/02/%E6%8D%95%E8%8E%B7.png

Just like this,there is a missing part on the right.

**Comment by QuiCM** [comment]
I believe we discovered that this is actually a Terraria issue that may be fixed in the next Terraria update.

**Comment by mistzzt** [comment]
Duplicated as in #1378

**Comment by QuiCM** [comment]
Closing - tracked in #1378
