### ISSUE TITLE
Packet 96 (Player Teleport Through Portal)

### ISSUE THREAD

**Issue by NotHunter101** [Pryaxis/TShock#1605]
Packet number 96 has no verification of who its coming from. Allows for teleportation of other users. Fix pl0x. Also unbean me from the forum please.

**Comment by QuiCM** [comment]
Thank you for your report.
Our policy on banning can be found here: https://github.com/Pryaxis/handbook/blob/master/policy/banning.md

**Comment by NotHunter101** [comment]
Oh, okay. I figured this was the case, I just thought that this is a really dangerous issue and should be reported.

**Comment by hakusaro** [comment]
@NotHunter101 if you want to be unbanned, you can make a one time investment of $100 USD equivalent in Ether to 0x00DB6Dd4C858D11Be6e56B15cb9833B876bDeC02 or send a 1,000 word original persuasive essay on why spamming Discord servers and then repeatedly ban-evading is not okay to shank@shanked.me.

There was literally **no problem** with you being in the community until you decided to self bot spam us. Given that, I don't particularly mind reversing a ban if you can demonstrate being apologetic and explain why you did it, and why you aren't going to do it again.

**Comment by NotHunter101** [comment]
100 dollars, really? Well, I guess i'm writing an essay, even though I really wouldn't know what to write besides me repeatedly saying

"I'm sorry, I was stupid, and I'm not going to spam you or ban evade anymore, because I understand that it can make people sad."

Over and over, modifying it, saying it again, and then just repeating that for 1000 words. I am apologetic, I also understand that people on the internet are human beings, and I also understand that you had all the right to ban me but now i'm getting the vibe that you are just trying to get me to pay you, or get me to write a long essay for no reason, just so you can be like "read the first post, skrub" and then next thing you know, all my efforts are put to waste for no reason. I know that this probably isn't the case, but I don't exactly feel all that comfortable with you conditions to unban someone. This is how I feel for all this kind of stuff, I feel sorry, I wan't to once again become some part of the community, but me writing a massive essay won't actually change the way I feel. And in the end, it's the same the other way around, too. I could not care, I could still hate you all, I could just fake out a whole entire 5000 words about how sorry I am just to come back and ping spam again, and that's why I feel this is counter-productive. I'm really trying to make some sort of redemption here. See, even here, after I've been banned, Instead of using this security oversight to make people angry, I am genuinely trying to have it fixed. I don't know what more I could possibly say, and I really, really, wish that this could be accepted as a genuine apology. I didn't wan't this to happen, and I understand if this isn't enough to be unbanned, but I really, really just want to be able to contribute to the forums and be able to contribute even in the smallest ways to server owners, I want to be able to upload plugins without ban evading and making alts, and I want to be able to re-join. I know this is only around 300 words, but I don't know what else to say without repeating myself. I hope this could be considered genuine.

**Comment by bartico6** [comment]
I think he was being ironic about that essay thing (and the unban ethereum payment) because that'd put him and the community he runs in a bad light...  
... with that said, being apologetic can be easily faked, and what he was trying to get through is that saying sorry isn't enough. It's also worth noting, that your behavior cycle starts to replicate that of someone known to tShock too closely (aka be a cunt, get banned, say sorry, get unbanned, be a cunt again, get banned again).  
That's just my two cents.

**Comment by hakusaro** [comment]
@NotHunter101 I regularly write 1,000+ word journal entries that take about 20 minutes to complete. The point is to be _self reflective_, to explain what made you feel that way, why you responded in the way you did, why you're apologetic, what you hope to achieve, and why you aren't just going to be a massive pain in the ass for us to deal with if we do in fact unban you. $100 in ETH is a fair price for the amount of time and effort we've put in debating and dealing with this situation -- divided amongst all admins it's pretty fair.

_Either way, you only get one submission and your submission **must be by email to shank@shanked.me**_ and there are no exceptions to the "appeal via email" policy. If you find that you don't have enough words to reflect, I suggest that you look deeper within yourself. I can easily write that content about a single day of my life -- this has been playing out for at least that long. As an alternative, I've been really interested in the computer industry lately. You can substitute any number of words, as you see fit, with a discussion of the #MeToo movement or Susan Fowler.

And I am sincere. I just don't want to waste the admins' time from having to clean up if this happens again. I don't want to be proven wrong by yet again forgiving someone only for them to throw shit in my face. Again.

Warmly,
Lucas

**Comment by NotHunter101** [comment]
Understandable.

**Comment by NotHunter101** [comment]
I guess I'll actually be writing this now, seeming as I do want to be unbanned.

**Comment by hakusaro** [comment]
@NotHunter101 update on this?
