### ISSUE TITLE
Add Visual Studio junk to Gitignore

### ISSUE THREAD

**Issue by QuiCM** [Pryaxis/TShock#1607]
Visual Studio 2017 adds a bunch of garbage to projects under a hidden `.vs/*` directory.
We should probably gitignore this directory for everyone's sanity and so I don't have to tell people to not commit those files

**Comment by hakusaro** [comment]
* ```db.lock```
* ```storage.ide```

**Comment by Ijwu** [comment]
@hakusaro Are you suggesting to add those files to the ignore or are you listing the contents of the .vs/* directory?

**Comment by hakusaro** [comment]
@Ijwu the former

**Comment by hakusaro** [comment]
or maybe they're in that dir, idk

**Comment by Ijwu** [comment]
They are, I checked just now. :)

**Comment by QuiCM** [comment]
![linqpad_2018-03-07_09-09-58](https://user-images.githubusercontent.com/2648373/37062829-7d3ca3dc-21e7-11e8-9e5e-f0312611e468.png)

Full contents of `.vs` and subdirectories
