### ISSUE TITLE
Missing Chunk of my World

### ISSUE THREAD

**Issue by MisterNoGo** [Pryaxis/TShock#1610]
TShock version:4.3.25.0

I had this issue in the past, and it never got resolved, I just stopped using tshock for a while.  There is new information about the issue as I tried to use the new version of tshock and new things happened.

The original issue:  A huge chunk of my map is gone.  It's still kind of there in that I can utilize the end of a teleporter path to get get back to the teleporter at my base, but there is NOTHING there when I arrive.  NPC's spawn in the blank space that the game recognizes as their home, then fall all the way to where the glitched area ends and respawn, only to fall in a loop.  Part of the building was built in Tedit, which was investigated as the cause.  I manually replaced almost everything placed by tedit, and even went into the map in tedit looking for anything accidentally left that would corrupt such a huge portion of the map.  I found nothing.  The center of the area missing is in my teleporter hall.

The new:  As I deleted tshock, and recently reinstalled, my logins were of course, all gone.  Entering into the glitched area not being a superadmin, I would randomly teleport back to a location I was only moments before, only now a small square 15x15 blocks large returned from the void the rest of the area is in, centered on where the player spawned.  Screen shots included, water behaves very strangely here.   I can get large chunks of the map to reappear simply by flying around and getting rubber banded back to where I was, now with my map returned.  Utilizing the rod of teleportation while hovering in an open area causes the tshock to let me know I don't have permission to teleport, but also returns the map, centered on me, in the same 15x15 patch.  None of the map returns as superadmin, which is probably why I didn't realize it was happening before.

Exiting and re-entering does not save any of the loaded space, and the same area is completely blank again.

Any items dropped will fall freely, until reaching a certain point, then respawn at the drop location and loop.  They can be picked up during free-fall.  Edit:  Any drops picked up during free-fall that are picked up far enough away from the spawn point will be added to inventory, but still respawn, allowing you to pick up the item until your inventory has filled, at which point the item will stop spawning until you have free inventory space, at which point, it will start spawning again.

Screenshots
Here's the map chunk, returned from the void.
![image](https://user-images.githubusercontent.com/18652792/37575020-36955236-2afb-11e8-97a0-4573502aa887.png)

More map chunks, but with the water glitching out in the returned portion.
![image](https://user-images.githubusercontent.com/18652792/37575210-4f3da4f4-2afc-11e8-90c8-72e51a3d3a6e.png)

**Comment by QuiCM** [comment]
Thanks.
This is tracked in #1610 and requires Re-Logic to fix a bug in their code

**Comment by QuiCM** [comment]
Whoops. #1378

**Comment by MisterNoGo** [comment]
You know it's a bug now?  That's great.  Last time, it didn't look like a solution was going to be found.

**Comment by hakusaro** [comment]
It's a bug, but it's a Re-Logic bug. Not our bug. 1.3.6 should probably fix
it.
