### ISSUE TITLE
Upnp seems to be in an unusable state

### ISSUE THREAD

**Issue by daiaji** [Pryaxis/TShock#1611]
I run TShock on Linux and Windows
Upnp does not seem to work for me😂

**Comment by Ijwu** [comment]
UPnP is not enabled in TShock.

**Comment by daiaji** [comment]
@Ijwu 
The UPNP plugin provided by the forum seems to be too old.
Can only go to the firewall to open the port?

**Comment by Ijwu** [comment]
You need to open the port in your router config to allow incoming connections on that port. I won't provide instructions or support on how to do that within this GitHub issue.

Please attempt to find the instructions on how to port forward for your router make and model. If you have searched and still cannot get it to work, then join the TShock Discord and DM me for further support.
