### ISSUE TITLE
Upstart script?

### ISSUE THREAD

**Issue by trentyarwood** [Pryaxis/TShock#1612]
!!!!!! PLEASE FILL IN THE TEMPLATE BELOW THANK YOU VERY MUCH !!!!!!

* TShock version: 4.3.25.0

Hi,
I've found lots of guides online about getting TShock up and running, and I think I can do it pretty reliably manually, but I'd like to have it running as a service when my server restarts.

I've seen the rc.d script using tmux, but has anyone been able to create an upstart script to get it working?

Thanks,

**Comment by ivanbiljan** [comment]
GitHub issues should not be used as a support platform. Please create a thread at tshock.co instead.

**Comment by hakusaro** [comment]
You should also hop by discord. Also, isn't upstart discontinued?
