### ISSUE TITLE
if tshock suport net core? 

### ISSUE THREAD

**Issue by 1424667164** [Pryaxis/TShock#1627]
if tshock suport net core? 

net core is cross platform for run and dev,
we no need mono any more.

-_-

**Comment by QuiCM** [comment]
TShock does not compile for dotnet core at this point in time

**Comment by hakusaro** [comment]
No.

**Comment by 1424667164** [comment]
is we can get it in future?
I mean, net core is cross platform and friendly for developer.
Thank you guys for all things here.

**Comment by DankRank** [comment]
Unlikely. TShock depends of vanilla Terraria server which uses .NET Framework.
