### ISSUE TITLE
Building From Source Does Not Work On CentOS 7

### ISSUE THREAD

**Issue by Ratstail91** [Pryaxis/TShock#1628]
!!!!!! PLEASE FILL IN THE TEMPLATE BELOW THANK YOU VERY MUCH !!!!!!

If you don't need help, delete this template and just post an issue (feature requests and discussions and the like).

* TShock version: v4.3.25
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. I recursively cloned the source repo
2. I switched to the tag v4.3.25
3. I switched the subdirectory /TerrariaServerAPI to the same commit that was used in v4.3.25 
4. I followed the instructions to build from source
5. I kept getting errors, and building simply failed

#### Any stack traces or error messages (if known)?

Too many to list

#### Any screenshots?

N/a

If possible, can you create a release for CentOS 7?

**Comment by Ratstail91** [comment]
The restore didn't work.

**Comment by hakusaro** [comment]
> Too many to list

Unfortunately, if you don’t list the errors, we really can’t help diagnose build problems. All official releases of TShock are compiled and packed on a CentOS 7 machine, so it certainly works on that platform specifically.

You need to give us something to work with or we can’t really help you. I’d love to point you in the right direction, but we need more context.
