### ISSUE TITLE
IP in ServerApi.Hooks.ServerConnect

### ISSUE THREAD

**Issue by ASgoPew** [Pryaxis/TShock#1630]
Why can't I get IP in ConnectEventArgs? It's impossible since TSPlayer isn't initialized at this point and Netplay.Clients[i].Socket.GetRemoteAddress() is private...

**Comment by bartico6** [comment]
This produces no compile errors; Are you sure? [Image](https://i.quake.tf/1535098561-1197239915.png)

**Comment by ASgoPew** [comment]
I got the reason why I didn't have an access to this method, but still I think IP in ConnectEventArgs is reasonable.

**Comment by ivanbiljan** [comment]
As OTAPI includes a modification that makes all types public and TSAPI already provides all the information you need in order to access a socket's address I don't see a valid reason for adding another argument.

**Comment by QuiCM** [comment]
If this is PRed and passes code review it would probably be merged. Unlikely that we will add this ourselves though.
