### ISSUE TITLE
Pirate Boss not working properly on Tshock

### ISSUE THREAD

**Issue by Luysita** [Pryaxis/TShock#1646]
* TShock version: tshock_4.3.25
* TShock build number (if known): TerrariaAPI Version: 2.1.0.0 (Protocol v1.3.5.3 (194), OTAPI 1.3.5.3)

Details: Pirate Invasion boss sometimes appears invisible when it's summoned. Cannot hit it at all.

 It still fires cannons and mobs though.

Screenshots:
![terraria 2018-10-28 19-07-58-99](https://user-images.githubusercontent.com/4097013/47621493-b6e0eb80-daf0-11e8-9eac-997686faad1d.png)

![terraria 2018-10-28 19-06-57-78](https://user-images.githubusercontent.com/4097013/47621502-cfe99c80-daf0-11e8-87c1-5430b1661036.png)

**Comment by AxeelAnder** [comment]
It's a bug of Terraria rather than TShock.
It happens when there are solid tiles on the top of where it spawn. Just move to other place and it'll be visible.

**Comment by Luysita** [comment]
> 
> 
> It's a bug of Terraria rather than TShock.
> It happens when there are solid tiles on the top of where it spawn. Just move to other place and it'll be visible.

Oh, because I tried in singleplayer and it worked, weird.

**Comment by AxeelAnder** [comment]
> 
> 
> > It's a bug of Terraria rather than TShock.
> > It happens when there are solid tiles on the top of where it spawn. Just move to other place and it'll be visible.
> 
> Oh, because I tried in singleplayer and it worked, weird.

It happens only in multiplayer game. 
Terraria only update an npc when it's velocity bigger than a value. When the ship get stuck in rising process, it's velocity is 0. And for some reasons I don't know, clients judge its cannons are died, so it died in clients. Without syncing(updating), players can never see it.

**Comment by Luysita** [comment]
Ah alright, thanks anyway.

**Comment by hakusaro** [comment]
Can we just work around this in TShock?

**Comment by Luysita** [comment]
> Can we just work around this in TShock?

Wonder the same.

**Comment by bartico6** [comment]
`        if (Main.npcStreamSpeed > 0 && !this.townNPC && (double) Math.Abs((float) this.velocity.X) + (double) Math.Abs((float) this.velocity.Y) > 1.0) <<<<<<<<<
        {
[...]
        }`
First thought is that you can try patching the NPC class to optionally skip the velocity check based on a configuration value, or you can emulate this behavior every tick by forcing an update if the NPC's velocity vector axis sum is <= 1.0.

**Comment by AxeelAnder** [comment]
I think the key is why cannons disappear.
Probably the network delay. First frame the ship update and generate 4 cannons, then second frame cannons update. If there's delay that is enough for client to update, client would be unable to find the cannons, so the ship blow up
Just my conjecture.

**Comment by sr229** [comment]
Sounds like a spawn state error IMHO, this can be rectified in TShock's side by checking if the client's view has the mob NPC entity is existent between clients. If it does then draw the entity with the sprite for all connected clients then despawn when there's conditions met for it to be de-spawned, then update to clients about it

**Comment by bartico6** [comment]
This has now been fixed in 1.4.1, apparently.
> Fixed an issue where Flying Dutchman would desync and behave oddly or die spontaneously
