### ISSUE TITLE
Consider TShock to be built with .NET Core

### ISSUE THREAD

**Issue by sr229** [Pryaxis/TShock#1649]
There has been considerable resource and effort for .NET Core to be used as an alternative to .NET Framework. So far, projects like [ppy/osu](https://github.com/ppy/osu) has been successful in using .NET Core as a alternative to .NET Framework.

Advantages of .NET Core might be:

- Independence for the need of having .NET runtime present, known as Self-Contained apps.
- Allows programs to operate in lower memory environments.

This is just a proposal since .NET Framework apps are known to be able to migrate to .NET Core easily given their NuGet packages supports it as well.

**Comment by DankRank** [comment]
TShock depends on Terraria server (which is .NET Framework).  Terraria itself depends on XNA framework, which is also .NET Framework-only.
See #1627

**Comment by hakusaro** [comment]
Yeah, sorry for the stupid delay on replying here. @DankRank is exactly correct.

**Comment by hakusaro** [comment]
@sr229 also that's a really cute avatar. Also, you look talented: I would love to see you hanging around TShock more if it at all interests you.

**Comment by bartico6** [comment]
Many .NET Framework packages run on .NET Core out of the box, so as long as the libraries are present, .NET Core should be able to load them.  

Case in point: 
BCrypt for .NET Framework 4.6.1 runs out of the box with no changes required in ASP.NET Core (which runs .NET Core 2.1 internally). I purposefully checked out a version that isn't even compiled to run on .NET Core, and it still works. The only sign of incompatibility is a warning in VS, the functionality is used throughout the project with no issues whatsoever.
![Image](https://i.quake.tf/1541185912-7191562410.png)

I don't know how XNA would handle running in .NET Core's runtime, but unless someone already proved it's impossible, it's worth a try.

**Comment by tylerjwatson** [comment]
There would be some work involved with OTAPI to present a binary that would work in .net standard but it would require some work. 

Be aware though that TShock is built on OTAPI which is a binary patch to the official server. The server was never compiled for any architecture or platform that isn't .net 4.5 on x86. 

Dead windows interop would have to be removed, and all dead references to XNA replaced with shims or removed entirely. I don't see it as an impossibility just yet.

**Comment by sr229** [comment]
I think this merits a reopen and open for dev since the possibility of this is already proven.
