### ISSUE TITLE
Packet 24 (Strike NPC with held item)

### ISSUE THREAD

**Issue by NotHunter101** [Pryaxis/TShock#1651]
You should definitely add a Bouncer for packet 24 and check the senders permissions ;)

https://www.youtube.com/watch?v=nJzGor_mCzw

I'm already bored with this, so here.

**Comment by NotHunter101** [comment]
Is this not important? Should I close this? Should I patch it myself?

**Comment by Ijwu** [comment]
Active development is spotty as we live our lives. I make no promises but I may pick this in my free time. The preferred scenario is that you patch it yourself and we will happily work with you to guide you to that solution.

**Comment by NotHunter101** [comment]
That's fair, i'll make a pull request.
