### ISSUE TITLE
SSC Documentation is Wrong

### ISSUE THREAD

**Issue by mtcdood** [Pryaxis/TShock#1659]
* TShock version: 4.3.25.0

#### Reproduction steps (if applicable)?

1. `group add superadmin-ssc`
2. `group parent superadmin-ssc superadmin`
3. `group addperm superadmin-ssc !tshock.ignore.ssc`
4. `user group myuser superadmin-ssc`
5. Log in with myuser
6. superadmin-ssc has no permissions
7. myuser has no permissions

Making superadmin a parent accomplishes nothing because superadmin doesn't have permissions; it just ignores permission checks. The documentation [here](https://tshock.readme.io/docs/server-side-character-config) should not suggest this.

**Comment by QuiCM** [comment]
Our documentation has a feature that allows you to suggest edits.
I'm confused as to why you opened an issue here instead of doing so.

I have corrected the issue
