### ISSUE TITLE
Cannot Remove Permissions From *

### ISSUE THREAD

**Issue by mtcdood** [Pryaxis/TShock#1660]
* TShock version: 4.3.25.0

#### Reproduction steps (if applicable)?

1. `group add superuser-ssc`
2. `group addperm superuser-ssc *`
3. `group delperm superuser-ssc tshock.ignore.ssc`
4. superuser-ssc has permission `, *`

This appears to be an oversight or a bug. Administrators should be able to negate permissions from `*`

**Comment by bartico6** [comment]
You negate permissions by adding !permission.
`group addperm superuser-ssc !tshock.ignore.ssc`.
delperm removes an existing entry. You're looking to add a negated entry.

**Comment by mtcdood** [comment]
That doesn't work either.

* `group add superuser-ssc`
* `group addperm superuser-ssc *`
* `group delperm superuser-ssc tshock.ignore.ssc`
* superuser-ssc has permission `, *`

**Comment by QuiCM** [comment]
Hi,
This is a defect with the way `listperm` works.
The permission has been applied, however listperm removes negated permissions from the displayed list (acting under the logic that `someperm, !someperm` -> nothing, so negated permissions should not be displayed).
The `*` permission was added after listperm was written and they don't interact well.
