### ISSUE TITLE
Item frame does not work properly with TShock v4.3.26

### ISSUE THREAD

**Issue by NekoDisc** [Pryaxis/TShock#1680]
TShock version: v4.3.26

Item frame is invisible after installation.
That becomes visible after re-login, but any items can't decorate on that.

**Comment by zippywin** [comment]
TShock version: v4.3.26

First item frame placed will not be visible.
However, placing 2 item frames at the same spot seems to make it function as normal.

**Comment by kubedzero** [comment]
Also having issues with the item frame seemingly "eating" items. I had a stack of light discs and accidentally replaced a banner on an item frame with a light disc, and was only able to recover 1 of the 5 light discs. Very strange

**Comment by QuiCM** [comment]
Going to merge this one with #1693
