### ISSUE TITLE
Build Action cannot complete

### ISSUE THREAD

**Issue by QuiCM** [Pryaxis/TShock#1688]
Seems like something changed in GitHub Actions and now the Build action is failing:

```
Run actions/checkout@master
  > Run actions/checkout@master
  ##[error]The input 'submodules' is not supported in actions/checkout@v2

##[error]Node run failed with exit code 1
```

**Comment by QuiCM** [comment]
https://github.com/actions/checkout#Checkout-submodules :
An example of checking out submodules in actions/checkout v2 (actions/checkout master)
```
- uses: actions/checkout@v2
- name: Checkout submodules
  shell: bash
  run: |
    auth_header="$(git config --local --get http.https://github.com/.extraheader)"
    git submodule sync --recursive
    git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
```

**Comment by hakusaro** [comment]
I tweaked the build script to just use v1 (that's what I did on my private repos) in https://github.com/Pryaxis/TShock/commit/8bc31eed0a8bc38bbfd1fd9bd862353e462e3543. Now the `SetupMSBuild` part of the workflow doesn't work, however.
