### ISSUE TITLE
Item Frame and Target Dummy broken

### ISSUE THREAD

**Issue by moisterrific** [Pryaxis/TShock#1693]
## TShock Version
4.3.26 (Mintaka), API 2.1

## Issue Description
- **Item Frame** and **Target Dummy** disappears to the client when placed, but are still visible to other players online
- **Target Dummy** cannot be interacted with by other players at all

(tested with stock TShock default group, it is worth mentioning this issue does not occur for superadmin group, nor any group with the `ignore.sendtilesquare` permission)

## Steps to Reproduce
1. craft Item Frame and Target Dummy
2. place them in a non-protected area (while in a group that does not have ignore.sendtilesquare perm)

## Supporting Evidence
https://cdn.discordapp.com/attachments/479657350043664386/689561252896440355/18_05_49_42_784.mp4
https://cdn.discordapp.com/attachments/479657350043664386/689561999025242151/18_05_52_39_150.mp4

**Comment by QuiCM** [comment]
Blocked by 1.4 existing >:(

**Comment by hakusaro** [comment]
This should be fixed in the next pre-release.
