### ISSUE TITLE
Why do I get this error message when I try to start up a TSHOCK server?

### ISSUE THREAD

**Issue by shosho12344** [Pryaxis/TShock#1719]
* TShock version: 4.3.5

```
[Server API] Error Server crashed due to an unhandled exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.File.InternalGetLastWriteTimeUtc(String path, Boolean checkHost)
   at System.IO.File.GetLastWriteTime(String path)
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
```

**Comment by moisterrific** [comment]
Because you are using an outdated version of TShock. The latest release is 4.3.26.

**Comment by shosho12344** [comment]
> Because you are using an outdated version of TShock. The latest release is 4.3.26.

I know but, people have used this without getting this error. I just want to fix this.

**Comment by tylerjwatson** [comment]
@shosho12344 Did you find a solution? if so please share it for the benefit of the community.  Other people that come up against this issue will come here, and nobody benefits from a simple closure.
