### ISSUE TITLE
1.4.0.2 support

### ISSUE THREAD

**Issue by skelterjohn** [Pryaxis/TShock#1747]
I imagine this is on your radar, but having an issue to watch is a way I can get notified that it's been achieved.

**Comment by QuiCM** [comment]
I assume you meant 1.4 ;)

**Comment by skelterjohn** [comment]
Nice re-typo!

**Comment by hakusaro** [comment]
Pre-release 1 now available: https://github.com/Pryaxis/TShock/releases/tag/v4.4.0-pre1. I'm going to close this because if you watch the repo on GitHub in the top right, you can turn on "releases only."
