### ISSUE TITLE
Using -world command line causes server crash

### ISSUE THREAD

**Issue by ghost** [Pryaxis/TShock#1761]

**Comment by mrshroomy** [comment]
It got fixed by not using a -world tag for starting the server

**Comment by QuiCM** [comment]
Interesting. Thanks, I'll update the issue title to match because that sounds like it may be something we need to fix

**Comment by agentsparrow** [comment]
I had this same problem when launching with this command line:
./TerrariaServer.exe -port XXXX -worldpath "/usr/games/tshock/Worlds/" -world "XXXXXX.wld"

Got it to work fine when I changed it to:
./TerrariaServer.exe -port XXXX -world "/usr/games/tshock/Worlds/XXXXXX.wld"

**Comment by hakusaro** [comment]
As of 7ad46abced17113ca4338598c73c172828e43355, this should be fixed by the removal of `-worldpath`. We really appreciate the time you've put into this -- it helped a lot. Thank you all!

**Comment by hakusaro** [comment]
@all-contributors add @mrshroomy for testing

**Comment by hakusaro** [comment]
@all-contributors add @agentsparrow for test
