### ISSUE TITLE
4.4.0 pre 1 ubuntu 16.04 error when starting

### ISSUE THREAD

**Issue by idunnoooooo** [Pryaxis/TShock#1762]
[Server API] Error Startup aborted due to an exception in the Server API initialization: System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.TypeLoadException: Could not load type 'Mono.Data.Sqlite.SqliteConnection' from assembly 'Mono.Data.Sqlite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'. at TerrariaApi.Server.PluginContainer.Initialize () [0x00006] in <dba7acc1d7d64878b6dd513ec7fd4459>:0 at TerrariaApi.Server.ServerApi.LoadPlugins () [0x002eb] in <dba7acc1d7d64878b6dd513ec7fd4459>:0 --- End of inner exception stack trace --- at TerrariaApi.Server.ServerApi.LoadPlugins () [0x00313] in <dba7acc1d7d64878b6dd513ec7fd4459>:0 at TerrariaApi.Server.ServerApi.Initialize (System.String[] commandLineArgs, Terraria.Main game) [0x0011a] in <dba7acc1d7d64878b6dd513ec7fd4459>:0 at TerrariaApi.Server.HookManager.InitialiseAPI () [0x0004e] in <dba7acc1d7d64878b6dd513ec7fd4459>:0

**Comment by QuiCM** [comment]
Hi, could you try again with pre 5 please?

**Comment by pluto00987** [comment]
FWIW, Pre3 and up have worked fine for me on Ubuntu 18.04. I didn't try any earlier ones.

**Comment by adamsalem** [comment]
> Hi, could you try again with pre 5 please?

Tested pre5 with 16.04 and confirmed working.

**Comment by QuiCM** [comment]
Thanks all. Will close this one off :)
