### ISSUE TITLE
[Feature Request] Add /mode command

### ISSUE THREAD

**Issue by QuiCM** [Pryaxis/TShock#1764]
Syntax suggestion: /mode <normal|expert|master|journey?>

This would replace the existing /expert command

**Comment by Kojirremer** [comment]
Would having Journey on that list have some unintended issues? Because supposedly only journey characters could enter journey worlds. Would changing, for instance, from expert to journey kick all players and then only allow journey ones?

**Comment by moisterrific** [comment]
yeah what would happen if you toggled journey mode in a non journey mode world while players are on? 🤔

**Comment by QuiCM** [comment]
Added in https://github.com/Pryaxis/TShock/commit/240b6b71b0825f59f49f03871be6dc0e662e59f6
