### ISSUE TITLE
Worldpath option is ignored

### ISSUE THREAD

**Issue by vmx-kbabenko** [Pryaxis/TShock#1767]
* TShock version:4.4.0_226_Pre1_Terraria1.4.0.2

#### Reproduction steps?

1. Start server with the following options:
` /tshock/TerrariaServer.exe -configpath /world -worldpath /world -logpath /world`
2. Observe, that no worlds from /world are available to start
3. Create a new world and find a newly created file under /root/.local/share/Terraria/Worlds/

#### Server log:

```
[05/18/20 14:40:35] [Server API] Verbose: TerrariaApi - Server v2.1.0.0 started.
[05/18/20 14:40:35] [Server API] Verbose: 	Command line: /tshock/TerrariaServer.exe -configpath /world -worldpath /world -logpath /world
[05/18/20 14:40:35] [Server API] Verbose: 	OS: Unix 5.4.13.1 (64bit: True)
[05/18/20 14:40:35] [Server API] Verbose: 	Mono: True
```

Server is launched in a docker container created from mono:6.8.0.96.

**Comment by SvenKirschbaum** [comment]
You have to copy the TShockAPI.dll file into the ServerPlugins folder.

From the [release notes](https://github.com/Pryaxis/TShock/releases/tag/v4.4.0-pre1):

> Important: You need to move TShockAPI.dll into the ServerPlugins folder. If you don't have one, run TerrariaServer.exe once, and then copy the file into the newly created folder. You know that you're running TShock as expected if you see the list of names in the startup sequence.

**Comment by vmx-kbabenko** [comment]
Indeed that was the problem. Thank you!
