### ISSUE TITLE
TShock 4.4.0 Pre 4, Doors disappear 

### ISSUE THREAD

**Issue by Kavex** [Pryaxis/TShock#1774]
[Worlds 5-18-2020-11-52pm.zip](https://github.com/Pryaxis/TShock/files/4646291/Worlds.5-18-2020-11-52pm.zip)

* TShock version: 4.4.0 Pre 1
* TShock build number (if known): b56f1fc https://github.com/Pryaxis/TShock/releases/tag/v4.4.0-pre1

#### Reproduction steps (if applicable)?

Happening to a user that is overseas so I'm assuming it's due to high latency but when opening or closing doors it will disappear and if there is a trap door next to it then it will duplicate that trap door. I haven't tested this on any other item to see if it duplicates it too. 

This doesn't happen to all door but only some of them too.

#### Any stack traces or error messages (if known)?

No error I can tell 

#### Any screenshots?

https://imgur.com/a/CjxSQGz

#### Any log messages from files that end in `.log` or `.txt`?

No error I can tell 

#### What plugins and what versions of those plugins are you running?

No Plugins

**Comment by moisterrific** [comment]
https://gfycat.com/showymiserableafricanhornbill

seeing this issue on my end too, it's not high latency, something to do with TShock detecting the smart door opening as cheat and attempting to revert the action

same problem happens for trap doors too I think, they like to vanish from existence when you click on them to open, not sure for tall gates

**Comment by breeece** [comment]
I can confirm, I am getting this as well.

**Comment by QuiCM** [comment]
Likely an issue with sent tile again. Cheers, will investigate

**Comment by Mirzero** [comment]
I am getting this in a low-latency environment.
The doors disappear (and sound like they break) as I pass through them.
If I disconnect and then reconnect... the door returns but in the open state.
It also allows me to build new doors in the open holes before I reconnect.

Seems like the door gets forced open, but desyncs from the client.
Will test later if other observing clients see the door break, or just get left open.

**Comment by Gameaday** [comment]
Observing clients see the doors as "open" and can interact with them, from my own experience on our server. 

Someone breaking the door you cannot see after this glitch occurs (as it remains visible to them) and replacing it makes it visible again to the original client...  but it is unbreakable by the original glitched client while "invisible" (until replaced). Hope that makes sense. 

Basically it only disappears from one client. If behaves normally for everyone else. And upon replacement by someone else behaves normally again until the glitch reoccur.

**Comment by Libbers** [comment]
Happening here as well, reconnecting shows them in open state

**Comment by QuiCM** [comment]
This is an issue with send tile square handling.
For temporary relief use the `tshock.ignore.sendtilesquare` permission - until we fix it properly :)

**Comment by stetsonblade** [comment]
Trap doors also auto shut when clicked. I can't get out of a room with a trap door unless I'm an superadmin (maybe admin or higher but I only have default and superadmin). I have the ignore.sendtilesquare added to default which fixed the door issue, but trap door is still an issue.

**Comment by lucasvperini** [comment]
I'm getting the Trap door issue too, `tshock.ignore.sendtilesquare` don't fix the problem.
Any fixes on this?

Thanks.

**Comment by stetsonblade** [comment]
> I'm getting the Trap door issue too, `tshock.ignore.sendtilesquare` don't fix the problem.
> Any fixes on this?
> 
> Thanks.

The only workaround I found so far was set the character as superadmin. Seems like there's some permission in superadmin that fixes the issue...

**Comment by QuiCM** [comment]
https://gfycat.com/illegalancientgreatargus

I can't reproduce any door/trapdoor issues while using the `tshock.ignore.sendtilesquare` permission.
If this only affects specific doors/trapdoors, could someone please list which ones definitely have issues?
Thanks

**Comment by SpiderDave** [comment]
I'm getting this issue too, where walking into doors sometimes removes them. It only happens with smart doors enabled, and only when walking into a closed door.  Sometimes the door won't disappear but it will make the noise as if it's been mined, and a few more times walking through the door will remove it.  I've had it remove a door (obsidian door), then I replaced it with a wooden door. Mining the wooden door sometimes brings the obsidian door back from nowhere (!).  I also ran through the large gate in the floor below where the above room's door unplaced, and that above room's door magically came back.  I'm not having any latency issues, so I can't say it's related to that.

**Comment by hakusaro** [comment]
@SpiderDave we actually know the root cause of the problem -- it's how we handle `SendTileSquare` packets. The problem is that `SendTileSquare` is basically the linchpin of all bulk updates -- if you give people the permission `tshock.ignore.sendtilesquare` it will work, but the damage will be that anyone can do anything to the world, essentially.

**Comment by iFocsy** [comment]
@hakusaro I've noticed and Reproduced that if you get pretty close to the door, and just give a tap, in a normal server it just quickly opens and closes the door, but when SendTileSquare is enable, if you try the same, it will disappear. Years ago i've been following this issue and in past before it got tracked, you had to pretty spam open/close so it happens, now what i've seen using the Debug Verbose, maybe it's because of the delay of the packets sent too quickly?

That's just a curiosity, i'm pretty new to tShock dev side but still need to know more how it handles to see if i can help.

If needed i can record Server Verbose x Client Test to show.

**Comment by hakusaro** [comment]
I honestly think that you’ve not given the permission to the affected player — if we don’t do anything with the packet the server processes it like normal. That would make this a vanilla issue but we’re pretty sure it’s not that. You should send debug logs (but we’re working on directly fixing the problem anyway).

**Comment by AceofSpades5757** [comment]
Having the same problem with _doors_ and _trapdoors_ in **TShock 4.4.0 Pre-release 8**.

>As a _quick fix_, I tried to use `group addperm * tshock.ignore.sendtilesquare` just to get the doors to work.
>_Restarted_ and _confirmed_ group permissions with `group listperm default` and `group listperm guest`.
>
>Problem **persisted**.

**Comment by hakusaro** [comment]
Do you have debug logs? (Set `DebugLogs` to `true` in `config.json` then run `/reload` and then cause the issue to happen (you should chat `start of issue` then move as little as possible to recreate the issue and then chat `end of issue`) and then upload the logs so we can take a look?)

**Comment by Saturate** [comment]
I'll try to set my server to debug as well, we had this issue a couple of times.

**Comment by hakusaro** [comment]
Latest build includes a manual /sync command that can be used to force the server to send the correct tile data to a client if their door disappears. This means that it’s faster to resolve than normal.
