### ISSUE TITLE
TShock 4.4.0 Pre 1 Sleeping only works for local user, doesn't pass the time

### ISSUE THREAD

**Issue by MysteriousAeon** [Pryaxis/TShock#1782]
Just like the title, you can sleep in beds but only you can see it and when everyone sleeps, time doesn't pass.

**Comment by QuiCM** [comment]
Thanks, will look into it

**Comment by sirsikes777** [comment]
In addition sitting in chairs only works for the client.

**Comment by QuiCM** [comment]
Hi, I think this may be fixed now. Could anyone confirm?

**Comment by sk9c00** [comment]
> In addition sitting in chairs only works for the client.

Unsure about time passing, I'll test that tomorrow when I get the time to.

On the other hand, sitting on chairs/benches? does show up for other players in the same server.
