### ISSUE TITLE
Smartdoors make doors disappear

### ISSUE THREAD

**Issue by Wolfie4** [Pryaxis/TShock#1786]
* TShock version: 4.4.0 
* TShock build number (if known):

When using smart doors with Tshock it seems they disappear. Havnt had this issue in single player. 

1. Place door 
2. Walk through with smartdoors on 
3. Door Disappears
4. place a block where the door was 
5. door reappears

Video Link: https://streamable.com/cssvhv

**Comment by Kavex** [comment]
Not just smart doors, already has an issue open https://github.com/Pryaxis/TShock/issues/1774

**Comment by QuiCM** [comment]
Will track this under #1774
