### ISSUE TITLE
TShock 4.4.0 Pre 2 Cannot remove NPC from housing

### ISSUE THREAD

**Issue by lluckymou** [Pryaxis/TShock#1792]
* TShock version: 4.4.0 Pre 2

#### Reproduction steps?
the title already describes the problem

1. /group addperm owner * (or any other group for that matter)
2. /group add vanilla * (even with a new group with all permissions)
3. Try to remove a NPC from a house (they do not have to be in towns, this is for all NPCs)
4. The banner wont probably be removed and the house will still be assigned to that NPC

#### Any stack traces or error messages (if known)?
Nothing on the console

#### Any screenshots?
![issue](https://user-images.githubusercontent.com/19612449/82330177-dc766400-99b8-11ea-8a7c-a1a44dc7aa10.png)

**Comment by lluckymou** [comment]
just a quick comment, even with /su this persists, so I don't think that's related to permissions

**Comment by QuiCM** [comment]
Thanks. I believe the packet for this got shuffled around a bit so we probably aren't handling it correctly. Will look into it

**Comment by lluckymou** [comment]
Confirmed in v4.4.0.0 Pre 6 (for Terraria 1.4.0.3)
