### ISSUE TITLE
Update Commands.cs to remove obsolete forums reference

### ISSUE THREAD

**Issue by Retrograde-i486** [Pryaxis/TShock#1793]
**Is your feature request related to a problem? Please describe.**
More of a suggestion really, noticed this when setting up an account on a Pre3 server

**Describe the solution you'd like**
_Change the text in Commands.cs from_ 

args.Player.SendSuccessMessage("Share your server, talk with other admins, and more on our forums -- https://tshock.co/");

_to something like_

args.Player.SendSuccessMessage("Submit bugs, discuss issues and more on our github page  -- https://github.com/Pryaxis/TShock/");

**Comment by hakusaro** [comment]
@Retrograde-i486 thank you so much for pointing this out! I really appreciate it! :green_heart: I've fixed this in the latest iteration of the codebase :)

@all-contributors add @Retrograde-i486 for code
