### ISSUE TITLE
[Pre 3] Pylons don't work.

### ISSUE THREAD

**Issue by artur9010** [Pryaxis/TShock#1795]
* TShock version: Pre 3

Working pylons were put on world while on vanilla server.
If you destroy and attempt to place pylon, it becomes invisible for the guy who placed it (other players can see it).
After reconnecting to the server pylon is visible again.
Pylons placed are not functional - right-clicking on them will show the map, but any attempt to teleport will show the message that you are too far from a pylon.
Placed pylon will not be visible on the map (like it doesn't exist), you also can't teleport to it from other ones.
This essentially makes pylons a furniture item like table or chair.

#### Reproduction steps (if applicable)?

1. Place the pylon (it should disappear)
2. Reconnect (to see the pylon)
3. Pylon no longer works

#### What plugins and what versions of those plugins are you running?
None.

**Comment by lytedev** [comment]
Any update on this? This seems to be a pretty important part of 1.4 that would be great to have working.

**Comment by HeySteets** [comment]
A trick some players on my server found was to destroy and replace all Pylons on the server. They work temporarily. Definitely not a fix, but a short-term patch at the very least.

**Comment by QuiCM** [comment]
Temporary workaround *may* be adding the `tshock.ignore.sendtilesquare` permission. It's on the list to get fixed

**Comment by hakusaro** [comment]
This should be fixed in the next pre-release.
