### ISSUE TITLE
Server Desync On Respawn 

### ISSUE THREAD

**Issue by TheCipher01** [Pryaxis/TShock#1800]
* TShock version: Latest pre release
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1) Die
2) Respawn and other players won't see you moving

I'm honestly not sure how to reproduce this because this issue just showed up less than an hour ago. One friend first noticed it earlier in the day but relogging fixed it and we didn't have the issue again until recently. Also after you die you can't seem to open chests till you relog. The only thing I could think of is we had a friend start playing golf, and then it seemed to cause more issues. No errors at all in the server console. It's running on a vps running debian. This is kind of based on #1799 Been watching the CPU usage all day  really haven't had anything above 50% on any one thread at any given time. We're at 2.07/5.82 G of RAM usage. 

#### Any stack traces or error messages (if known)?

```
PUT SUPER LONG ERROR MESSAGES IN THE TICK MARKS
```

#### Any screenshots?

 
Server Console has no errors. 

This is right after I died I was unable to pick up my money or anything and my friend didn't see me moving. 
https://gyazo.com/1fc4da7e976c69dde6961fff9b9b9c04

#### What plugins and what versions of those plugins are you running?
No plugins

**Comment by Patrikkk** [comment]
This is resolved by AxeelAnder@53d211b 
Thank you for the reports guys! Helped us fix it.

**Comment by TheCipher01** [comment]
Well I just died on pre4 and again was desynced. Is that fix not in pre4?

**Comment by Patrikkk** [comment]
Sorry, my message wasn't clear enough. This will be fixed in the next pre-release which drops in a couple of hours!
