### ISSUE TITLE
TShock 4.4.0 Pre 2/Pre4v2 Scarab Bomb only working on partial type of blocks 

### ISSUE THREAD

**Issue by Sodium-Aluminate** [Pryaxis/TShock#1808]
#1781
* TShock version: [TShock_4.4.0_226_Pre1_Terraria1.4.0.2](https://github.com/Pryaxis/TShock/releases/tag/v4.4.0-pre2), [TShock_4.4.0_226_Pre4v2_Terraria1.4.0.2](https://github.com/Pryaxis/TShock/releases/tag/v4.4.0-pre4)
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. put some blocks
2. use Scarab Bomb

#### Any stack traces or error messages (if known)?

(no, nothing in console)

#### Any screenshots?

------ prev2 -------
![before](https://user-images.githubusercontent.com/38349409/82426800-e08aaa80-9aba-11ea-928a-6da3e6085b33.png)
before

![after](https://user-images.githubusercontent.com/38349409/82427058-2b0c2700-9abb-11ea-9b9e-1c1af3ed2185.png)
after

------- prev4 -------
![image](https://user-images.githubusercontent.com/38349409/82428015-7541d800-9abc-11ea-9c17-6bdf4405f36c.png)
before

![image](https://user-images.githubusercontent.com/38349409/82428055-868ae480-9abc-11ea-906a-ec6ad1a7c68e.png)
after

#### Any log messages from files that end in `.log` or `.txt`?

------ prev2 -------
[ServerLog.txt](https://github.com/Pryaxis/TShock/files/4655719/ServerLog.txt)
------ prev4 -------
[ServerLog.txt](https://github.com/Pryaxis/TShock/files/4655759/ServerLog.txt)

#### What plugins and what versions of those plugins are you running?

there no plugin.

**Comment by Fanyatsu** [comment]
Also noticed that. Same with my server

**Comment by hakusaro** [comment]
Thank you for the awesome bug report @Sodium-Aluminate! I really appreciate it! You're awesome :)
