### ISSUE TITLE
TShock 4.4.0 Pre4 Desync upon death

### ISSUE THREAD

**Issue by Minescence** [Pryaxis/TShock#1809]
* TShock version: [TShock 4.4.0 Pre4](https://github.com/Pryaxis/TShock/releases/tag/v4.4.0-pre4)
* TShock build number (if known): 

#### Reproduction steps (if applicable)?

1. Die to anything
2. Now you're desynced until you reconnect to server

#### Any stack traces or error messages (if known)?

```
Nothing in console.
```

#### Any screenshots?

![image](https://user-images.githubusercontent.com/51507768/82434461-2b90c780-9a93-11ea-87a0-d128d8f81a07.png)

Client data before dying
![image](https://user-images.githubusercontent.com/51507768/82434949-e751f700-9a93-11ea-9c30-1ec5cf2f5aa4.png)

Client data after dying
![image](https://user-images.githubusercontent.com/51507768/82434537-42cfb500-9a93-11ea-95ea-1af7ff854a82.png)

#### Any log messages from files that end in `.log` or `.txt`?

**[2020-05-19_19-21-01.log](https://github.com/Pryaxis/TShock/files/4656114/2020-05-19_19-21-01.log)**

#### What plugins and what versions of those plugins are you running?

No plugins

**Comment by dly2424** [comment]
Yup, entire fresh install of tshock pre 4 still leads to desyncs on death (still using same world though. Shouldnt matter however)

Ubuntu - using sudo permissions in screen
`sudo screen -L -Logfile log -dmS terraria mono-sgen /path/to/tshock/TerrariaServer.exe -ip (ipv4here) -port 7777 -maxplayers 20 -world /path/to/world.wld -autocreate 0 -pass password`

Ill do some testing in the config file/OS environment and looking around for errors/issues. If i find anything ill post about it.

**Comment by dly2424** [comment]
Interestingly, not specifiying the -world flag seems to rid of my desyncs, this is also using another world. Still looking into it.

Things that i changed around and havent affected it are:
Sudo permissions
Screen
Some Configurations

EDIT:
Further testing shows that -world flag doesnt matter, but instead the world seems to.
World with desyncs can be found below, using any pre versions so far up to pre 4 seems to cause desyncs.

A fresh world does not seem to have this issue.

[world.zip](https://github.com/Pryaxis/TShock/files/4657537/world.zip)

(All done on an untouched install of Pre 4 - Please attempt to replicate)

**Comment by Patrikkk** [comment]
This is resolved by AxeelAnder@53d211b 
Thank you for the reports guys! Helped us fix it.

**Comment by dly2424** [comment]
> This is resolved by [AxeelAnder/TShock@53d211b](https://github.com/AxeelAnder/TShock/commit/53d211b)
> Thank you for the reports guys! Helped us fix it.

This is not fixed in the latest release. Still desyncing apon death. If you get the chance, i can add you to the server or you should be able to replicate it using the Pre 4 release and the world i posted above.
Unless im dumb and you have yet to put a release fixing this up yet.

**Comment by Patrikkk** [comment]
Sorry, my message wasn't clear enough. This will be fixed in the next pre-release which drops in a couple of hours!
