### ISSUE TITLE
Configurable sqlite db path

### ISSUE THREAD

**Issue by LiuXingYuYe** [Pryaxis/TShock#1810]
stay config.json set up tshock.sqlite Read location

**Comment by AxeelAnder** [comment]
抱歉英语有点看不懂，你是说添加一个自定义sqlite路径的设置选项吗

**Comment by LiuXingYuYe** [comment]
> 抱歉，英语有点看不懂，你是说添加一个自定义sqlite路径的设置选项吗

是的，抱歉咱不会英文的机翻。希望可以自定义数据库的路径以方便多个服务器共用存档。

**Comment by AxeelAnder** [comment]
> > 抱歉，英语有点看不懂，你是说添加一个自定义sqlite路径的设置选项吗
> 
> 是的，抱歉咱不会英文的机翻。希望可以自定义数据库的路径以方便多个服务器共用存档。

如果想共用数据库推荐使用mysql作为数据库，只要多个服务器使用相同配置即可。sqlite本身不支持共用，强行共用有可能出问题

**Comment by LiuXingYuYe** [comment]
> > > 抱歉，英语有点看不懂，你是说添加一个自定义sqlite路径的设置选项吗
> > 
> > 
> > 是的，抱歉咱不会英文的机翻。希望可以自定义数据库的路径以方便多个服务器共享存档。
> 
> 如果想共享数据库推荐使用mysql作为数据库，只要多个服务器使用相同的配置即可。sqlite本身不支持共享，强行共享有可能出问题

抱歉，渣渣看不懂_(:з」∠)_，能说说怎么设置么。以前1241版本时候有个大佬汉化的ts添加过自定义sqlite路径的设置方便开肉前肉后服，用着没有出啥问题。

**Comment by AxeelAnder** [comment]
Solved at https://github.com/Pryaxis/TShock/pull/1811.

已添加该功能
