### ISSUE TITLE
TShock 4.4.0 Pre 2 Venom staff kicks for "Added buff to NPC abnormally"

### ISSUE THREAD

**Issue by Tomo3214** [Pryaxis/TShock#1814]
It's the same problem with Venom Staff like with whips you get kicked with message: "Added buff to NPC abnormally" and when you type rain you use emote instead of command.

**Comment by QuiCM** [comment]
Rain command is fixed in latest releases - now falls under `/worldevent rain`.
Going to update incident title to reflect the venom staff issue only
