### ISSUE TITLE
can't move NPC

### ISSUE THREAD

**Issue by Tibbind** [Pryaxis/TShock#1817]
!!!!!! PLEASE FILL IN THE TEMPLATE BELOW THANK YOU VERY MUCH !!!!!!

If you don't need help, delete this template and just post an issue (feature requests and discussions and the like).

* TShock version: 4.4.0 226 pre3
* TShock build number (if known): part of above maybe?

#### Reproduction steps (if applicable)?

1. have multiple NPC
2. try to move NPC out by right clicking their icon in the housing menu
3. Can't move NPC out
4. Can't move new NPC in

#### Any stack traces or error messages (if known)? none

```
N/A, server outputs no error
```

#### Any screenshots? not needed

!!!!!! PLEASE FILL IN THE TEMPLATE ABOVE THANK YOU VERY MUCH !!!!!!

**Comment by ColinBohn** [comment]
Same issue as https://github.com/Pryaxis/TShock/issues/1792.

**Comment by QuiCM** [comment]
Closing - tracking under #1792
