### ISSUE TITLE
error auto door

### ISSUE THREAD

**Issue by Tibbind** [Pryaxis/TShock#1818]
* TShock version: 4.4.0 226 pre3
* TShock build number (if known): see above maybe

#### Reproduction steps (if applicable)?

1. turn on smart doors
2. run through a door
3. door will stay open and disappear from client side
4. Door stays open, able to put new doors over existing door, breaking block beneath door will drop the door.

#### Any stack traces or error messages (if known)? n/a

```
no error message
```

#### Any screenshots? after restarting server, I tried again but am no longer able to recreate the issue

 can't access console at the moment

 https://imgur.com/a/plJhBaj

**Comment by ColinBohn** [comment]
Same issue as https://github.com/Pryaxis/TShock/issues/1774.

**Comment by QuiCM** [comment]
Closing - tracking in #1774
