### ISSUE TITLE
Journey mode item research will not be available when SSC is enabled

### ISSUE THREAD

**Issue by 2hakjv** [Pryaxis/TShock#1833]
* TShock version:TShock 4.4.0 Pre 5

#### Reproduction steps (if applicable)?

1. Open the Jurney Mode server with SSC enabled
2. Research the item

#### Any screenshots?

![20200521161939_1](https://user-images.githubusercontent.com/61584406/82533810-f9f52a80-9b7e-11ea-9b0a-5d6604b76709.jpg)
![20200521161945_1](https://user-images.githubusercontent.com/61584406/82533815-fb265780-9b7e-11ea-969a-610ea525abb6.jpg)
![20200521161947_1](https://user-images.githubusercontent.com/61584406/82533816-fb265780-9b7e-11ea-98e6-8566753261f9.jpg)

**Comment by hakusaro** [comment]
This is fixed in #1909, which will be landing in a pre-release soon.
