### ISSUE TITLE
Mannequins break upon being placed (4.4.0 pre-6)

### ISSUE THREAD

**Issue by PolarNinja23** [Pryaxis/TShock#1844]
TShock version: 4.4.0 pre-6

Reproduction steps (if applicable)?

1. Join server 
2. Attempt to place Mannequin/Womannequin
3. Mannequin/Womannequin breaks immediately after placing, consuming the Mannequin/Womannequin still despite it not being placed

 Any stack traces or error messages (if known)?
No

Any screenshots?
No

Context: See Title, they break upon being placed.

What plugins and what versions of those plugins are you running?
Only what originally came in the ServerPlugins folder upon downloading it.

**Comment by QuiCM** [comment]
Thanks for the report. This is a known issue with our sendtilesquare handling.
For a temporary workaround you can use the permission `tshock.ignore.sendtilesquare`

**Comment by hakusaro** [comment]
This should be fixed in the next pre-release.
