### ISSUE TITLE
Doors Break and Vanish for any player that is not a logged in Admin

### ISSUE THREAD

**Issue by strevorrow** [Pryaxis/TShock#1846]
TShock version: 4.4.0 pre-6

Reproduction steps (if applicable)?

    1) Join server
    2) Do not log in
    3) walk back and forth between any door with "Easy Doors" enabled
    4) Note how eventually the door vanishes for only the user that triggered the vanishing until reloading into the server 

Any stack traces or error messages (if known)?
No

Any screenshots?
No

Context: Simple house with a single door used to test

What plugins and what versions of those plugins are you running?
Only what originally came in the ServerPlugins folder upon downloading it.

**Comment by QuiCM** [comment]
Thanks for the report. 
We're tracking this one under #1774
As a temporary workaround you can give players the `tshock.ignore.sendtilesquare` permission
