### ISSUE TITLE
/status?players=true & /v2/users/activelist & /v2/server/status

### ISSUE THREAD

**Issue by XGhozt** [Pryaxis/TShock#1850]
TerrariaAPI Version: 2.1.0.0 (Protocol v1.4.0.3 (227), OTAPI 1.4.0.3)
---

```
{
  "status": "500",
  "error": "Internal server error.",
  "errormsg": "Object reference not set to an instance of an object",
  "stacktrace": "  at TShockAPI.RestManager.ServerStatusV2 (Rests.RestRequestArgs args) <0x4254d380 + 0x00805> in <filename unknown>:0 \n  at TShockAPI.RestManager.<RegisterRestfulCommands>b__2_0 (Rests.RestRequestArgs a) <0x4254d080 + 0x000ab> in <filename unknown>:0 \n  at Rests.RestCommand.Execute (Rests.RestVerbs verbs, IParameterCollection parameters, IRequest request, IHttpContext context) <0x42549b30 + 0x0007c> in <filename unknown>:0 \n  at Rests.Rest.ExecuteCommand (Rests.RestCommand cmd, Rests.RestVerbs verbs, IParameterCollection parms, IRequest request, IHttpContext context) <0x42549a40 + 0x00046> in <filename unknown>:0 \n  at Rests.SecureRest.ExecuteCommand (Rests.RestCommand cmd, Rests.RestVerbs verbs, IParameterCollection parms, IRequest request, IHttpContext context) <0x42548e30 + 0x0008f> in <filename unknown>:0 \n  at Rests.Rest.ProcessRequest (System.Object sender, HttpServer.RequestEventArgs e) <0x425428b0 + 0x004ba> in <filename unknown>:0 "
}
```

The above is a result of **/status?players=true** and **/v2/server/status**

~~And so I tried: **/v2/users/activelist**~~
~~But that only returned:~~

```
{
  "status": "200",
  "activeusers": "XGhozt"
}
```

~~However, I have 3 players on the server.~~

I should also note that the above error only occurs if players are on the server. If no players are on the server it just returns an empty array correctly.

**Comment by QuiCM** [comment]
Not sure how well this is documented, but `/v2/users/activelist` only returns active *users*, i.e., players who are logged in.
Not sure where the 500 is coming from, I'll check that out

**Comment by XGhozt** [comment]
Ah, that makes sense (RE: activelist). Thanks. I'm on Discord if you need more details. I tried to find any other related issues or recent commits and this was all I could find: https://github.com/Pryaxis/TShock/commit/ee20946cdd8dd7c7204804694bc16e2899619fee

**Comment by QuiCM** [comment]
https://github.com/Pryaxis/TShock/commit/b9b83dd36f31b2e038e5720cd844ae43878bc267 should fix this :)

**Comment by hakusaro** [comment]
Is this still an issue?

**Comment by XGhozt** [comment]
It's working for me now, we can close this.
