### ISSUE TITLE
1.4 research doesn't work "Owner" Journey mode + master mode

### ISSUE THREAD

**Issue by GamerKing122** [Pryaxis/TShock#1855]
please add journey mode as a separate world option to fix this or add "parameters" such as primary gamemode and subgamemode. "subgamemode " could run like this Journey/classic/mediumcore/hardcore.
primarygamemode can be the difficulty eg journey/normal/expert/mastermode

**Comment by Ristellise** [comment]
I think I know what you meant, you mean this difficulty slider?

![image](https://user-images.githubusercontent.com/7894419/82724072-f9d36700-9d05-11ea-9e82-b58ae840a80c.png)

**Comment by GamerKing122** [comment]
yes

**Comment by GamerKing122** [comment]
non ssc it doesn't save research on server
i researched wooden fishing crates with mastermode enabled and it didn't save research it just deleted them not sure if this is a global bug

**Comment by hakusaro** [comment]
This should be fixed since #1909 is merged.
