### ISSUE TITLE
SendMessage update to inbuilt Terraria Chat Messaging breaks with '{' '}' in msg

### ISSUE THREAD

**Issue by Stealownz** [Pryaxis/TShock#1856]
* TShock version: self build on https://github.com/Pryaxis/TShock/commit/83eb707761dc37ebb0b7a90aadeca5896fb568f0
* TShock build number (if known): https://github.com/Pryaxis/TShock/commit/83eb707761dc37ebb0b7a90aadeca5896fb568f0

#### Reproduction steps (if applicable)?

1. Connect to server and type `{ test`
2. A blank "message" appears in the chat box instead of `{ test`
3. Any group with prefix/suffix using { } as formatting will always have blank text.

#### What plugins and what versions of those plugins are you running?
Just TShock.

**Comment by QuiCM** [comment]
Should be resolved in https://github.com/Pryaxis/TShock/commit/5d2945ab1f4be47ab031220ffca9d5ae9d6b4fc4.
FromFormattable doesn't like curly braces apparently
