### ISSUE TITLE
Worldevent sandstorm does not function properly

### ISSUE THREAD

**Issue by samamstar** [Pryaxis/TShock#1877]
* TShock version: 1.4.0.3 Pre6
Any sandstorms produced with /worldevent sandstorm will only exist for a short while (roughly 30 seconds to a minute). 

I *think* this may be caused by issue #1763 . Sandstorms only start naturally when wind is above 30mph, and I think that since you cannot set this with commands the game is ending the sandstorm quickly as wind isn't high enough. 

I know pre7 is out, but the changelog doesn't mention wind so I'm still posting this

**Comment by hakusaro** [comment]
@samamstar can you try in this version (or a later pre-release)? https://github.com/Pryaxis/TShock/suites/712280319/artifacts/6959701

**Comment by AxeelAnder** [comment]
When wind speed is not suffient, sandstorm will stop as 16x faster.
