### ISSUE TITLE
doors dissapering

### ISSUE THREAD

**Issue by jsgameing101** [Pryaxis/TShock#1891]
* TShock version: 1.4.0.4
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. open door
2. close door
3. walk thru acouple times
4. door dissapears

#### Any stack traces or error messages (if known)?

```
PUT SUPER LONG ERROR MESSAGES IN THE TICK MARKS
```

#### What plugins and what versions of those plugins are you running?
none

**Comment by hakusaro** [comment]
This is being tracked in #1774 -- thank you for the report though!
