### ISSUE TITLE
Auto doors still bugged - with video 

### ISSUE THREAD

**Issue by Tibbind** [Pryaxis/TShock#1896]
!!!!!! PLEASE FILL IN THE TEMPLATE BELOW THANK YOU VERY MUCH !!!!!!

If you don't need help, delete this template and just post an issue (feature requests and discussions and the like).

* TShock version: 4.4.0.0
* TShock build number (if known): latest

#### Reproduction steps (if applicable)?

1. turn on auto doors
2. walk through them
3. doors more likely to break if they weren't supposed to be opened - ala ropes next to door, run into door in direction of ropes
4. doors still "exist" just not for client

#### Any stack traces or error messages (if known)?

```
PUT SUPER LONG ERROR MESSAGES IN THE TICK MARKS
```

#### Any screenshots? 
https://youtu.be/UGdGV40odhw
https://imgur.com/a/qtSUJ38

!!!!!! PLEASE FILL IN THE TEMPLATE ABOVE THANK YOU VERY MUCH !!!!!!

**Comment by hakusaro** [comment]
This is being tracked in #1774. You can work around with: https://github.com/Pryaxis/TShock/issues/1774#issuecomment-631825861.
