### ISSUE TITLE
Door issues.

### ISSUE THREAD

**Issue by blomer** [Pryaxis/TShock#1905]
* TShock version: 4.4.0
* TShock build number (if known): 4.4.0 Release

#### Reproduction steps (if applicable)?

Door disappearing:
1. Walk through a door during a slime rain
2. Door disappears.

Lead door disappearing and turning into a wooden door.
1. Place Lead door.
2. Use it a couple of times.

#### Any stack traces or error messages (if known)?

None

#### Any screenshots?

Self explainatory.

#### Any log messages from files that end in `.log` or `.txt`?

Nope.

#### What plugins and what versions of those plugins are you running?

No other plugins. Just using TShock as default.

**Comment by hakusaro** [comment]
This is being tracked in #1774.
