### ISSUE TITLE
gravedigger's shovel not supported

### ISSUE THREAD

**Issue by goardis** [Pryaxis/TShock#1945]
TShock 4.4.0 Pre-release 8 for Terraria 1.4.0.4

using the gravedigger's shovel on dirt doesn't break the center block and using it on a soft block like sand doesn't break anything at all.

**Comment by kristupas098** [comment]
Still not fixed

**Comment by hakusaro** [comment]
Thanks for letting us know!
GitHub <notifications@github.com> wrote:
“Still not fixed”

**Comment by QuiCM** [comment]
Requesting followup on this. Should be solved in #2085, if its not please comment here
