### ISSUE TITLE
Added  Sparkle Slime buff to NPC abnormally

### ISSUE THREAD

**Issue by Ayrawei** [Pryaxis/TShock#1956]
* TShock version: TShock 4.4.0 Pre-release 8 for Terraria 1.4.0.4
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. Grab some Sparkle Slime Balloons (drop from Queen Slime Boss)
2. Go to some friendly NPC (I've tried it on the Merchant)
3. Throw the balloon at the NPC (giving them the Sparkle Slime debuff)
4. Feel the bouncer's steel boot.

#### Any stack traces or error messages (if known)?
none

#### Any screenshots?
There was only the console message provided below

#### Any log messages from files that end in `.log` or `.txt`? What are the last 100 log messages from the server console?

2020-05-30 22:51:11 - Utils: INFO: Broadcast: Atyaraya has left.
2020-05-30 22:51:11 - TShock: INFO: Atyaraya disconnected.
2020-05-30 22:51:11 - TSPlayer: INFO: Kicked Atyaraya for : 'Added buff to NPC abnormally.'
2020-05-30 22:51:11 - Utils: INFO: Broadcast:  was force kicked for 'added buff to npc abnormally.'

#### What plugins and what versions of those plugins are you running?
none

**Comment by moisterrific** [comment]
This will be fixed in the next TShock release. In the meantime, avoid throwing party girl bathwater at anyone other than Guide and Clothier.

**Comment by hakusaro** [comment]
This should be fixed since the introduction of @moisterrific's changes.
