### ISSUE TITLE
crash...

### ISSUE THREAD

**Issue by BellCocoa** [Pryaxis/TShock#1959]
* TShock version:TShock_4.4.0_Pre8_Terraria1.4.0.4
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. Some step
2. Some other step
3. Some bigger step
4. This is the problem

#### Any stack traces or error messages (if known)?

```
PUT SUPER LONG ERROR MESSAGES IN THE TICK MARKS
```

#### Any screenshots?

[TShock_4.4.0_Pre8_Terraria1.4.0.4.zip](https://github.com/Pryaxis/TShock/files/4706766/TShock_4.4.0_Pre8_Terraria1.4.0.4.zip)

**Comment by hakusaro** [comment]
It looks like you've uploaded the release payload, which means that this issue is quite difficult to debug. Please let me know if you have a zip that has information in it. Thanks! 💚
