### ISSUE TITLE
No One Can Place Pylons Except Superadmin.

### ISSUE THREAD

**Issue by Kirbyarm** [Pryaxis/TShock#1963]
This tells me that there is likely a permission node somewhere controlling whether or not TShock allows a given group to place functional pylons normally, as a superadmin is capable of doing the last I checked.

May I asked what the new permission node for placing pylons is in the 1.4 pre-release?

tshock.world.pylon or something similar?

Thanks guys! Making this possible so fast on 1.4 has been dreamy so far!

**Comment by QuiCM** [comment]
Currently no permission exists for it. You can temporarily work around the issue by giving the `tshock.ignore.sendtilesquare` permission.
May I ask which pre-release you are using?

**Comment by Kirbyarm** [comment]
I believe 3 or 4, I'm in the process of updating now and re-overhauling my default database groups and permissions since I was playing on another TShock server (not my own) and that has now made me ready to look into hosting my own again.

Thank you for the workaround! I'll bump that down from mods to members then for the time being.

**Comment by hakusaro** [comment]
In general you should **never** be running a pre-release version that's out of date. We don't support pre-releases at all. The only path is to upgrade forward. I would highly suggest updating. It's essentially painless.

**Comment by hakusaro** [comment]
This should be fixed in the next pre-release.

**Comment by Kirbyarm** [comment]
Hey there, yes I know. I was posting this from my experience on my friend's (at the time) fully updated and run server. I was answering what version I had on the version I was in the middle of setting up my own server - if that makes sense. Sorry for the confusion and thank you for the clarification.
