### ISSUE TITLE
Missing "martian" arg from "/worldevents invasion" Invalid commands response.

### ISSUE THREAD

**Issue by LMacs** [Pryaxis/TShock#2013]
Hi,

When using the "/worldevent invasion" command, the "invalid command" response fails to list the "martian" argument as a valid argument. Very minor issue, but I couldn't find a definitive list of arguments, thus it took me a little while to figure it out.

May be helpful to update the readme.io or invalid command output to include it.

Thanks,
-L

**Comment by moisterrific** [comment]
Good catch, sounds like a very easy fix so I’ll get on that.
