### ISSUE TITLE
Add RegionProtectMannequins if possible 

### ISSUE THREAD

**Issue by moisterrific** [Pryaxis/TShock#2018]
## Current behavior
Mannequins (and Womannequins) are in fact "protected" tile squares if they are in placed within protected regions, unauthorized users cannot remove them, but they can still open the mannequin and remove/change the stored items. 

## Suggested change
Add a new config defined option `RegionProtectMannequins` (`false` by default for consistency w/ other `RegionProtectX` options. 

Not sure if this is possible though, cuz right now I'm aware of how TShock protects chests if `RegionProtectChests = true`, but dunno if Mannequins use the same packet or a different one.

**From `GetDataHandlers.cs` line 2755:**
```csharp
			if (!args.Player.HasBuildPermission(x, y) && TShock.Config.RegionProtectChests)
			{
				TShock.Log.ConsoleDebug("GetDataHandlers / HandleChestActive rejected build permission and region check {0}", args.Player.Name);
				args.Player.SendData(PacketTypes.ChestOpen, "", -1);
```

Also I dunno how hat racks are affected, maybe they behave the same way as existing mannequins?

**Comment by QuiCM** [comment]
Think this should be in latest prerelease now :)
