### ISSUE TITLE
Special characters in admin password used in REST API query string

### ISSUE THREAD

**Issue by XGhozt** [Pryaxis/TShock#2022]
Anyone know of a possible bug that breaks the REST API if the password being used has special characters in it? Usually with a REST API the requests that need a user/pass are accepted as POST instead of GET which helps with special characters getting jumbled. Not sure if this actually a bug or maybe I need to encode them beforehand or what. I haven't been encoding because that usually results in an invalid password, I can only assume there's no entity decoding happening. Just had a user with a special character in the password and it was just showing invalid password when passed as query string. Worked fine after changing to a password that didn't have a special character in it.

Possible breaking characters: `@ # $ % ^ & *`

**Comment by QuiCM** [comment]
Will need to investigate. Thanks for reporting

**Comment by QuiCM** [comment]
This one should be fixed in 51f179f.
In fact, all inputs should be correctly unescaped with 51f179f
