### ISSUE TITLE
Documentation is out of date following color format changes

### ISSUE THREAD

**Issue by pluto00987** [Pryaxis/TShock#2025]
* TShock version: 4.4.0 pre11

Firstly, I'm not sure if this might have been an intentional change for 4.4.x. It worked as of 4.3.26 and seems to have stopped working as of 4.4.0 pre 1. It definitly doesn't work as of pre 11.  I couldn't find anything relevant in the changelog though, so I thought I'd mention it here. There's also some related past issues #1314 #1317 
_I do not personally need this functionality._

The TShock-specific MOTD color attributes are no longer working. Instead, clients just see the literal color string(s) at logon:

![image](https://user-images.githubusercontent.com/3868322/84091682-2a342a00-a9c3-11ea-96f1-aa7baba39504.png)

That's using the default motd.txt from TShock 4.3.26. The color attributes are documented [here](https://tshock.readme.io/docs/message-of-the-day-config). I did notice that the 4.4.0 detault motd.txt has been updated and no longer contains this type of string(s). Again, that might suggest the change was intentional. If nothing else, it might should just be documented.

**Comment by AxeelAnder** [comment]
This doc is outdated, this color format has been cutted. Please use legacy color format.

https://github.com/Pryaxis/TShock/commit/2846ad915f40f28628e1b84cd08f78237b069bea#diff-3d2acd20354f0979c8f57f021f8b045eL26

**Comment by hakusaro** [comment]
This format was deprecated and slated for removal. The new default MOTD doesn't contain this formatting scheme. I've updated the title of this issue :) thank you for reporting!

**Comment by QuiCM** [comment]
Updated
