### ISSUE TITLE
Gem locks don't let you place gems 

### ISSUE THREAD

**Issue by Dameworth** [Pryaxis/TShock#2036]
Existing gem locks remain unchanged but if you try and put a gem in a gem lock it disappears.

**Comment by QuiCM** [comment]
This may be fixed in the next release! I believe gem locks use send tile square, which we currently have a buggy check for. You may be able to bypass this issue with the `tshock.ignore.sendtilesquare` permission

**Comment by QuiCM** [comment]
Hi, could anyone confirm if this is still an issue in latest release?
Thanks :)

**Comment by Armag3ddon** [comment]
Yep, still an issue.

**Comment by bartico6** [comment]
According to #2140 it is still an issue.
