### ISSUE TITLE
TshockWiki_ConfigSettings_Typesetting

### ISSUE THREAD

**Issue by PrettyGrey** [Pryaxis/TShock#2046]
https://tshock.readme.io/docs/config-settings

> ApplicationRestTokens
Type:` Dictionary2 Description: A dictionary of REST tokens that external applications may use to make queries to your server.Default:
` "System.Collections.Generic.Dictionary2[System.String,Rests.SecureRest+TokenData]"

**Comment by hakusaro** [comment]
I'm sorry?

**Comment by QuiCM** [comment]
Fixed. Thanks to Tejdxa in discord for pointing it out :)
