### ISSUE TITLE
Users cannot place item racks or mannequins 

### ISSUE THREAD

**Issue by lylet-AC** [Pryaxis/TShock#2049]
Hey all, 

I'm using TShock version: 4.4.0.0.  Members of my server seem to be unable to place weapon racks, mannequins, coat racks, anything of the sort.  Admin account works, so perhaps this is a permission thing.  My apologies if this is the incorrect place to post this, I'm not sure where else I can go.

**Comment by QuiCM** [comment]
This should be fixed in the next release! In the meantime you can bypass the check that is failing by giving people the `tshock.ignore.sendtilesquare` permission

**Comment by QuiCM** [comment]
Hi, could anyone confirm if this is still an issue in latest release?
Thanks :)
