### ISSUE TITLE
Owners don't have access to pet license

### ISSUE THREAD

**Issue by HairyMilkshakes** [Pryaxis/TShock#2050]
* TShock version: 1.4.0.5
* TShock build number (if known): 590

#### Reproduction steps (if applicable)?

1. Be owner
2. Buy pet license
3. Use it
4. Pet license disappears, no pet spawned, in chat it states that there's insufficient permission.

#### What plugins and what versions of those plugins are you running?
None.

**Comment by moisterrific** [comment]
This should be added to owner group by default, and most likely will be in the next release.

In the meantime, type `/su` to gain SuperAdmin for 10 mins so you have every permission.

**Comment by HairyMilkshakes** [comment]
Thank you - wasn't aware of the /su command.
