### ISSUE TITLE
Users can't use the Clentaminator and it's not a banned item on the server

### ISSUE THREAD

**Issue by HairyMilkshakes** [Pryaxis/TShock#2057]
* TShock version: 1.4.0.5
* TShock build number (if known): 607

#### Reproduction steps (if applicable)?
1. Get a Clentaminator
2. Use it (with tshock.world.modify permission)
3. User can't convert corruption/hallow

To further elaborate on the issue, I gave the users tshock.ignore.* and they are able to convert, but I don't see the converted blocks on my end. Not sure if it's a sync issue, permission issue, or both?

#### What plugins and what versions of those plugins are you running?
No plugins.

Thank you.

**Comment by QuiCM** [comment]
Likely send tile square issue. May be partially resolved when we next release, but may also need more investigation. Thanks for the report!

**Comment by HairyMilkshakes** [comment]
> 
> 
> Likely send tile square issue. May be partially resolved when we next release, but may also need more investigation. Thanks for the report!

Hi, after further investigation, users can convert the world fine with tshock.world.modify but it is not updated client side for me. So I suppose it is a send tile square issue, thanks.

**Comment by QuiCM** [comment]
Hi, could anyone confirm if this is still an issue in latest prerelease?
Thanks :)

**Comment by HairyMilkshakes** [comment]
Let me check for you - stay tuned.

**Comment by bsztankovacs** [comment]
I have tested it recently on a 2-player server, and neither of us found a problem either with the gameplay change or display.
