### ISSUE TITLE
Debug messages flooding console

### ISSUE THREAD

**Issue by ghost** [Pryaxis/TShock#2072]

**Comment by hakusaro** [comment]
Do you trust the players in the messages?

**Comment by mrshroomy** [comment]
Ye, there's backups so there's nothing that i'm afraid that the players will do and i don't think they'll do anything suspicious..

**Comment by jhinyu** [comment]
You can disable Debug reports by going into the config.json file in the tshock folder and changing the line,
"DebugLogs": true, to false.

**Comment by StinkyVoet** [comment]
Why is it turned on as default anyway? I would think it makes more sense to have it off as default, so you won't get issues like this one

**Comment by hakusaro** [comment]
The plan is to turn that default off with the next stable release. You're running an experimental build, no?

**Comment by StinkyVoet** [comment]
Oh right hahaha my bad!
