### ISSUE TITLE
Item bans are handled differently in public and internal scopes.

### ISSUE THREAD

**Issue by AnzhelikaO** [Pryaxis/TShock#2096]
https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/TShock.cs#L324
https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/TShock.cs#L335

Two ban systems lead to unexpected behavior: TShock.Itembans.ItemBans.Add(new ItemBan(itemName)) shows up in /itemban list but doesn't work because tshock checks TShock,ItemBans.DataModel.ItemBans instead. Item bans should be used in one place and should be public for developers to add temp bans. Or TShock,ItemBans.DataModel should be the same object as TShock.Itembans.

**Comment by QuiCM** [comment]
Should be resolved in 39e13f7. Thanks
