### ISSUE TITLE
Thresholds are not functioning right

### ISSUE THREAD

**Issue by Marcus101RR** [Pryaxis/TShock#2103]
* TShock version: 4.3.26
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. Set Config Tile Thresholds
  "KickOnDamageThresholdBroken": true,
  "TileKillThreshold": 300,
  "KickOnTileKillThresholdBroken": false,
  "TilePlaceThreshold": 110,
  "KickOnTilePlaceThresholdBroken": false,
  "TileLiquidThreshold": 100,
  "KickOnTileLiquidThresholdBroken": false,
  "ProjIgnoreShrapnel": true,
  "ProjectileThreshold": 700,
  "KickOnProjectileThresholdBroken": false,
  "HealOtherThreshold": 90,
  "KickOnHealOtherThresholdBroken": false,

2. Mine with fastest pickaxe possible, you will get stoned. Same with projectiles.

#### Any stack traces or error messages (if known)?
NONE
#### Any screenshots?
![image](https://user-images.githubusercontent.com/8344293/88703756-21b2c280-d0db-11ea-9aef-35ccf585a8b0.png)

#### Any log messages from files that end in `.log` or `.txt`? What are the last 100 log messages from the server console?
NONE

#### What plugins and what versions of those plugins are you running?
Testing with no plugins.

This has recently been a growing issue, players would be frozen for ages and have to leave.

**Comment by hakusaro** [comment]
You should turn on debug logs in the config file, reproduce the issue, and send those in.

**Comment by moisterrific** [comment]
Might also be caused by network lag, at least I've seen it happening a few times on my private server back when I hosted.
