### ISSUE TITLE
Chat and consolecommands flood console

### ISSUE THREAD

**Issue by StinkyVoet** [Pryaxis/TShock#2116]
* TShock version: 4.4.0-pre12

#### Reproduction steps (if applicable)?

1. Make sure the server is turned on
2. Chat or type something in console

#### Any screenshots?

![image](https://user-images.githubusercontent.com/44726280/92236942-c2548900-eeb6-11ea-8596-3fb7bba5c3e5.png)

#### Any log messages from files that end in `.log` or `.txt`? What are the last 100 log messages from the server console?

I do not think log messages are very useful in this case. Let me know otherwise, so I can add it later!

#### What plugins and what versions of those plugins are you running?

Just TShock 4.4.0-pre12

**Comment by bartico6** [comment]
Whatever you're using as the terminal/consoleviewer doesn't support console window titles and writes them to the log instead it seems... ?  
EDIT: What I meant to say is that I'm not sure this is a tShock issue per se, it's likely a problem with your shared host/host environment.

**Comment by StinkyVoet** [comment]
Alright, thanks! I'll let the WISP Panel devs know!

**Comment by QuiCM** [comment]
Seems like a non-tShock issue. Please reopen if it turns out to be something on our side :)
