### ISSUE TITLE
Add a /music toggle to switch between normal and Otherworld soundtracks

### ISSUE THREAD

**Issue by Kojirremer** [Pryaxis/TShock#2121]
Once you visit a drunk world/special seed, the party girl permanently gains a new menu option, **_Music_**, which toggles between the vanilla soundtrack and Terraria Otherworld's. The problem is that the selected OST reverts to the map's default (vanilla for normal maps, Otherworld's for special seeds) whenever you reconnect, and having to search for the party girl every time you come back is a bit of a pain.

Would it be possible to add a /music command to TShock as a quick music toggle? Just a minor QoL improvement to avoid having to search for the party girl every single time you enter a server.

The game remembering your OST selection would be great, but AFAIK, that's a vanilla kirk. Just being able to switch soundtracks on the fly would be great already.

Thanks for reading.

**Comment by Strawparrot** [comment]
I would personally change the command name to something like /togglemusic or /drunk, but otherwise a great suggestion! I support this.

**Comment by Kojirremer** [comment]
> I would personally change the command name to something like /togglemusic or /drunk, but otherwise a great suggestion! I support this.

**_/togglemusic_**, I agree. _**/drunk**_ would probably lead to confusion, since the first thing one would think that command does is to turn on the world's flag that indicates that it is a drunk one (which may be worth suggesting as well).

**Comment by Quinci135** [comment]
The value `swapMusic` would have to change to true, and that only changes if your player toggles it with the party girl, you enter the main menu (sets it false so you hear normal music there), or you toggle it in your game's config.json file (set `UnlockMusicSwap` true or false).

**Comment by QuiCM** [comment]
Quinci has the long and short of it. Can't toggle this from the server at this time, unfortunately
