### ISSUE TITLE
UpdateManager warning

### ISSUE THREAD

**Issue by Ne0shka** [Pryaxis/TShock#2127]
* TShock version:  v4.4.0-pre12

#### Reproduction steps

1. Launch the server
2. To wait
3. Get a message in the console:

```
UpdateManager warning: Error: SecureChannelFailure (The authentication or decryption has failed.)
        -> The authentication or decryption has failed.
        -> The authentication or decryption has failed.
        -> The authentication or decryption has failed.
Retrying in 5 minutes.
```

**Comment by pluto00987** [comment]
Guessing this might have to do with the recent release of Terraria 1.4.1?

**Comment by QuiCM** [comment]
Likely to do with our recent move of server infrastructure. Message can be safely ignored but I'll check what we can do to stop it showing up :)

**Comment by hakusaro** [comment]
What OS and .NET framework are you on?

On October 14, 2020, GitHub <notifications@github.com> wrote:
> Likely to do with our recent move of server infrastructure. Message
> can be safely ignored but I'll check what we can do to stop it showing

> up :)
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Pryaxis/TShock/issues/2127#issuecomment-708429896>,

or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAECBJ5GQESTR5VJDHNMW4DSKWWRHANCNFSM4SK7OJ6A>.

**Comment by Ne0shka** [comment]
> Guessing this might have to do with the recent release of Terraria 1.4.1?

No, 1.4.1 came out later than the detected bug like

> Likely to do with our recent move of server infrastructure. Message can be safely ignored but I'll check what we can do to stop it showing up :)

The problem is relevant on this version

> What OS and .NET framework are you on?

Linux hostname 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1)

**Comment by Ne0shka** [comment]
On latest prerelease problem is not relevant.

**Comment by Ne0shka** [comment]
Mistaken. The problem also exists on the last prerelease.

**Comment by Ne0shka** [comment]
```
> curl https://update.tshock.co/latest/
{
  "version": "4.3.26",
  "changes": "TShock v4.3.26" 
}
```

**Comment by cainiaocome** [comment]
How can I disable update and update check totally? I don't feel like any software to check update or update on my computer. If something works I never want to change it. Thanks very much.

**Comment by bartico6** [comment]
This is worthy of a new issue, but you would have to modify the server to change this behaviour:

Easiest way would be to remove the contents of the constructor in this file (https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/UpdateManager.cs#L47) and recompile.
