### ISSUE TITLE
Latest pre-release tag seems wrong

### ISSUE THREAD

**Issue by tieonlinux** [Pryaxis/TShock#2132]
Hello,

Latest release's tag is [v4.40-pre13](https://github.com/Pryaxis/TShock/tree/v4.40-pre13) i guess it should be tagged `v4.4.0-pre13` instead.
Notice the 4.**40** vs 4.**4**.0 diff

Regards

**Comment by QuiCM** [comment]
Oops. Thanks, will get it fixed up in the morning

**Comment by QuiCM** [comment]
Fixed - tag 4.40 has been removed and replaced with 4.4.0.
Thanks :)
