### ISSUE TITLE
Group prefixes do not show in chat

### ISSUE THREAD

**Issue by Crdguy** [Pryaxis/TShock#2134]
* TShock version: 4.4.0 Pre-release 13

Updated to the newest pre-release, spoke in chat and realised prefixes appear to be absent in chat. Was working fine last version on my server. Any help on the issue would be appreciated. Cheers

#### Reproduction steps (if applicable)?

1. Add a prefix to a group you are in using /group set prefix 
2. Speak in chat
3. Observe the set prefix is not used in chat

#### Any screenshots?

![image](https://user-images.githubusercontent.com/30349278/96282011-0a94ba00-0fd2-11eb-9e46-b1f667fb60e8.png)
Context: there is no group prefix after me running the following command: /group set prefix Captain "Captain "

#### Any log messages from files that end in `.log` or `.txt`? What are the last 100 log messages from the server console?

[2020-10-16_16-46-47.log](https://github.com/Pryaxis/TShock/files/5392998/2020-10-16_16-46-47.log)

**Comment by QuiCM** [comment]
![Terraria_2020-11-13_19-06-54](https://user-images.githubusercontent.com/2648373/99047003-796e2e80-25e3-11eb-9f16-77024f771aaf.png)
Prefixes working fine for me. You may need to have a look at your chat format (and please note that ChatOverHeads causes problems with some parts of the formatting that you may need to work around)
