### ISSUE TITLE
-difficulty command-line parameter

### ISSUE THREAD

**Issue by CansecoDev** [Pryaxis/TShock#2177]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to create a world automatically with a specific difficulty setting.

**Describe the solution you'd like**
Implement a new command-line parameter: `-difficulty {difficulty number}`
- It should be tied with the `-autocreate` parameter, and ignore it in case of not having it.
- It should use one of these 4 possible values: `0` (classic), `1` (expert), `2` (master) or `3` (journey).

**Describe alternatives you've considered**
Workarounds with plugins, but since this is already managed by the wizard, I believe it should be easy to implement as a command-line parameter.

**Additional context**
This is useful for servers that generate new worlds periodically in an automated manner.

**Comment by MrConorAE** [comment]
Suggestion if I may:
Make Journey mode `0`, because it is the "odd one out" of the options - then `1` (classic), `2` (expert), and `3` (master).
Just an idea...

**Comment by bartico6** [comment]
@MrConorAE 
```csharp
		public static Dictionary<int, GameModeData> RegisterdGameModes = new Dictionary<int, GameModeData>
		{
			{
				0,
				GameModeData.NormalMode
			},
			{
				1,
				GameModeData.ExpertMode
			},
			{
				2,
				GameModeData.MasterMode
			},
			{
				3,
				GameModeData.CreativeMode
			}
		};
```
In order to be consistent with the base game, if this is implemented, the gamemode IDs **will** most likely follow the order in the game code.

**Comment by MrConorAE** [comment]
@bartico6 Ah, that makes sense. I wasn't aware those values already were implemented, so I absolutely agree that we should/must follow that.

**Comment by QuiCM** [comment]
PR pending in draft over in the TerrariaAPI-Server repo. Needs testing

**Comment by hakusaro** [comment]
I believe this is no longer relevant because it's been released as fixed. Please reopen if this isn't the case!
