### ISSUE TITLE
REST API always returning HTTP 200

### ISSUE THREAD

**Issue by Syngeo** [Pryaxis/TShock#2189]
* TShock version: 4.4.0.0

When calling the REST API, every request returns HTTP 200 even if the request itself failed (a quick way to confirm is to call **http://TSHOCK_REST_SERVER:/tokentest?token=**, keep the token parameter blank).

I'm not sure if this was done for a specific reason, but I've been trying to use a Python client to access my own local server and I need to parse the JSON from the response just to get the status code. It's not too big a deal, but it would significantly simplify error handling and be more intuitive to learn for people who are used to working with status codes directly.

**Source:**
https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/Rest/Rest.cs#L275

This hopefully shouldn't break for people if they're parsing the status from the response anyway, but maybe it could be a significant change for other people. What are your thoughts on this?

**Example screenshot:**
![image](https://user-images.githubusercontent.com/18536210/102720843-af8f8400-42ee-11eb-84e6-7cde4bacbdba.png)

**Comment by QuiCM** [comment]
Thanks - I've implemented this in 1b4dc53. `RestObject`s returned by the `ProcessRequest` method will now have their status value respected in the response

**Comment by Syngeo** [comment]
Great, cheers for that 👍
