### ISSUE TITLE
REST API Token creation returning error instead of token

### ISSUE THREAD

**Issue by SuperMechaCow** [Pryaxis/TShock#2190]
* TShock version: 4.4.0.0 (stock, no addons. Running with mono on a RPi 4)
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. Create a stock server and connect.
2. Authorize self as admin
2. Navigate to http://ip:restport/v2/token/create?username=user&password=pass
2. Returns status code 200, but JSON returned is status code 403, regardless of the validity of the credentials
3. Continuing to try the login results in the error:
"TextLog: ERROR: A REST login from XXX.XXX.XXX.XXX was blocked as it currently has 5 tokens"

There's not much more information to give than that. It seems to be generating a token, but returning as if it was an error.

**Comment by QuiCM** [comment]
Make sure your user has the permission `tshock.rest.useapi`. Without this permission they will be unable to create tokens and you'll get a 403 response.
As of 1b4dc53, the correct HTTP status code will be returned (should match the JSON status code)

**Comment by SuperMechaCow** [comment]
User was not in superadmin group even though I added them twice. Probably user error.

Thank you!
