### ISSUE TITLE
Replace current Godmode (Healmode) with Journey mode Godmode

### ISSUE THREAD

**Issue by tlworks** [Pryaxis/TShock#2209]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem.
**Describe the solution you'd like**
Instead of continue using the inconsistent annoying healmode, implement actual journey mode godmode.
**Describe alternatives you've considered**
No alternative solution.
**Additional context**
No, it's not impossible because Quake already managed to do but refuses to share it.

**Comment by hakusaro** [comment]
>No, it's not impossible because Quake already managed to do but refuses to share it.

@bartico6 I'm assigning this issue to you

**Comment by hakusaro** [comment]
@bartico6 I will pay you $1 in BTC if you do this

**Comment by 0x3fcf1bbd** [comment]
```
private static void ToggleCreativeGodMode(CommandArgs args)
{
    TSPlayer tSPlayer;
    if (args.Parameters.Count > 0)
    {
        if (!args.Player.HasPermission(Permissions.godmodeother))
        {
            args.Player.SendErrorMessage("You do not have permission to god mode another player.");
            return;
        }
        List<TSPlayer> list = TSPlayer.FindByNameOrID(string.Join(" ", args.Parameters));
        if (list.Count == 0)
        {
            args.Player.SendErrorMessage("Invalid player!");
            return;
        }
        if (list.Count > 1)
        {
            args.Player.SendMultipleMatchError(list.Select((TSPlayer p) => p.Name));
            return;
        }
        tSPlayer = list[0];
    }
    else
    {
        if (!args.Player.RealPlayer)
        {
            args.Player.SendErrorMessage("You can't god mode a non player!");
            return;
        }
        tSPlayer = args.Player;
    }
    CreativePowers.GodmodePower godmodePower = CreativePowerManager.Instance.GetPower<CreativePowers.GodmodePower>();
    bool state = !godmodePower.IsEnabledForPlayer(tSPlayer.Index);
    godmodePower.SetEnabledState(tSPlayer.Index, state);
    if (tSPlayer == args.Player)
    {
        args.Player.SendMessage(string.Format("You are {0} in god mode.", state ? "now" : "no longer"), state ? Color.Green : Color.Yellow);
        return;
    }
    args.Player.SendMessage(string.Format("{0} is {1} in god mode.", tSPlayer.Name, state ? "now" : "no longer"), state ? Color.Green : Color.Yellow);
    tSPlayer.SendMessage(string.Format("You are {0} in god mode.", state ? "now" : "no longer"), state ? Color.Green : Color.Yellow);
}
```

**Comment by bartico6** [comment]
Appears to be correct, you can use this xd

**Comment by hakusaro** [comment]
@0x3fcf1bbd hi, random person! Can you send me a an email (argo@hey.com) so that I can get you to sign an agreement permitting us to use this code?

**Comment by 0x3fcf1bbd** [comment]
This code is for the most part not mine, as it is a copy of the current TShock godmode command. The only additions are the creative parts, as well as the different colors depending on the result on the feedback messages.
I would like to relinquish all and any credits/rights I possibly have over my part of the code. 
You may consider it public domain, therefore you are free to use/modify/copy/anything it.
Tbf I don't want to deal with agreements and copyright things. Just use the code.

**Comment by bartico6** [comment]
I don't remember if the SetEnabledState call also does networking - if it doesn't, you might need to update the godmode state to everyone. Other than that, LGTM if this was a PR.

**Comment by 0x3fcf1bbd** [comment]
It does networking.
You can decompile and check this yourself if you have any doubts.

**Comment by bartico6** [comment]
I don't doubt you at all, I was just unsure if the method does networking, but I'm glad you knew off the top of your head :)

**Comment by QuiCM** [comment]
This was added in 4.5.1 :)
