### ISSUE TITLE
Can i play on pc and mobile?

### ISSUE THREAD

**Issue by Timtaran** [Pryaxis/TShock#2225]
Mobile version - 1.4.0.2.5
PC version - 1.4.1.2

**Comment by csmir** [comment]
TShock does not support mobile Terraria. However: in case you have enough knowledge of how packets work, you can make them match on joining the server with a plugin. This gives you the ability to join on both mobile & PC. The main packet you want to focus on is SendTileRect <> SendTileSquare

**Comment by Timtaran** [comment]
._. Okay... I'm playing on tshock server with my friend on mobile.

**Comment by bartico6** [comment]
to reiterate: tshock can be used with mobile servers by downgrading several versions but we don't provide support for it and we won't officially release tools making that easier.

**Comment by Timtaran** [comment]
Okay
