### ISSUE TITLE
Remove Frozen and Stoned from Disable

### ISSUE THREAD

**Issue by Arthri** [Pryaxis/TShock#2231]
**Is your feature request related to a problem? Please describe.**
It sort of is, stoned deals damage to you on stone.

**Describe the solution you'd like**
Remove Stoned and Frozen. Some accessories even negate Stoned and Frozen and, additionally, Stoned causes side-effects.

The 3rd debuff Webbed, in contrast, can't be negated and doesn't cause side effects. It also stops the player, freezing them in the air, unlike Stoned and Frozen.

Contrary to the [wiki](https://terraria.gamepedia.com/Webbed), you **can not** use healing items while webbed.

**Describe alternatives you've considered**
Well, Frozen doesn't necessarily need to be removed. It's just that Webbed makes it not so useful.

**Additional context**
N/A

**Comment by Kojirremer** [comment]
Agreed. Webbed makes the other two obsolete, and is the only one of the three that can't be negated without cheats.

**Comment by QuiCM** [comment]
Added in e23509d. Will be part of the next release

**Comment by ATFGK** [comment]
No, because it won't stop players from using items

**Comment by csmir** [comment]
Yes it does? The change has already been implemented in preparation for next release and the side-effects have been considered.

**Comment by bartico6** [comment]
> While affected by the debuff, the player will be unable to use any items except for healing items.

One could argue that they can heal while disabled but the server will ignore their actions anyway.

**Comment by ATFGK** [comment]
Although the server can be ignored, Stoned is an excellent warning

**Comment by Kojirremer** [comment]
> 
> 
> Although the server can be ignored, Stoned is an excellent warning

The same as webbed, but with two less buff slots taken and avoiding some kirks specific of being petrified.

**Comment by ATFGK** [comment]
I see. That's great

**Comment by Arthri** [comment]
> > While affected by the debuff, the player will be unable to use any items except for healing items.
> 
> One could argue that they can heal while disabled but the server will ignore their actions anyway.

> No, because it won't stop players from using items

The wiki is outdated. As of 1.4.1.2, you can't use either healing items or normal items

**Comment by bartico6** [comment]
In that case I retract my statement :^)
