### ISSUE TITLE
1.4.2 Support

### ISSUE THREAD

**Issue by lemonlim3** [Pryaxis/TShock#2257]
Apparently there was another update - can no longer connect because of version mismatch :(

**Comment by ladyofthelake51** [comment]
Yeah, indeed there is a new update. Hopefully there will be a new release soon...

**Comment by ghost** [comment]
i hope they release 1.4.2 on this week

**Comment by 0x3fcf1bbd** [comment]
One thing you can do is to patch OTAPI.dll yourself, at Terraria.MessageBuffer.GetData, case 1 of the switch, find the line looking like this : `this.reader.ReadString() == "Terraria" + 234`, and set it to 235. Using a tool such as dnSpy.
Not the best solution, but it works so...

**Comment by butchpaolom** [comment]
> One thing you can do is to patch OTAPI.dll yourself, at Terraria.MessageBuffer.GetData, case 1 of the switch, find the line looking like this : `this.reader.ReadString() == "Terraria" + 234`, and set it to 235. Using a tool such as dnSpy.
> Not the best solution, but it works so...

can you provide modified dll file?

**Comment by AlexeyZavar** [comment]
Try this: [removed]

**Comment by QuiCM** [comment]
Official binaries will be provided when the team has time to do so
