### ISSUE TITLE
Handle PlayerChatEventArgs.Handled

### ISSUE THREAD

**Issue by Arthri** [Pryaxis/TShock#2260]
**Is your feature request related to a problem? Please describe.**
PlayerChatEventArgs inherits from HandledEventArgs but setting Handled to true does nothing because it's not handled.
[TShock.OnChat, Invokes void method](https://github.com/Pryaxis/TShock/blob/b4789607f60bf20b593ff7efa354f725b3956e78/TShockAPI/TShock.cs#L1347)
[PlayerHooks.OnPlayerChat, Handled is ignored](https://github.com/Pryaxis/TShock/blob/b4789607f60bf20b593ff7efa354f725b3956e78/TShockAPI/Hooks/PlayerHooks.cs#L452)

**Describe the solution you'd like**
Handled is handled and messages can be blocked

**Describe alternatives you've considered**
A hook where chat messages can be blocked, but still processed by TShock

**Additional context**
N/A

**Comment by QuiCM** [comment]
This sounds like a reasonable request.
Given that `ServerChatEventArgs.Handled = true` prevents processing of the message, it would make sense that `PlayerChatEventArgs.Handled = true` should similarly prevent the message being sent.

We can make `OnPlayerChat` return the boolean value of `Handled` and adjust TShock.cs like so:
```csharp
1347: bool cancelChat = PlayerHooks.OnPlayerChat(tsplr, args.Text, ref text);
1348: if (cancelChat)
      {
          return;
      }
```

**Comment by QuiCM** [comment]
Added in 784a75b
