### ISSUE TITLE
Display TicketNumber in Ban Message

### ISSUE THREAD

**Issue by bippity** [Pryaxis/TShock#2274]
**Is your feature request related to a problem? Please describe.**

With the new ban system, by default/quick-ban, the server will add 3 entries into the database, 1 for each identifier (IP, UUID, account).
To unban that player, an admin would need to run `ban del <ticket number>` for each of those tickets. Assuming the admin only knows the player's name and the server has a moderate amount of entries/banned players, this could be daunting for the admin to navigate through the ban list to find the correct tickets. And if the server migrated over from the old ban system, only the IP and UUID info would be preserved, the username would be missing. (Example screenshot attached below)

**Describe the solution you'd like**

Include the Ticket Number when sending the error message to the client.
Instead of just "You are banned: [reason]", it could be "#[ticket number] You are banned: [reason]".
This would allow the player to tell the admin which specific ticket is being applied and would help the admin narrow down which tickets to look for.

**Describe alternatives you've considered**

Admin can ask/guide the player to find their IP and UUID, but would still need to search through the ban list to find the correct ticket; this can be made easier by modifying the database directly, but it would require some SQL knowledge to perform queries and must be performed outside the game.

**Additional context**
_Screenshot of user bans from 2016:_
![](https://user-images.githubusercontent.com/4565052/114663661-475f1680-9cc0-11eb-9947-f29fbeb28f2f.png)
* Updating a web-based[ ban viewer](https://bippityserver.com/banviewer/) (might make it open source in the near future?) and I've changed it to require a ticket number instead of the player name, it would then find the other related tickets.

**Comment by QuiCM** [comment]
This sounds reasonable. I'll look at implementing in the next few days, time permitting

**Comment by bippity** [comment]
Yay!
e80f0bfda5ea8e846517ee1f295ac18bcac3fb0c
