### ISSUE TITLE
Add a folder for logs by default

### ISSUE THREAD

**Issue by moisterrific** [Pryaxis/TShock#2305]
**Is your feature request related to a problem? Please describe.**
It's annoying when log files fill up the tshock folder, esp when that folder is full of other important files users can write to, while logs are mostly for reading. 

**Describe the solution you'd like**
change `LogPath` in config from `tshock` to `logs` and generate a folder named logs (idk how that would work bc on my end I manually made a folder named logs)

**Describe alternatives you've considered**
no idea

**Additional context**
should look something like this

![image](https://user-images.githubusercontent.com/57187883/118267393-ffcbd600-b489-11eb-921d-76c409ba5648.png)

**Comment by steviegt6** [comment]
Should this not be marked as closed now?
