### ISSUE TITLE
Support mobile Terraria 1.4.0.5

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#2341]
Since 1.4.0.5 is on 1.4, it would be trivial for us to maintain a version of TShock compatible with mobile and desktop 1.4.0.5.

**Comment by moisterrific** [comment]
Would this mobile version receive new features from PC TShock? Like the most up to date anti-cheat checks, fixes, security updates, etc.?

**Comment by JoseFcoRosado** [comment]
I'm in.
Ive been hosting Mobile worlds since 1.3 released.
Anything you need, count me in.

**Comment by EMREOYUN** [comment]
> Since 1.4.0.5 is on 1.4, it would be trivial for us to maintain a version of TShock compatible with mobile and desktop 1.4.0.5.

I tried some compiling with Upcoming Mobile OTAPI but it will not work current Mobile TShock branch because new OTAPI works on .NET 5 instead all other TShock and OTAPI Patcher works on .NET version 4

**Comment by sgkoishi** [comment]
No longer valid, should be closed.
