### ISSUE TITLE
Changing weapon Usetime

### ISSUE THREAD

**Issue by ronnoc245** [Pryaxis/TShock#2376]
TShock version:4.5.4

1. Load into my server running Tshock.
2. Use a command to change the Usetime of a weapon to zero.
3. The server inflicts me with the webbed debuff.

It's probably got something to do with server security, but I can't seem to figure out how to disable it.
Honestly idk if this is event he right place to report this.

**Comment by Quinci135** [comment]
Does the usetime 0 weapon shoot projectiles? 

If your current group is one with elevated permissions/it's just you and you aren't using this for other players, you can ignore projectile shoot/creation/generation rate thresholds by adding `tshock.ignore.projectile` to your group.

**Comment by ronnoc245** [comment]
Thank you so much :D
