### ISSUE TITLE
Dont running on linux mint Ulyana

### ISSUE THREAD

**Issue by blixer-debug** [Pryaxis/TShock#2395]
* TShock version:I don't know i remove TShock
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. Some step
2. Some other step
3. Some bigger step
4. This is the problem

#### Any stack traces or error messages (if known)?

```
PUT SUPER LONG ERROR MESSAGES IN THE TICK MARKS
```

#### What plugins and what versions of those plugins are you running?

If I didn't provide any logs this issue, please close my issue immediately. I'm sorry for the inconvenience.

**Comment by blixer-debug** [comment]
Trying run TShock from root shell EPIC FAIL backtraces,errors,logs my cleaner removes .log files

**Comment by hakusaro** [comment]
Don’t run TShock as root. Please clearly state what you were trying to accomplish and what went wrong. If you need help in another language please tell us. Please post in your original language. Do not use a translator app to translate to English.
