### ISSUE TITLE
an error occurs when entering the Hardmode

### ISSUE THREAD

**Issue by ATFGK** [Pryaxis/TShock#2425]
When the map is small, such as skyblock, an error occurs when entering the Hardmode:

Hardmode is now on.
: Unhandled exception
System.UnhandledExceptionEventArgs
[Server API] Error ===================================================================================
[Server API] Error An unhandled exception has occured in TSAPI, and a crash report will be generated
[Server API] Error Generating a crash report, please wait...
[Server API] Error Could not generate a crash report.
[Server API] Error Please upload the crash file and report it at http://tshock.co/
[Server API] Error The process will terminate.
[Server API] Error ===================================================================================
================
2021/8/13 20:32:32: Unhandled Exception
Thread: 8 []
Culture: zh-CN
Exception: System.IndexOutOfRangeException: 索引超出了数组界限。
   在 OTAPI.Tile.DefaultTileCollection.get_Item(Int32 x, Int32 y)
   在 Terraria.WorldGen.smCallBack(Object threadContext)
   在 System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by csmir** [comment]
It appears this is an error sourced from Terraria itself. @bartico6 can provide better feedback on the error string, as he knows the games core better. This could be patched by doing checks for what OTAPI tries to match before execution?

**Comment by Moneylover3246** [comment]
This is happening because while terraria generates the hallow/evil during hardmode gen, its trying to get a tile cord thats out of bounds. If the world you're using isn't a vanilla size, it could be because the tile bounds weren't properly modified

**Comment by csmir** [comment]
Are the tile bounds getable? If so, can we check for them being vanilla? This should be doable by a simple array of vanilla world sizes and a getter for the size of the current world

**Comment by Moneylover3246** [comment]
Main.maxTilesX/Y

**Comment by bartico6** [comment]
Generating hardmode happens on another thread. If the `ITileCollection` in Main is modified, or the boundaries (Main.maxTilesX/Y) during that time, this may happen.

Please say when and what causes this error to occur. Is it consistent?

**Comment by ATFGK** [comment]
It's fixed
