### ISSUE TITLE
Function of Luck

### ISSUE THREAD

**Issue by iamyou** [Pryaxis/TShock#2449]
A command to query or modify luck

**Comment by moisterrific** [comment]
Unfortunately modifying luck is not possible. Something like this was asked before on the discord server. 

![085C279F-EAB2-42CE-8DC7-922AF63F5F78](https://user-images.githubusercontent.com/57187883/133080731-0281fd62-a2e3-4de1-93be-0d2a4ebe5c0a.jpeg)

I’m not exactly sure about checking current luck though, I thought you can already do that via the Wizard NPC?

**Comment by bartico6** [comment]
You can check the luck by simply retrieving the luck value of the player object, since it should be up to date.
