### ISSUE TITLE
CI/CD Leaves TShock files in root directory

### ISSUE THREAD

**Issue by Arthri** [Pryaxis/TShock#2476]
This is the [line](https://github.com/Pryaxis/TShock/blob/03c20a98048ee7493d58140c0b8458a3d4399484/.github/workflows/build.yml#L42) responsible for copying `TShockAPI.dll`, however there's no equivalent one for other important TShock files. Especially the documentation file, since IDEs commonly need them to be in the same place to load them

* TShock version: <4.5.5
* TShock build number (if known): N/A

#### Reproduction steps (if applicable)?

1. Download TShock
2. Unzip TShock
3. `TShockAPI.xml`, `TShockAPI.pdb`, etc., is in the server root directory not `ServerPlugins` directory

#### Any stack traces or error messages (if known)?

N/A

#### Any screenshots?

![image](https://user-images.githubusercontent.com/41360489/137472513-18c398c6-f2c8-481d-bbee-5282b32c0582.png)

#### Any log messages from files that end in `.log` or `.txt`? What are the last 100 log messages from the server console?

N/A

#### What plugins and what versions of those plugins are you running?

N/A

**Comment by sgkoishi** [comment]
No longer valid, should be closed.
