### ISSUE TITLE
Config option for allowing the toggling of gem locks on protected regions not working

### ISSUE THREAD

**Issue by Kojirremer** [Pryaxis/TShock#2485]
* TShock version: 4.5.5.0

Reproduction steps:

1. Set "RegionProtectGemLocks" to false in config file.
2. Start server and place a gem lock wired to a mechanism within a protected region.
3. Get a player without build access to the region to try and toggle the mechanism by placing a large gem.
4. The gem will be consumed without anything happening. No gem on the lock, no sent signal, not even the toggle sound. The gem just vanishes in silence. No error is given to the player either.

Info from Durtle:
https://github.com/Pryaxis/TShock/blob/40a979186120e4204bb4dbf2da26b371f2f1ec8e/TShockAPI/Bouncer.cs#L1925
"afaict the check doesnt check if the config option is off
it uses build permissions"

**Comment by hakusaro** [comment]
@Kojirremer this should be resolved in the latest dev build. Please let me know if it's not!

**Comment by Kojirremer** [comment]
> @Kojirremer this should be resolved in the latest dev build. Please let me know if it's not!

Yes, just tested with the same setup as before and it's working as intended now. Thanks a lot.
