### ISSUE TITLE
Server boots players with error “Added buff to Wall Creeper NPC abnormally.”

### ISSUE THREAD

**Issue by phyd3aux** [Pryaxis/TShock#2514]
* TShock version: 4.5.9 and 4.5.10
* TShock build number (if known): Don't know.

#### Reproduction steps (if applicable)?

1. Hit a creature with a Tentacle Spike
2. Server boots with message “Added buff to Wall Creeper NPC abnormally.”

#### Any stack traces or error messages (if known)?
See server logs.

#### Any screenshots?
![Screen Shot 2021-11-27 at 1 53 24 am](https://user-images.githubusercontent.com/71910044/143599090-198eec15-71d1-41ec-8491-6854648d4383.png)

The problem seems to be linked to the Tentacle Spike. Wall Creepers when hit with the spike immediately result in the boot. The problem affects all players on the server (i.e., both of us :)). Other creatures were tried too with similar effect (although a slime didn't cause the bug). Wall Creepers seem to do it reliably. See BugReport_1.log for the details.

After these logs were produced we successfully played for 2 or so hours (using weapons other than the tentacle spike).

This only started with version 4.5.9 (Terraria version 1.4.3.2). Everything was fine in earlier versions.

Oh, if it's relevant, the world is using the new special seed “theconstant”.

#### Any log messages from files that end in `.log` or `.txt`? What are the last 100 log messages from the server console?
- Server version 4.5.9: [BugReport_1.log](https://github.com/Pryaxis/TShock/files/7609452/BugReport_1.log)
- Server version 4.5.10: [BugReport_2.log](https://github.com/Pryaxis/TShock/files/7609454/BugReport_2.log)

See above for context. Problem appears to be somehow related to the tentacle spike.

#### What plugins and what versions of those plugins are you running?

No plugins were running. Just base tshock.

**Comment by Arthri** [comment]
Linked #2513

**Comment by hakusaro** [comment]
Fixed in #2513
