### ISSUE TITLE
TShock 4.5.12 - Tentacle Spike - Added buff to NPC abnormally - Kicked

### ISSUE THREAD

**Issue by Exeden** [Pryaxis/TShock#2539]
* TShock version: 4.5.12

1. Attack mob with Tentacle Spike
2. User gets kicked with message 'Added buff to NPC abnormally'

![image](https://user-images.githubusercontent.com/10290610/145934920-6fde672c-f43f-4a91-9128-fb34eb5b9468.png)

**Comment by Arthri** [comment]
Can you please turn on `DebugLogs` in the config then reproduce this? Edit the original issue with the log file so others can know what's wrong.

I'm unable to reproduce this myself

**Comment by Exeden** [comment]
Sorry for wasting everyone's time.  Server was at 4.5.11, and when updated to 4.5.12 issue resolved.
