### ISSUE TITLE
Coins picked up by enemies do not drop when killed

### ISSUE THREAD

**Issue by dscyrux** [Pryaxis/TShock#2546]
* TShock version: 4.5.12
* TShock build number (if known): f3b1a84

#### Reproduction steps (if applicable)?

1. Drop a coin on enemy
2. Enemy picks up coin
3. Kill enemy
4. Enemy drops default money amount, picked-up coin is consumed

#1864 seems to have popped up again.

**Comment by pcider** [comment]
I have experienced this bug before on TShock 4.5.5 but I didn't report it because I thought it was intended behaviour
