### ISSUE TITLE
Question about item banning

### ISSUE THREAD

**Issue by ghost** [Pryaxis/TShock#2554]
Hello,

I have a question on the item ban feature. What is the actual behavior tied to an item ban? For example, does it kick the person using the item? Does it appear in their inventory, but can't be used? Or does it disappear from their inventory entirely while on the server?

If context helps, I'm wondering if I can use it to limit players bringing in high progression items to a low progression world without having to resort to so draconian a feature as server-side characters. If there's also a feature aside from item banning that might help accomplish this, I'd be grateful if you could point me in the right direction.

Thank you.

**Comment by Kojirremer** [comment]
For banned items, people who doesn't have the required permissions **can** carry them within their inventory. However, trying to hold, select in the hotbar, equip, or use the banned item will disable the player while the item is held/equipped; they will also receive a constant warning about the banned item causing their current state.
This means the player will have some immovilizing debuffs constantly applied to them, and the server will ignore their inputs and stop providing map info while the player remains disabled. This is not perfect, though. Quick-action buttons can bypass some of these bans.
IIRR, you **can** modify an option in the config file so banned items trigger a kick to the offender instead, if you so desire.

**Comment by ghost** [comment]
I'd rather a warning and the item be disabled than a kick... and even if it's not perfect, it sounds like it's at least better than having to choose between nothing and SSC. Thank you!
