### ISSUE TITLE
New Version of terraria TShock Needs A Update

### ISSUE THREAD

**Issue by GamerKing122** [Pryaxis/TShock#2573]
* TShock version:TShock4.5.13_Terraria1.4.3.2
* TShock build number:Release

#### Reproduction steps 
1. start server
2. try joining server
3. error terraria version doesn't match server

![image](https://user-images.githubusercontent.com/27757241/155668203-d453f3eb-c917-4e75-a27c-f03f995b1fc0.png)

![image](https://user-images.githubusercontent.com/27757241/155668389-77c69cdb-1526-4140-941a-3be31143dee5.png)

**Comment by Arthri** [comment]
Related: https://github.com/Pryaxis/TSAPI/pull/203

**Comment by hakusaro** [comment]
See: https://github.com/Pryaxis/TShock/releases/tag/v4.5.14
