### ISSUE TITLE
Players getting kicked when using bunny cannon with quick actions

### ISSUE THREAD

**Issue by Kojirremer** [Pryaxis/TShock#2616]
* TShock version: 4.5.17.0

#### Reproduction steps:

1. Play with a character without any elevated permissions, but that can use the bunny cannon and explosive bunnies
2. Try to shoot the bunny cannon using the quick action button without having exploding bunnies in the hotbar
3. The cannon will shoot as normal, the proyectile will fly as usual, but...
4. If the proyectile didn't hit anything while in the air, as soon as the explosive bunny lands and turns into a creature, the player gets kicked for critter not matching item being used.

#### Any stack traces or error messages?

```
2022-04-15 01:26:59 - TSPlayer: INFO: Kicked Shredder for : 'Released critter was not from its item.'
2022-04-15 01:26:59 - Utils: INFO: Broadcast: Shredder was force kicked for 'released critter was not from its item.'
2022-04-15 01:26:59 - Utils: INFO: Broadcast: Shredder has left.
2022-04-15 01:26:59 - TextLog: INFO: Shredder disconnected.
```
My guess is that since the latest Terraria updates changed the behavior of explosive bunnies to now being critters instead of proyectiles once they land, and usually critters can't be released via the quick action extra slot that appears on the hotbar while using quick actions, they are being caught as a cheat.
When I tried using the explosive bunnies directly on the bunny cannon, releasing them, or using quick actions with them in the hotbar to shoot I did not get kicked. It seems it only happens when the bunnies are not in the hotbar.

**Comment by swinzy** [comment]
@hakusaro I'm using version 5.2.0.0 and facing the same issue. Any idea? Even when I'm holding the rabbit in my hand it will still kick me.
