### ISSUE TITLE
Setting a /tempgroup a time too far into the future results in command failure

### ISSUE THREAD

**Issue by JordanDi123** [Pryaxis/TShock#2625]
* TShock version: 4.5.17
* TShock build number (if known): Unknown but it's the release here: https://github.com/Pryaxis/TShock/releases/tag/v4.5.17

#### Reproduction steps (if applicable)?

1. Type `/tempgroup <username> <group> 24d` into the chat/console.
2. Type `/tempgroup <username> <group> 25d` into the chat/console.
3. An error should be throw when you execute the second command.

#### Any stack traces or error messages (if known)?

```
2022-05-07 18:24:12 - Command: ERROR: System.ArgumentException: Invalid value '-2134967296' for parameter 'interval'.
   at System.Timers.Timer..ctor(Double interval)
   at TShockAPI.Commands.TempGroup(CommandArgs args)
   at TShockAPI.Command.Run(String msg, Boolean silent, TSPlayer ply, List`1 parms)
```

#### Any screenshots?

![image](https://user-images.githubusercontent.com/24500399/167273996-c01cfae7-feae-46d8-96c0-043e894d83b0.png)

#### Any log messages from files that end in `.log` or `.txt`? What are the last 100 log messages from the server console?

[2022-05-07_18-23-20.log](https://github.com/Pryaxis/TShock/files/8646049/2022-05-07_18-23-20.log)

#### What plugins and what versions of those plugins are you running?
No plugins other than the TShockAPI.dll itself.

Please let me know if you require any further information. I'm very sorry if I missed anything; this is my first time doing this.

**Comment by punchready** [comment]
Fixing on the way in #2626
