### ISSUE TITLE
Missing or incorrect documentation for field/packet type (Documentation update request)

### ISSUE THREAD

**Issue by ghost** [Pryaxis/TShock#2641]
### Discussed in https://github.com/Pryaxis/TShock/discussions/2640

<div type='discussions-op-text'>

<sup>Originally posted by **kvxmmu** July 21, 2022</sup>
# Incorrect behaviour

The problem is `Connect request [1]` - https://tshock.readme.io/docs/multiplayer-packet-structure#connect-request-1
If client send payload string without leading byte length, then server will disconnect it with the LegacyMultiplayer reason.

# Official terraria client behaviour

Official terraria client sends version with the leading byte length

# Payload Example (Packet headers omitted)

`0xB 0x54 0x65 0x72 0x72 0x61 0x72 0x69 0x61 0x32 0x34 0x38` (b'\x0bTerraria248') - valid
`0x54 0x65 0x72 0x72 0x61 0x72 0x69 0x61 0x32 0x34 0x38` (b'Terraria248') - invalid (LegacyMultiplayer.4)

# Suggestion

If String is encoded like: `length + utf8_bytes` please note that. Is documentation contains structs without details like missing/incorrect field/size/offset?</div>

**Comment by drunderscore** [comment]
Newer and nicer documentation can be found at: https://docs.tshock.co (disclaimer: I've written the Developer stuff)

You kinda just have to know these things, or take two seconds to look at a decompilation. Just use the new documentation -- Readme is deprecated in my eyes.

EDIT: Additionally, Terraria doesn't send byte length prefix, but rather a 7-bit encoded integer length prefix... so I don't see why you're making an issue like this without properly looking at it!

**Comment by ghost** [comment]
Very helpful, thanks! Byte length prefix is an assumption, I see that this assumption was not right.

**Comment by bartico6** [comment]
To be clear, any time a 'String' is mentioned in the docs, it has a length prefix.

The reason for this is C#'s implementation of BinaryWriter and BinaryReader. Writing a string to a binarywriter will first measure the string's length, encode it in a 7-bit int, and then write the length + string right after.

It should've been documented properly, but technically isn't wrong - and if you use the same class (which is 99% of the userbase of this guide) - you'll just call `.ReadString()` and it'll work.
