### ISSUE TITLE
Support Terraria v1.4.4.x

### ISSUE THREAD

**Issue by ngara** [Pryaxis/TShock#2668]
Terraria version 1.4.4.1 was just released today!

**Comment by maige2002** [comment]
i can't enter my server now /(ㄒoㄒ)/~~

**Comment by Jimmy-SafeCash** [comment]
Confirmed - same issue.

**Comment by hakusaro** [comment]
It you want to discuss this further, please go to discussions or some other venue — issues are for bug reports / etc. We’re working on support for 1.4.4.

See also: https://github.com/Pryaxis/TShock/discussions/2667

**Comment by hakusaro** [comment]
The only issue stopping us from releasing our code fully is #2675 unfortunately.

**Comment by hakusaro** [comment]
I think this is done.
