### ISSUE TITLE
Axe of Regrowth does not replant trees automatically.

### ISSUE THREAD

**Issue by Marotheit** [Pryaxis/TShock#2713]
* TShock version: 5.0.0-beta
* TShock build number (if known): d3f542c

#### Any stack traces or error messages (if known)?

`Bouncer / OnPlaceObject rejected awkward tile creation/selection from <player>`

[Debug Log](https://github.com/Pryaxis/TShock/files/9743679/2022-10-10_00-21-36.log)

#### What plugins and what versions of those plugins are you running?

None (except TShock).

**Comment by drunderscore** [comment]
Yeah I confirmed this yesterday, just wasn't at my PC to do anything -- will add a special case when using this item later today :)
