### ISSUE TITLE
Region protections not working?

### ISSUE THREAD

**Issue by jgranserver** [Pryaxis/TShock#2721]
* TShock version: TShock 1.4.4.5 beta
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. Region protection does not do anything after defining a region.
2. Tried to test it with a other player and still doesn't work.

#### Any stack traces or error messages (if known)?

```
PUT SUPER LONG ERROR MESSAGES IN THE TICK MARKS
```

#### What plugins and what versions of those plugins are you running?

If I didn't provide any logs this issue, please close my issue immediately. I'm sorry for the inconvenience.

**Comment by hakusaro** [comment]
> If I didn't provide any logs this issue, please close my issue immediately. I'm sorry for the inconvenience.

No problemo! If you accidentally said this in-error, please provide a video, logs, etc. Thank you.

**Comment by jgranserver** [comment]
https://textdoc.co/7Y4LjwMC0DREKNcX

**Comment by jgranserver** [comment]
https://textdoc.co/MurUJgqnSHmWtca4

**Comment by jgranserver** [comment]
https://pastebin.com/LZhGvGbP

**Comment by hakusaro** [comment]
Maybe related to #2712
