### ISSUE TITLE
Don't Log commands that don't log if they can't be executed

### ISSUE THREAD

**Issue by oz5581** [Pryaxis/TShock#2779]
There was a issue before where if a player executed a command that had the 'DoLog' enabled but doesn't have permission to execute it, it will still show the message in console saying: 'Player tried to execute: /command'
I feel like this change should be added because if in some case where someone tried to execute /login or /password without knowing they didn't have permission will just show the password in console. its very easy to add just add cmd.dolog (sorry idk how to do pull requests) 

![image](https://user-images.githubusercontent.com/78177269/199094988-dbcb1bb8-91b8-44d1-9603-877ba274cf4a.png)

**Comment by sgkoishi** [comment]
I believe `/user`, `/login`, `/register` and `/password` are already set to `DoLog = false` so they should already be ignored?
https://github.com/Pryaxis/TShock/blob/45ea3cc771f7680fc9a033c7a45a475b59f6b850/TShockAPI/Commands.cs#L229-L259



Edit:
I see what you mean, you could just click the edit button [here](https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/Commands.cs) for a pull request.
![image](https://user-images.githubusercontent.com/9637711/199108993-a41e6deb-850d-4724-9eaf-6c5749dc0aff.png)

**Comment by punchready** [comment]
Yes but the command executor does not check for that when logging command attempts with permission failure, which is exactly what this issue is about. The screenshot might be a bit confusing because it shows the result of the suggested change, not the current code.

**Comment by sgkoishi** [comment]
Or maybe we could change the logging behaviour that only shows the command itself without args if `DoLog == false` - it sounds somehow better

**Comment by oz5581** [comment]
> Yes but the command executor does not check for that when logging command attempts with permission failure, which is exactly what this issue is about. The screenshot might be a bit confusing because it shows the result of the suggested change, not the current code.

ye thats what i meant
