### ISSUE TITLE
Issues with Town Slimes

### ISSUE THREAD

**Issue by ScrapDragon2** [Pryaxis/TShock#2789]
Don't have debug logs, but the basic gist of it is that the Surly Slime NPC -- the one you need to fish up during a Blood Moon -- is not possible to get. While using a Sonar Potion to check what's on the line, the Surly Slime would pop up, I fish it out, and nothing. It does not spawn at all. Line did not break (as I had the Lavaproof Tackle Bag equipped), and I tested it multiple times. Works in Single Player, and Multiplayer using base server, but not in TShock. No crashes, just... Doesn't spawn the Surly Slime.

* TShock version: 1.4.4.7
* TShock build number (if known): Current "mostly stable" release.

#### Reproduction steps (if applicable)?

1. Activate a Blood Moon
2. Use Sonar Potion (If you want, optional, but makes for testing this much easier and more consistent.)
3. Go fishing anywhere in the world during the Blood Moon
4. Wait for the Surly Slime to show up on Sonar.
5. Fish up Surly Slime.
6. Surly Slime does not spawn.

#### Any stack traces or error messages (if known)?
No Stack Traces/Error Messages.

#### Any screenshots?
No Screenshots.

#### What plugins and what versions of those plugins are you running?
No Plugins, just base TShock.

**Comment by instant-segfault** [comment]
Seems like you can't spawn a Squire Slime either. I believe the Surly Slime just needs to be added to `FishableNpcIDs` in `GetDataHandlers.cs` though.

**Comment by drunderscore** [comment]
Actual issue is as stated above, I'll submit the simple fix
