### ISSUE TITLE
Disabled player never get un-controlled

### ISSUE THREAD

**Issue by sgkoishi** [Pryaxis/TShock#2812]
* TShock version: 5.0.0

#### Reproduction steps (if applicable)?

1. SSC false, RequireLogin true
2. Join the server.

#### Any stack traces or error messages (if known)?
https://github.com/Pryaxis/TShock/blob/a00d5ed2a94c26a8a47ec66421b4a6f706b02b77/TShockAPI/TShock.cs#L1193-L1204
The player will be Disabled because not logged in.
https://github.com/Pryaxis/TShock/blob/a00d5ed2a94c26a8a47ec66421b4a6f706b02b77/TShockAPI/Commands.cs#L808-L812
They can not log in because they were disabled.

The SSC server will just have the players Disabled once and they can wait till expires.

**Comment by drunderscore** [comment]
Yup, absolutely, thanks for bringing this to my/our attention.

I had recalled this feature being in TShock, but couldn't find a corresponding config entry for it, but obviously this is it.

We can either:
- Immediately remove any crowd-controlling buffs (that being frozen, webbed and stone) upon login.
- Or, (the "proper" solution), have Re-Logic implement what is described in https://github.com/Pryaxis/Terraria/issues/12, allowing us to use the `SyncLoadout` packet safely and consistently to change player's own loadout index.

I will end up PR-ing the first option ASAP, as this is obviously an unacceptable behavior, is an acceptable behavioral change (imo), and we shouldn't be superficially waiting on _possible_ implementation of changes by Re-Logic.

**Comment by drunderscore** [comment]
So unfortunately my implementation of option 1 fell short...

The `Player.CCed` property represents the player being either frozen, webbed, or stoned. These states are gathered from the fields `Player.frozen`, `Player.webbed`, and `Player.stoned` respectively.

However, these fields are not _always_ representative of the player's active buffs, depending on when the buffs were applied.

These fields are reset to `false` in `Player.ResetEffects`, which is called for _every_ `Player.Update`.
These fields are then updated again in `Player.UpdateBuffs`, based on the player's active buffs, which is called for _every_ `Player.Update`, not too long after `Player.ResetEffects`.

This essentially means that the player on the client would need to tick at _least_ once for the buff removal to perform what we want it to. This means that I won't be able to implement what I described earlier at all.

For now, I will simply relax the restriction for CC'd players during login to _only_ occur on servers with SSC enabled, as that is only where it can cause issues, and additionally, it would allow the `RequireLogin` config option to once again continue functioning usefully.
