### ISSUE TITLE
new game version(1.4.4.9) doesnt match latest tshock

### ISSUE THREAD

**Issue by 1415931284** [Pryaxis/TShock#2838]
* TShock version:5.1.2
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. Some step
2. Some other step
3. Some bigger step
4. This is the problem

#### Any stack traces or error messages (if known)?

```
PUT SUPER LONG ERROR MESSAGES IN THE TICK MARKS
```

#### What plugins and what versions of those plugins are you running?

If I didn't provide any logs this issue, please close my issue immediately. I'm sorry for the inconvenience.

**Comment by sgkoishi** [comment]
The nightly version is 1.4.4.9, or you can use some plugin to trick the version.

**Comment by 1415931284** [comment]
> The nightly version is 1.4.4.9, or you can use some plugin to trick the version.

thx for ur reply! and what is the nightly version (sry im new to this game)

**Comment by ckocyigit** [comment]
Here is a nice documentation with video for experimental versions:
https://ikebukuro.tshock.co/#/?id=experimental-downloads

**Comment by vitor-poga** [comment]
> The nightly version is 1.4.4.9, or you can use some plugin to trick the version.

Name of the plugin pls

**Comment by sgkoishi** [comment]
> > The nightly version is 1.4.4.9, or you can use some plugin to trick the version.
> 
> Name of the plugin pls

`Crossplay` and `NoVersionLimit`.

`NoVersionLimit` simply removes the version check, so it works for all versions without updating, but players might experience bugs if they don't match.
`Crossplay` actually check and handle some of the difference between versions so less bug, but someone had to manually check them to get things to work and it takes time.

**Comment by 1415931284** [comment]
> 

crossplay, or at least the one I have, only works with older versions.

and I cant find noversionlimit.

and again, thx for ur help. ur a good man.

**Comment by 1415931284** [comment]
> > > The nightly version is 1.4.4.9, or you can use some plugin to trick the version.
> > 
> > 
> > Name of the plugin pls
> 
> `Crossplay` and `NoVersionLimit`.
> 
> `NoVersionLimit` simply removes the version check, so it works for all versions without updating, but players might experience bugs if they don't match. `Crossplay` actually check and handle some of the difference between versions so less bug, but someone had to manually check them to get things to work and it takes time.

crossplay, or at least the one I have, only works with older versions.

and I cant find noversionlimit.

and again, thx for ur help. ur a good man.

**Comment by sgkoishi** [comment]
> crossplay, or at least the one I have, only works with older versions.
> 
> and I cant find noversionlimit.
> 
> and again, thx for ur help. ur a good man.

The 'official' version of `Crossplay` is outdated, there is [a simple fix](https://github.com/Moneylover3246/Crossplay/pull/53/files) but you had to compile it by yourself.
Google `"NoVersionLimit"` shows a Chinese forum but I'm not quite sure - it's free, you need 'coin' to download but also get 'coin' by just logging in

**Comment by 1415931284** [comment]
> > crossplay, or at least the one I have, only works with older versions.
> > and I cant find noversionlimit.
> > and again, thx for ur help. ur a good man.
> 
> The 'official' version of `Crossplay` is outdated, there is [a simple fix](https://github.com/Moneylover3246/Crossplay/pull/53/files) but you had to compile it by yourself. Google `"NoVersionLimit"` shows a Chinese forum but I'm not quite sure - it's free, you need 'coin' to download but also get 'coin' by just logging in

that chinese one works! bless u.

**Comment by xenus** [comment]
> there is [a simple fix](https://github.com/Moneylover3246/Crossplay/pull/53/files) but you had to compile it by yourself.

If someone needs it, then the compiled version is published in my repository [here](https://github.com/xenus/Crossplay/releases/tag/2.1.2)

**Comment by drunderscore** [comment]
TShock 5.1.3 supports 1.4.4.9, and has long since been out.
