### ISSUE TITLE
Webbed status glitch

### ISSUE THREAD

**Issue by Op0m** [Pryaxis/TShock#2875]
So there's a troubling bug where if you have a Modified that has a size effect it will make you get a webbed effect every time you attack.

And i use tshock v5.1.3(latest)

So can you guys can fix it? (Plssss)

**Comment by sgkoishi** [comment]
The latest version is `TShock 5.1.3 for Terraria 1.4.4.9`.

**Comment by Op0m** [comment]
Ah ok look like i wrong type yeah i use 5.1.3 
But i want they fix this issue because iam melee user and cant use glove its painful

**Comment by drunderscore** [comment]
Cannot reproduce, using Titan Glove and Large Blade of Grass.

It would be helpful to share a video, or even better, set `DebugLogs` to `true` in your config, and share the log output once you are webbed.

**Comment by sgkoishi** [comment]
Likely duplicate of #2804.
Should be fixed in [latest dev version](https://github.com/Pryaxis/TShock/actions/workflows/ci-otapi3.yml?query=branch%3Ageneral-devel+event%3Apush), you can try it.

**Comment by Op0m** [comment]
Here i guess

**Comment by Op0m** [comment]
Dam i cant sent video i guess YouTube link?

**Comment by Op0m** [comment]
> Cannot reproduce, using Titan Glove and Large Blade of Grass.
> 
> It would be helpful to share a video, or even better, set `DebugLogs` to `true` in your config, and share the log output once you are webbed.

![Uploading Screenshot_2022-12-17-11-40-13-522_com.android.chrome.jpg…]()

**Comment by Op0m** [comment]
Debug: GetDataHandlers / HandlePlayerBuffList handled event and sent data Redigit

Debug: Bouncer / OnNewProjectile rejected from projectile damage limit from Redigit 6144/1175

Debug: Bouncer / OnNewProjectile rejected from projectile damage limit from Redigit 6144/1175

Debug: GetDataHandlers / HandlePlayerBuffList handled event and sent data Redigit

Player Redigit has been disabled for Projectile damage is higher than 1175..

Debug: Bouncer / OnNewProjectile rejected from projectile damage limit from Redigit 6144/1175

Debug: Bouncer / OnNewProjectile rejected from projectile damage limit from Redigit 6144/1175

Debug: GetDataHandlers / HandlePlayerBuffList handled event and sent data Redigit

> Cannot reproduce, using Titan Glove and Large Blade of Grass.
> 
> It would be helpful to share a video, or even better, set `DebugLogs` to `true` in your config, and share the log output once you are webbed.

**Comment by sgkoishi** [comment]
You can try the dev version. Here's the current one: https://github.com/Pryaxis/TShock/actions/runs/3683343469
Scroll to the bottom and download the right version.

**Comment by Op0m** [comment]
> Cannot reproduce, using Titan Glove and Large Blade of Grass.
> 
> It would be helpful to share a video, or even better, set `DebugLogs` to `true` in your config, and share the log output once you are webbed.

Ok i think its because The server think my projectile Has great dmg

**Comment by Op0m** [comment]
They should make Default max projectile and dmg into 10k now because 1.4.4 overhaul Melee Weapon
