### ISSUE TITLE
Quick Stack range is shortened by range check

### ISSUE THREAD

**Issue by boddyn** [Pryaxis/TShock#2885]
* TShock version: 5.1.3.0
* TShock build number (if known):

* Description of issue:
In the current version of Terraria (1.4.4.9 PC), and I believe since 1.4.4, the range for quick stacking to nearby chests is ~37. This is verified by both the wiki and my own personal tests.
However, on servers using TShock, the quick stack range is maximally 32 by my own measurements.

* Expected problem and fix:
[Quick stack range check](https://github.com/Pryaxis/TShock/blob/24bb002e646c88dacb1d1d864f8c171b48784435/TShockAPI/TShock.cs#L685-L689)
[IsInRange](https://github.com/Pryaxis/TShock/blob/95d157fd5d24f8997578ca9a4d67f988b6b7d7f1/TShockAPI/TSPlayer.cs#L752-L762)
The code at the first link runs when a player tries to quick stack. If the chest is not in range, it returns without allowing the player.
The function IsInRange is called without a supplied value for range, and so defaults to 32. Adding a range value of, say, 40 on line 685 should fix  this issue.

#### Reproduction steps (if applicable)?

1. Go to an isolated area.
2. Place a chest down and place gray bricks in it, leaving some in your personal inventory.
3. Walk a distance away using the ruler tool.
4. While, say, 35 tiles away, open your inventory.
5. Click the "Quick Stack to Nearby Chests" button.
6. Observe that the gray bricks in your inventory do not quick stack to the chest.

#### Any stack traces or error messages (if known)?
None, nor would I expect any.

#### Any screenshots?

![image](https://user-images.githubusercontent.com/16693233/209925239-fbbc4ac9-abfe-4ada-88fc-4e56e4c43a51.png)
Fig. 1 - Showing setup of inventories.
![image](https://user-images.githubusercontent.com/16693233/209925327-eee4b3bd-d77a-4193-9621-9be81656e72b.png)
Fig. 2 - At range of 35 tiles, quick stacking to nearby chests does not work.
![image](https://user-images.githubusercontent.com/16693233/209925399-c49e80ce-9533-431c-9d0c-6dec67fc3a8f.png)
Fig. 3 - Now at a range of 32.
![image](https://user-images.githubusercontent.com/16693233/209925478-1db33d9b-08f7-4f7b-8b43-c9e39d49477b.png)
Fig. 4 - At the range of 32, you can now quick stack to the chest.

**Comment by sgkoishi** [comment]
Actually, this check is unnecessary. The client only sends the slot, and the server determines which chest to use and checks for the range (`Distance(player, chest) < 600`) before this hook.

<sub>600 = 37.5 tiles</sub>
