### ISSUE TITLE
Console display error

### ISSUE THREAD

**Issue by CatWhyN0t** [Pryaxis/TShock#2889]
* TShock version: 5.1.3 for Terraria 1.4.4.9
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. Installed TShock, dependencies and Vannilaifier plugin
2. chmod u+x TShock*
3. ./TShock.Server
4. And then this happens (screenshot)

#### Any stack traces or error messages (if known)?

```
This appears every time I start the world on the server. Everything works fine except for the console, I can't write anything.
```

#### Any screenshots?

![image](https://user-images.githubusercontent.com/78268087/210403898-9f7b492a-0f8c-494d-85d3-31f4105006fd.png)

#### Any log messages from files that end in `.log` or `.txt`? What are the last 100 log messages from the server console?

[2023-01-02_22-27-55.log](https://github.com/Pryaxis/TShock/files/10338401/2023-01-02_22-27-55.log)

#### What plugins and what versions of those plugins are you running?

If I didn't provide any logs this issue, please close my issue immediately. I'm sorry for the inconvenience.

**Comment by ACaiCat** [comment]
Do you use "screen"?

If so, you can try "tmux" instead.

Or maybe your SSH client doesn't support changing the title

**Comment by CatWhyN0t** [comment]
> 

Thank you. The error is gone.
