### ISSUE TITLE
Anti-cheat for Terraria Trainer FLiNG

### ISSUE THREAD

**Issue by louanfontenele** [Pryaxis/TShock#2950]
Hello, I would like to report a hack that simply bypasses the characters' SSC configs making them able to unlock all recipes and simply be able to use and craft any items.

(link removed)

**Comment by drunderscore** [comment]
Please do not share links to tools or resources that allow cheating.

Unfortunately Terraria is not a perfect game, and preventing such cheating is not entirely realistic within TShock.

**Comment by louanfontenele** [comment]
> Please do not share links to tools or resources that allow cheating.
> 
> Unfortunately Terraria is not a perfect game, and preventing such cheating is not entirely realistic within TShock.

Is there no way to avoid?

**Comment by Kojirremer** [comment]
Most likely impossible without modding the game client itself for everyone involved, which can not be done.

**Comment by louanfontenele** [comment]
> Most likely impossible without modding the game client itself for everyone involved, which can not be done.

Oh, ok, thanks.
