### ISSUE TITLE
Sever IP with console

### ISSUE THREAD

**Issue by ghost** [Pryaxis/TShock#2972]
**Is your feature request related to a problem? Please describe.**
kind of... it is the server ip in the console (this is in the window name)

**Describe the solution you'd like**
If the server console displays the server IP address (public) it would work better for if other players outside the network wants to join

**Describe alternatives you've considered**
if this cannot work please find a way to make it to where it enables steam multiplayer on the server.
or you can set it to the IP address (private) for LAN game play

**Comment by sgkoishi** [comment]
It's not quite feasible to know their own public IP that works for players to join, and in some cases, they don't have one. 
TShock does not show its IP in the window name, what it shows is the IP it listens to (usually it's `0.0.0.0`, which means it accepts anyone that can connect to it).

To play with friends via Steam, try installing a corresponding plugin (e.g. [SteamEnablerPlugin by Arthri](https://github.com/Arthri/SteamEnablerPlugin)).
To play with friends in LAN, you don't need to do anything with TShock - as said before, TShock by default responds to anyone that can connect to it. All you need is to set up LAN properly to have them connected.

**Comment by ghost** [comment]
Thank you @sgkoishi
