### ISSUE TITLE
starting and maximum HP and MP

### ISSUE THREAD

**Issue by ghost** [Pryaxis/TShock#2984]
**Is your feature request related to a problem? Please describe.**
this is a pet-peeve

**Describe the solution you'd like**
The problem is that the starting HP and MP is still 100HP and 20MP on start even when i change it, the same thing to the maximum... it does not affect the SSC
This problem to be fixed

**Describe alternatives you've considered**
Removing this in the config files

**Comment by punchready** [comment]
Are you properly changing the `config.json` file? Based on some of your activity on github, it seems like you are just changing the config class source code, which is NOT the correct way of changing the config.

**Comment by ghost** [comment]
no... i was origanlly changing it in the config.json file on my computer... that fork is just for me to mess around....
