### ISSUE TITLE
Player failed to load map after join the game

### ISSUE THREAD

**Issue by tungdo0602** [Pryaxis/TShock#3003]
For some reason my friend join the server and got this problem.
![image](https://github.com/Pryaxis/TShock/assets/89498812/2fd62617-413d-4283-9f0a-eb2433e88551)

On my view:
![image](https://github.com/Pryaxis/TShock/assets/89498812/8cb6ea23-3999-4985-90b6-77323714608a)

**Comment by sgkoishi** [comment]
Sounds like a networking issue... Try chat or run `/home`?

**Comment by tungdo0602** [comment]
> Sounds like a networking issue... Try chat or run `/home`?

I still can see his chat
