### ISSUE TITLE
Can't write log file

### ISSUE THREAD

**Issue by tungdo0602** [Pryaxis/TShock#3004]
![image](https://github.com/Pryaxis/TShock/assets/89498812/748a5ac5-04a9-43ee-aaa7-82d8f687038d)

**Comment by xtpkt** [comment]
You hosting on google drive?

**Comment by tungdo0602** [comment]
> You hosting on google drive?

yes

**Comment by bartico6** [comment]
[This probably answers your question](https://superuser.com/a/1702214)

**Comment by tungdo0602** [comment]
> [This probably answers your question](https://superuser.com/a/1702214)

thank you for your solution but isn't it disconnect the drive and remount? After that the server could crashed due the data is stored on drive.

**Comment by ghost** [comment]
How did you host this on google drive?

**Comment by tungdo0602** [comment]
I run it on google colab
