### ISSUE TITLE
Remove SuperAdminGroup

### ISSUE THREAD

**Issue by MarioE** [Pryaxis/TShock#915]
Instead of having a hardcoded superadmin group, simply have a normal, default superadmin group. This would, logically, remove the need for several config options.

**Comment by nicatronTg** [comment]
It's worth noting that my initial reasoning for having it in the first place was, like on Linux, to have a root account that has all power that is specifically designated not to be used on a regular basis. At this point, however, I doubt many Terraria users treat it as that.
