### ISSUE TITLE
Provide more feedback upon freezing a player.

### ISSUE THREAD

**Issue by Ijwu** [Pryaxis/TShock#973]
Would be nice to have more feedback when a player is frozen with the exact reason(s) why they were frozen.

**Comment by Gummin** [comment]
I suppose I agree, sometimes it can be very lacking in information.

**Comment by nicatronTg** [comment]
If I might add: we have in the past neglected to inform players why they are disabled in the event that they're tripping cheat checks and the like. The server owner is notified via console what caused it and why.

**Comment by Puremin0rez** [comment]
Would it be possible to show how much damage they did that triggered the damage threshold? It says they did over 175, but doesn't say how much. It think that'd help in finding a good default value. Same thing with the Projectile one.

**Comment by nicatronTg** [comment]
That should be added to the console message, definitely.

**Comment by ProfessorXZ** [comment]
@Ijwu Is this still an issue in the latest release(s)? If I remember correctly the `TSPlayer.Disable()` method prints both to console and the player. E.g "Professor X has been disabled for holding a banned item: Meowmere". If it still is an issue, what would be the goal of this? Make the message a bit clearer?

**Comment by nicatronTg** [comment]
@ijwu please comment on github whether or not this should be kept open

**Comment by ProfessorXZ** [comment]
I just checked the code and nothing regarding feedback when disabling players has changed since last year. Maybe the purpose in fact was to clarify the output message a bit more.

**Comment by Enerdy** [comment]
@Ijwu please comment whether or not this should be kept open as per @hakusaro's request 2 years ago.

**Comment by Ijwu** [comment]
Closing due to irrelevance now.
